import type { ComponentType } from "react";
import type { StyleMeta } from "../../lib/styles";
import {
  MinimalismPreview,
  UltraMinimalismPreview,
  SwissDesignPreview,
  JapaneseMinimalismPreview,
  ScandinavianPreview,
  MonochromePreview,
  EditorialMinimalismPreview,
  LuxuryMinimalismPreview,
  ProductMinimalismPreview,
  FunctionalMinimalismPreview,
} from "./batch1-minimal";
import {
  BrutalismPreview,
  NeoBrutalismPreview,
  PlayfulBrutalismPreview,
  CorporateBrutalismPreview,
  EditorialBrutalismPreview,
  MinimalBrutalismPreview,
  ColorfulBrutalismPreview,
  AntiDesignPreview,
  PostBrutalismPreview,
  IndustrialBrutalismPreview,
} from "./batch2-brutalist";
import {
  MaximalismPreview,
  PlayfulMaximalismPreview,
  EditorialMaximalismPreview,
  PsychedelicMaximalismPreview,
  TypographyMaximalismPreview,
  ColorMaximalismPreview,
  DigitalMaximalismPreview,
  ChaosDesignPreview,
  LuxuryMaximalismPreview,
  GraphicMaximalismPreview,
} from "./batch3-maximalist";
import {
  EditorialMagazinePreview,
  NewspaperPreview,
  FashionEditorialPreview,
  PosterInspiredPreview,
  SwissPosterPreview,
  BauhausPreview,
  MemphisPreview,
  Y2KPreview,
  RetroInternetPreview,
  WebcorePreview,
  DesktopUIPreview,
  Windows95Preview,
  MacOSPreview,
  TerminalPreview,
  HackerAestheticPreview,
  CyberpunkPreview,
  FuturismPreview,
  SciFiUIPreview,
} from "./batch4-editorial-retro";
import {
  GlassmorphismPreview,
  NeumorphismPreview,
  ClaymorphismPreview,
  SkeuomorphismPreview,
  BentoGridPreview,
  CardBasedUIPreview,
  CorporateSaaSPreview,
  StripeInspiredPreview,
  LinearInspiredPreview,
  NotionInspiredPreview,
  GradientDesignPreview,
  AuroraGlowPreview,
  HolographicPreview,
  LiquidChromePreview,
  ThreeDWebDesignPreview,
  ImmersivePreview,
  ScrollytellingPreview,
  ParallaxPreview,
} from "./batch5-soft-product";
import {
  KineticTypographyPreview,
  TypographyFirstPreview,
  VariableFontsPreview,
  OversizedTypographyPreview,
  CollagePreview,
  ScrapbookPreview,
  ZinePunkPreview,
  RisographPreview,
  HalftonePreview,
  GrainNoisePreview,
  HandDrawnPreview,
  IllustrationLedPreview,
  CorporateMemphisPreview,
  OrganicBiophilicPreview,
  EcoSustainablePreview,
  JapandiPreview,
  WabiSabiPreview,
  ArtDecoPreview,
  ArtNouveauPreview,
  MidCenturyModernPreview,
} from "./batch6-type-cut";
import {
  SeventiesRetroPreview,
  EightiesRetroPreview,
  NinetiesRetroPreview,
  VaporwavePreview,
  SynthwavePreview,
  Pixel8BitPreview,
  GamingUIPreview,
  ComicPopArtPreview,
  GraffitiStreetwearPreview,
  QuietLuxuryPreview,
  SurrealismPreview,
  DreamcorePreview,
  LiminalWeirdcorePreview,
  GenerativeAlgorithmicPreview,
} from "./batch7-decades-neon";
import { Frame, Meta } from "./frame";

const previews: Record<string, ComponentType<{ meta: StyleMeta; large?: boolean }>> = {
  "minimalism": MinimalismPreview,
  "ultra-minimalism": UltraMinimalismPreview,
  "swiss-design": SwissDesignPreview,
  "japanese-minimalism": JapaneseMinimalismPreview,
  "scandinavian": ScandinavianPreview,
  "monochrome": MonochromePreview,
  "editorial-minimalism": EditorialMinimalismPreview,
  "luxury-minimalism": LuxuryMinimalismPreview,
  "product-minimalism": ProductMinimalismPreview,
  "functional-minimalism": FunctionalMinimalismPreview,
  "brutalism": BrutalismPreview,
  "neo-brutalism": NeoBrutalismPreview,
  "playful-brutalism": PlayfulBrutalismPreview,
  "corporate-brutalism": CorporateBrutalismPreview,
  "editorial-brutalism": EditorialBrutalismPreview,
  "minimal-brutalism": MinimalBrutalismPreview,
  "colorful-brutalism": ColorfulBrutalismPreview,
  "anti-design": AntiDesignPreview,
  "post-brutalism": PostBrutalismPreview,
  "industrial-brutalism": IndustrialBrutalismPreview,
  "maximalism": MaximalismPreview,
  "playful-maximalism": PlayfulMaximalismPreview,
  "editorial-maximalism": EditorialMaximalismPreview,
  "psychedelic-maximalism": PsychedelicMaximalismPreview,
  "typography-maximalism": TypographyMaximalismPreview,
  "color-maximalism": ColorMaximalismPreview,
  "digital-maximalism": DigitalMaximalismPreview,
  "chaos-design": ChaosDesignPreview,
  "luxury-maximalism": LuxuryMaximalismPreview,
  "graphic-maximalism": GraphicMaximalismPreview,
  "editorial-magazine": EditorialMagazinePreview,
  "newspaper": NewspaperPreview,
  "fashion-editorial": FashionEditorialPreview,
  "poster-inspired": PosterInspiredPreview,
  "swiss-poster": SwissPosterPreview,
  "bauhaus": BauhausPreview,
  "memphis": MemphisPreview,
  "y2k": Y2KPreview,
  "retro-internet": RetroInternetPreview,
  "webcore": WebcorePreview,
  "desktop-ui": DesktopUIPreview,
  "windows-95": Windows95Preview,
  "mac-os": MacOSPreview,
  "terminal": TerminalPreview,
  "hacker-aesthetic": HackerAestheticPreview,
  "cyberpunk": CyberpunkPreview,
  "futurism": FuturismPreview,
  "sci-fi-ui": SciFiUIPreview,
  "glassmorphism": GlassmorphismPreview,
  "neumorphism": NeumorphismPreview,
  "claymorphism": ClaymorphismPreview,
  "skeuomorphism": SkeuomorphismPreview,
  "bento-grid": BentoGridPreview,
  "card-based-ui": CardBasedUIPreview,
  "corporate-saas": CorporateSaaSPreview,
  "stripe-inspired": StripeInspiredPreview,
  "linear-inspired": LinearInspiredPreview,
  "notion-inspired": NotionInspiredPreview,
  "gradient-design": GradientDesignPreview,
  "aurora-glow": AuroraGlowPreview,
  "holographic": HolographicPreview,
  "liquid-chrome": LiquidChromePreview,
  "3d-web-design": ThreeDWebDesignPreview,
  "immersive": ImmersivePreview,
  "scrollytelling": ScrollytellingPreview,
  "parallax": ParallaxPreview,
  "kinetic-typography": KineticTypographyPreview,
  "typography-first": TypographyFirstPreview,
  "variable-fonts": VariableFontsPreview,
  "oversized-typography": OversizedTypographyPreview,
  "collage": CollagePreview,
  "scrapbook": ScrapbookPreview,
  "zine-punk": ZinePunkPreview,
  "risograph": RisographPreview,
  "halftone": HalftonePreview,
  "grain-noise": GrainNoisePreview,
  "hand-drawn": HandDrawnPreview,
  "illustration-led": IllustrationLedPreview,
  "corporate-memphis": CorporateMemphisPreview,
  "organic-biophilic": OrganicBiophilicPreview,
  "eco-sustainable": EcoSustainablePreview,
  "japandi": JapandiPreview,
  "wabi-sabi": WabiSabiPreview,
  "art-deco": ArtDecoPreview,
  "art-nouveau": ArtNouveauPreview,
  "mid-century-modern": MidCenturyModernPreview,
  "70s-retro": SeventiesRetroPreview,
  "80s-retro": EightiesRetroPreview,
  "90s-retro": NinetiesRetroPreview,
  "vaporwave": VaporwavePreview,
  "synthwave": SynthwavePreview,
  "pixel-8bit": Pixel8BitPreview,
  "gaming-ui": GamingUIPreview,
  "comic-pop-art": ComicPopArtPreview,
  "graffiti-streetwear": GraffitiStreetwearPreview,
  "quiet-luxury": QuietLuxuryPreview,
  "surrealism": SurrealismPreview,
  "dreamcore": DreamcorePreview,
  "liminal-weirdcore": LiminalWeirdcorePreview,
  "generative-algorithmic": GenerativeAlgorithmicPreview,
};

export function StylePreview({ meta, large }: { meta: StyleMeta; large?: boolean }) {
  const Cmp = previews[meta.slug];
  if (!Cmp) {
    const p = meta.preview;
    return (
      <Frame meta={meta} large={large}>
        <div className="flex h-full flex-col justify-center px-[8%]">
          <div style={{ fontFamily: p.display, fontSize: large ? 26 : 15 }}>{meta.name}</div>
          <div style={{ color: p.muted, fontSize: large ? 11 : 7.5 }}>{meta.description}</div>
        </div>
        <Meta meta={meta} large={large} />
      </Frame>
    );
  }
  return <Cmp meta={meta} large={large} />;
}
