export const stylesA = [
{
slug: "minimalism",
name: "Minimalism",
description: "Restrained layouts, generous whitespace and quiet typography that lets content breathe.",
category: "Minimal",
tags: ["minimal", "clean", "whitespace"],
bg: "#FAFAF9", surface: "#FFFFFF", ink: "#1A1A1A", muted: "#737373", accent: "#1A1A1A", accent2: "#4D7CFE",
display: "Inter, Helvetica Neue, Arial, sans-serif",
body: "Inter, Helvetica Neue, Arial, sans-serif",
radius: "8px cards, 6px buttons, pills only for small tags",
border: "1px solid #E7E7E4 on cards; no borders on sections — whitespace separates",
shadow: "Almost none: 0 1px 2px rgba(0,0,0,0.04) on cards; no shadows on text or buttons",
spacing: "8px base unit; section padding 96–128px; card padding 24–32px; max line length 65ch",
aesthetic: "Minimalism removes everything that does not earn its place. One typeface, near-monochrome color, and large fields of whitespace create calm, confident interfaces. Restraint is the decoration: alignment, proportion, and timing carry the entire design.",
principles: ["Subtract before you add — every element must justify itself", "One typeface, two weights, three sizes per view", "Whitespace is a structural material, not empty space"],
layout: "Single centered column, max-width 1120px, 12-column grid for features. One idea per viewport; sections separated by 96px+ of space, never by rules or boxes.",
buttons: "Solid black 44px buttons with 6px radius and white labels; secondary is 1px-bordered transparent. Hover darkens to #333 with a 150ms ease; no shadows, no gradients.",
cards: "White cards on off-white ground with 1px hairline borders and 8px radius. Title in 17px semibold, body in 15px gray; no icons unless functional.",
nav: "Top bar: wordmark left, 4–5 links center or right in 14px medium, single CTA. Sticky with backdrop blur and hairline bottom border on scroll.",
imagery: "Sparse, large, and deliberate — one hero image or none. Photography should be desaturated and geometric; prefer product shots on plain grounds.",
icons: "1.5px stroke line icons (Lucide/Feather style), 18–20px, ink or gray. Never filled, never multicolor.",
texture: "None. Flat matte surfaces only; depth comes from layering whitespace, never from grain or gradients.",
motion: "150–200ms ease-out micro-transitions only. Fades and 4px rises on reveal; nothing bounces, nothing spins.",
avoid: ["Adding gradients, shadows, or decoration to fill space", "More than one accent or more than two font weights", "Centering everything — use left alignment for text blocks", "Boxes inside boxes; let whitespace group content", "Uppercase micro-labels everywhere"],
},
{
slug: "ultra-minimalism",
name: "Ultra-Minimalism",
description: "Extreme reduction: tiny type, vast whitespace and almost no visible interface.",
category: "Minimal",
tags: ["minimal", "reduction", "quiet"],
bg: "#FFFFFF", surface: "#FFFFFF", ink: "#111111", muted: "#A3A3A3", accent: "#111111", accent2: "#0000EE",
display: "Helvetica Neue, Inter, Arial, sans-serif",
body: "Helvetica Neue, Inter, Arial, sans-serif",
radius: "0px — sharp or borderless; pills never",
border: "Hairlines only: 1px solid #EDEDED to separate, never to decorate",
shadow: "Zero shadows anywhere. Depth is forbidden; separation comes from space and hairlines",
spacing: "Base unit 4px; section padding 140–200px; paragraphs capped at 60ch; navigation floats in vast margins",
aesthetic: "Ultra-minimalism is minimalism taken to its limit: 13px type floating in oceans of white, hairline rules, and interfaces that seem embarrassed to exist. It suits portfolios, essays, and tools whose content is the entire point. Every pixel on screen should feel inevitable.",
principles: ["If it can be removed without losing meaning, remove it", "Type size stays small; presence comes from position, not scale", "Gray text and hairlines before black text and boxes"],
layout: "Narrow centered column (640–760px) with enormous vertical rhythm. No grids, no sidebars, no cards — a vertical sequence of text blocks and hairline dividers.",
buttons: "Text links, not buttons: 13–14px underlined or plain, turning solid on hover. A primary action may be a 1px-bordered rectangle, 40px tall, sharp corners.",
cards: "No cards. Content blocks separated by 64px+ of space and occasionally a full-width hairline.",
nav: "A single row of tiny 12–13px links, often just a wordmark and 2–3 items. Fixed minimal footer with copyright and one email link.",
imagery: "Almost none; when used, small and centered with wide margins. Black-and-white or heavily muted imagery only.",
icons: "Avoid icons entirely. If unavoidable, 14px 1px-stroke glyphs in light gray.",
texture: "Pure flat white. No paper grain, no gradients — sterility is the point.",
motion: "Nearly static. 200ms opacity fades at most; content should feel printed, not animated.",
avoid: ["Cards, shadows, rounded corners, or badges", "Hero sections or large display type", "Color — one blue link color is the entire palette", "Marketing patterns like logos walls or feature grids", "Bold weights above 500 for body content"],
},
{
slug: "swiss-design",
name: "Swiss Design",
description: "Grid-driven layouts, disciplined typography and strong visual hierarchy.",
category: "Minimal",
tags: ["grid", "typography", "rational"],
bg: "#F4F2ED", surface: "#FFFFFF", ink: "#111111", muted: "#6E6A61", accent: "#E30613", accent2: "#0B3D91",
display: "Helvetica Neue, Helvetica, Arial, sans-serif",
body: "Helvetica Neue, Helvetica, Arial, sans-serif",
radius: "0px everywhere — Swiss corners are always sharp",
border: "Hairline black rules (1–2px) as structural dividers; grid lines may show deliberately",
shadow: "None. Hierarchy comes from scale, weight, and position — never elevation",
spacing: "8px base; strict 12-column grid with 24px gutters; section padding 80–120px; baseline rhythm in 4px steps",
aesthetic: "The International Typographic Style: asymmetric grids, flush-left ragged-right type, oversized numerals, and one decisive red accent. Objective, systematic, and legible at any distance. Content is engineered, not decorated — mathematics you can see.",
principles: ["The grid is visible logic, not a cage — align everything to it", "Flush left, ragged right, never justified or centered", "One accent color used sparingly and always deliberately"],
layout: "Asymmetric 12-column grid; large empty cells are intentional. Oversized headlines span 7–9 columns; meta and body occupy narrow 3–4 column rails. Numbered sections (01, 02, 03).",
buttons: "Sharp rectangular buttons, black fill with white uppercase 12px labels tracked +0.08em. Secondary is a 2px black outline. Hover inverts.",
cards: "Borderless white blocks separated by black hairlines, or pure grid cells with number + title + rule. No elevation, no radius.",
nav: "Top row: index number, wordmark, section links in small uppercase mono or Helvetica caps. A thick black rule (3–4px) may anchor the header.",
imagery: "High-contrast photography cropped hard to grid cells, often duotone or grayscale with red accents. Images align to columns exactly.",
icons: "Geometric, constructed icons with uniform 2px strokes; numerals preferred over pictograms where possible.",
texture: "Flat matte paper background (#F4F2ED). Optional visible grid overlay in draft mode; no grain.",
motion: "Precise and fast: 120–180ms linear or ease-out, grid-aligned slides. Number counters and rule-draws suit the style; no bounces.",
avoid: ["Centered layouts or decorative asymmetry that ignores the grid", "Rounded corners, shadows, or gradients", "Serif or script typefaces", "More than one accent color", "Centering body copy or justifying text"],
},
{
slug: "japanese-minimalism",
name: "Japanese Minimalism",
description: "Ma-inspired negative space, muted natural tones and quiet wabi-sabi restraint.",
category: "Minimal",
tags: ["minimal", "ma", "serene"],
bg: "#F7F4EE", surface: "#FFFDF8", ink: "#2B2B28", muted: "#8A867C", accent: "#9C2B2E", accent2: "#4A5D4E",
display: "Hiragino Mincho ProN, Yu Mincho, Georgia, serif",
body: "Hiragino Sans, Inter, Helvetica Neue, sans-serif",
radius: "2–4px, barely-there softness; never pills",
border: "Hairline warm-gray borders (#E3DED2); vertical rules and generous margins do the grouping",
shadow: "A single whisper: 0 1px 3px rgba(43,43,40,0.05). Ink-inspired, never lifted",
spacing: "Ma (negative space) as the primary material: sections breathe 120–160px; line-height 2.0 for prose; wide letter-spacing on labels",
aesthetic: "Inspired by ma — the pregnant emptiness between things — and wabi-sabi imperfection. Warm paper tones, a vermilion hanko-like accent, vertical rhythm, and content placed low and off-center. Designs feel like a tea room: still, warm, and complete with very little.",
principles: ["Ma first: space between elements matters more than the elements", "Natural, desaturated color drawn from paper, stone, moss, and clay", "Asymmetry and off-center placement feel more alive than symmetry"],
layout: "Off-center compositions with large voids; content often sits in the lower two-thirds. Vertical Japanese-style dividers and small caps labels; max-width 960px.",
buttons: "Quiet rectangles with 1px warm-gray borders and dark text; primary fills deep ink. Hover deepens color slowly (300ms). Wide letter-spacing on labels.",
cards: "Paper-toned panels with hairline borders and vast internal padding (32–48px). Images bleed; text floats in space.",
nav: "Sparse top bar or side column with vertical options. Small tracked labels; a red hanko-square mark as the logo device.",
imagery: "Mist, stone, wood, paper, shadow — natural textures photographed softly. Low contrast, warm white balance, generous crops.",
icons: "Thin brush-like line icons with varied stroke, or simple kanji-like geometric marks. Restrained and few.",
texture: "Subtle washi-paper grain at 3–5% opacity; soft vignettes. Imperfection is welcome if barely visible.",
motion: "Slow and breath-like: 400–600ms ease-in-out fades, ink-wash reveals. Nothing sudden; transitions feel like seasons changing.",
avoid: ["Saturated color fields or neon accents", "Dense grids and packed layouts", "Sharp pure-black on pure-white contrast", "Fast bouncy animation", "Western-style centered hero sections"],
},
{
slug: "scandinavian",
name: "Scandinavian",
description: "Light woods, soft neutrals and functional warmth with hygge approachability.",
category: "Minimal",
tags: ["minimal", "warm", "functional"],
bg: "#F9F7F3", surface: "#FFFFFF", ink: "#2E2C29", muted: "#8C877E", accent: "#C2703D", accent2: "#5B7E6B",
display: "Inter, Avenir, Nunito Sans, sans-serif",
body: "Inter, Avenir, Nunito Sans, sans-serif",
radius: "10–14px friendly rounding on cards and buttons",
border: "Rarely visible; soft tonal separations (#ECE7DD) instead of lines",
shadow: "Soft and warm: 0 8px 30px rgba(46,44,41,0.08). Diffuse like daylight, never hard",
spacing: "8px base; airy 24–32px card padding; sections 88–120px; comfortable, never sparse or dense",
aesthetic: "Scandi design pairs minimalism with warmth: pale oak tones, clay and sage accents, rounded soft geometry, and honest materials. Interfaces feel like a bright Copenhagen apartment — functional, cozy, and quietly optimistic. Friendliness is a feature.",
principles: ["Light first: pale backgrounds, daylight-feel shadows, open layouts", "Warm neutrals over cold grays — beige, oat, clay, sage", "Democratic and friendly: readable sizes, clear actions, no intimidation"],
layout: "Open centered layouts with soft card clusters; photography-forward bands alternating with oat backgrounds. Max-width 1200px, generous gutters.",
buttons: "Pill or 12px-radius buttons in warm clay or deep forest; white 15px labels. Hover lifts 2px with softened shadow. Large touch targets (48px).",
cards: "White or cream cards, 12px radius, soft daylight shadow, 28px padding. Rounded image tops; icon in a tinted rounded square.",
nav: "Light bar with warm wordmark, rounded pill links, and a soft clay CTA. Sticky with blur; friendly and unhurried.",
imagery: "Bright interiors, pale wood, plants, daylight, people at ease. Warm, slightly lifted exposure; rounded corners on all photos.",
icons: "Rounded-line icons (2px, round caps), 20px, in tinted circles. Friendly and consistent sets only.",
texture: "Faint linen or oak-grain at very low opacity; soft daylight gradients from #FFFFFF to #F3EEE5.",
motion: "Gentle 200–300ms ease-out; soft rises and fades. Hover lifts feel buoyant, never snappy.",
avoid: ["Cold blue-grays and stark pure-white sterility", "Hard shadows, sharp corners, or aggressive contrast", "Tiny 12px body text or cramped layouts", "Dark mode as default — light is the home", "Cynical or edgy copy tone"],
},
{
slug: "monochrome",
name: "Monochrome",
description: "Single-hue discipline: black, white and grays engineered into full interfaces.",
category: "Minimal",
tags: ["minimal", "black-white", "contrast"],
bg: "#FFFFFF", surface: "#F5F5F5", ink: "#0A0A0A", muted: "#737373", accent: "#0A0A0A", accent2: "#525252",
display: "Inter, Helvetica Neue, Arial, sans-serif",
body: "Inter, Helvetica Neue, Arial, sans-serif",
radius: "6px standard; sharp 0px for editorial moments",
border: "Grayscale hairlines (#E5E5E5 light, #262626 dark); weight carries hierarchy",
shadow: "Grayscale only: 0 2px 12px rgba(0,0,0,0.08). No colored shadows ever",
spacing: "8px base; sections 80–120px; rely on tonal steps (#FAFAFA → #F5F5F5 → #E5E5E5) for separation",
aesthetic: "One hue, infinite control. Monochrome interfaces prove that value contrast alone can build complete products: black type, gray meta, white surfaces, inverted black sections for drama. Photography becomes the color. It reads premium, timeless, and ruthlessly coherent.",
principles: ["Value contrast does all the work — test every screen in grayscale", "Invert deliberately: black sections punctuate long white pages", "Photography and imagery carry all chromatic energy"],
layout: "Strong tonal rhythm: alternate white, #F5F5F5, and #0A0A0A bands. Oversized black headlines on white; reversed white type on black chapters.",
buttons: "Black fill / white text primary; 1px black outline secondary. On black sections, invert to white fill. Hover grays to #333 (or #E5E5E5 inverted).",
cards: "White on gray-ground, or gray-tinted panels on white, hairline borders. Black feature cards with white type for emphasis moments.",
nav: "Transparent-over-hero turning white with hairline on scroll; or permanent black bar with white mono links. Always high contrast.",
imagery: "Black-and-white photography preferred; color images acceptable if the UI ignores their hues. Full-bleed image chapters work beautifully.",
icons: "Pure black or white line icons, uniform 1.75px stroke. No fills, no color, no exceptions.",
texture: "Fine film grain (3–6%) or halftone dots in gray; paper whites. Texture stays achromatic.",
motion: "Crisp 150–250ms ease-out; hard wipes and clip reveals suit the palette. Avoid soft pastel-feeling springs.",
avoid: ["Any chromatic color in UI chrome — includingFocus rings (use black/white)", "Colored status hues; use icons + labels (OK / WARN / ERR in mono)", "Gray text below 4.5:1 contrast on its ground", "Gradient meshes or duotone photo treatments", "Low-contrast light-gray-on-white body copy"],
},
{
slug: "editorial-minimalism",
name: "Editorial Minimalism",
description: "Quiet magazine restraint: serif headlines, rules, and footnotes over empty space.",
category: "Minimal",
tags: ["minimal", "editorial", "serif"],
bg: "#FBFAF7", surface: "#FFFFFF", ink: "#1C1B1A", muted: "#7A7671", accent: "#8C2F1B", accent2: "#1C1B1A",
display: "Georgia, Playfair Display, Times New Roman, serif",
body: "Georgia, Source Serif 4, Times New Roman, serif",
radius: "0–2px; sharp like print",
border: "Typographic rules: 1px ink lines above/below headers, double rules for mastheads, hairline column dividers",
shadow: "None — print has no shadows",
spacing: "Baseline grid 24–28px; measure 60–68ch; kickers tracked +0.18em; drop caps optional on features",
aesthetic: "A literary journal rendered as a website: serif display type, kickers, bylines, pull quotes, and footnote-style meta. Color appears once — an oxblood or ink-blue accent for links and rules. Authority comes from typography and editing, not interface.",
principles: ["Typography is the interface — invest in scale, measure, and rhythm", "Print devices translate: kickers, rules, bylines, folios, pull quotes", "One accent color, used like an editor's red pen"],
layout: "Article column (680px) with marginalia rail; section openers with kicker + giant serif headline + rule. Generous top matter, quiet footers with colophon.",
buttons: "Understated: small-caps tracked text links in accent, or 1px ink-bordered rectangles. No fills except a black subscribe button.",
cards: "No cards — story rows with thumbnail, kicker, headline, dek, byline, separated by hairlines. Index-like and calm.",
nav: "Masthead: centered or left serif wordmark, date/edition line, thin double rule, small-caps section links. Unchanged across pages.",
imagery: "Duotone or muted editorial photography with captions and credits. Figures numbered (Fig. 1); captions in 12.5px italic gray.",
icons: "Almost none; use typographic ornaments (❦, §, →) and small-caps labels instead.",
texture: " Warm paper flat (#FBFAF7); faint deckle or letterpress impression on the masthead only.",
motion: "Page-like: 200ms fades, footnote-style smooth scrolling to anchors. No parallax theatrics.",
avoid: ["Sans-serif headlines or techy UI chrome", "Cards, pills, shadows, or rounded media", "Bright multi-color accents", "Infinite-scroll density — paginate like issues", "Clickbait patterns: badges, counts, sticky video"],
},
{
slug: "luxury-minimalism",
name: "Luxury Minimalism",
description: "Whispered opulence: vast space, hairline gold, serif display and museum pacing.",
category: "Minimal",
tags: ["minimal", "luxury", "refined"],
bg: "#0E0D0B", surface: "#161411", ink: "#EDE6D6", muted: "#8E8574", accent: "#C6A15B", accent2: "#EDE6D6",
display: "Didot, Bodoni Moda, Cormorant Garamond, serif",
body: "Cormorant Garamond, EB Garamond, Georgia, serif",
radius: "0px — luxury is sharp and certain",
border: "Hairline gold (#C6A15B at 40%) rules and frames; double rules on invitations and certificates",
shadow: "None; depth suggested by layering black-on-black tones and gold light lines",
spacing: "Ceremonial: sections 160–220px; letterspacing +0.2em on eyebrow labels; single centered column, 720px measure",
aesthetic: "Dark, slow, and certain. Ivory serif type on near-black, hairline gold rules, and enormous pauses between statements. Every screen feels like a gallery wall with one object on it. Scarcity — of color, of words, of elements — is the luxury signal.",
principles: ["One object per view — isolate, then illuminate", "Gold is light, not paint: thin lines, never fills", "Slow everything: motion, scroll pacing, and copy cadence"],
layout: "Centered ceremonial axis; full-viewport chapters with a single headline, rule, and action. Alternating black depths (#0E0D0B / #161411) mark movements.",
buttons: "Ghost buttons: 1px gold border, tracked uppercase 12px gold labels, transparent fill. Hover fills gold with black text over 400ms. One per view.",
cards: "No cards. Framed panels with double gold hairlines for collections; wide internal margins (48–64px).",
nav: "Minimal centered monogram, hairline top/bottom rules, tiny tracked links. Fades to a thin gold line on scroll.",
imagery: "Cinematic low-key photography: marble, silk, watch movements, architecture at night. Deep blacks, warm highlights, slow Ken Burns drift.",
icons: "Hairline gold line icons, 1px stroke, sparse. Monograms and Roman numerals preferred over pictograms.",
texture: "Black silk gradients (barely-there radial light), faint marble veining at 4%, fine grain for cinema feel.",
motion: "Slow ceremonial: 600–900ms ease-out reveals, letter-spaced fade-ups, gentle 20s Ken Burns. Reduced-motion yields still frames.",
avoid: ["Bright or multiple accent colors", "Rounded corners, shadows, or elevation", "Dense grids or comparison tables", "Exclamation marks and urgency copy", "Fast snappy transitions or playful easing"],
},
{
slug: "product-minimalism",
name: "Product Minimalism",
description: "Linear-grade restraint: quiet chrome, one blue accent and keyboard-first density.",
category: "Minimal",
tags: ["minimal", "saas", "product"],
bg: "#F7F8FA", surface: "#FFFFFF", ink: "#23272F", muted: "#6B7280", accent: "#4D7CFE", accent2: "#7C5CFF",
display: "Inter, SF Pro Text, Helvetica Neue, sans-serif",
body: "Inter, SF Pro Text, Helvetica Neue, sans-serif",
radius: "8px panels, 6px inputs and buttons",
border: "1px solid #E5E7EB on surfaces; 1px #D1D5DB on inputs; inset dividers #EEF0F3",
shadow: "Subtle product elevation: 0 1px 2px rgba(35,39,47,0.05), popovers 0 8px 24px rgba(35,39,47,0.10)",
spacing: "4px base; dense 12–16px component padding; 24px panel gaps; 13–14px UI text for density",
aesthetic: "The modern developer-tool aesthetic: light gray canvas, white command surfaces, 13px Inter, one confident blue, and hairline structure everywhere. Nothing shouts; everything is findable. Keyboard shortcuts, command palettes, and empty states carry the personality.",
principles: ["Density with clarity: small type, generous alignment, strict hierarchy", "One accent (blue/violet) reserved for actions and focus", "Chrome recedes; content and commands lead"],
layout: "App shell: 240px sidebar + main panel + optional inspector; marketing pages use 1200px center column with product screenshot bands.",
buttons: "36px blue primary (6px radius, 14px medium); ghost and outline secondaries; full keyboard focus rings (2px blue offset). Sizes xs/sm/md for density.",
cards: "White panels with 1px borders and 8px radius; 16–20px padding; header row with title + actions; hover border-darken only.",
nav: "Sidebar with workspace switcher, ⌘K hint, sectioned 13px items with icons and counts; top bar with breadcrumbs + search + avatar.",
imagery: "Product screenshots in browser frames with soft shadows; abstract pastel gradient covers for social/empty states; avatar stacks.",
icons: "16px 1.75px-stroke set (Lucide-style), gray-500 default, blue-600 active. Kbd chips in mono for shortcuts.",
texture: "Near-flat; faint dot grid or gradient mesh only in marketing heroes at low opacity.",
motion: "Fast and functional: 100–150ms ease-out; command menu scales 0.98→1; skeleton shimmer on loads; no decorative animation.",
avoid: ["Marketing gradients inside the product UI", "More than two accent hues", "Large display type in app chrome", "Heavy shadows or 3D decoration", "Hiding keyboard shortcuts — surface them"],
},
{
slug: "functional-minimalism",
name: "Functional Minimalism",
description: "Utilitarian clarity: system type, visible structure and zero ornament for tools.",
category: "Minimal",
tags: ["minimal", "utility", "accessible"],
bg: "#FFFFFF", surface: "#F4F4F5", ink: "#18181B", muted: "#71717A", accent: "#2563EB", accent2: "#059669",
display: "system-ui, -apple-system, Segoe UI, sans-serif",
body: "system-ui, -apple-system, Segoe UI, sans-serif",
radius: "6px controls, 8px panels — system defaults, never custom",
border: "System hairlines (#E4E4E7); form fields always visibly bordered; tables fully gridded",
shadow: "None on content; dialogs get standard system elevation only",
spacing: "4px base; compact 8–16px rhythm; information density prioritized over airiness",
aesthetic: "The aesthetic of infrastructure: system fonts, visible tables, explicit labels, and affordances that look clickable. Beauty comes from correctness — aligned columns, honest states, readable errors. Built for operators, admins, and anyone doing real work.",
principles: ["Affordances must look clickable: borders, underlines, hover states always", "Data first: tables, logs, and forms are the design", "System conventions over brand expression"],
layout: "Dense workbench: toolbar + filter row + data table + status bar. Labels above inputs; units and validation inline; 1280px+ fluid width.",
buttons: "Native-looking controls: bordered 32–36px buttons, blue primary, destructive red reserved for danger. Disabled states always visible, never hidden actions.",
cards: "Panels are flat gray wells with headers, not floating cards. Fieldsets and legends group forms; tables use zebra rows sparingly.",
nav: "Utility nav: breadcrumbs, tabs with counts, and a persistent status/footer bar. Sidebar is a plain labeled list with section headers.",
imagery: "None decorative. Diagrams, charts, and document thumbnails only; screenshots shown at real size with borders.",
icons: "System/SF-style glyphs, 16px, monochrome. Every icon button has a visible text label or tooltip.",
texture: "None. Flat system grays; focus on contrast and legibility.",
motion: "Minimal: 100ms state fades; respect reduced motion fully; loading spinners are system-standard.",
avoid: ["Custom fonts or brand flourishes in tool UI", "Ghost buttons with no visible boundary", "Icon-only critical actions", "Marketing heroes inside admin tools", "Trendy dark-only themes that hurt daytime ops work"],
},
{
slug: "brutalism",
name: "Brutalism",
description: "Raw concrete honesty: system type, exposed structure and zero decoration.",
category: "Brutalist",
tags: ["raw", "structural", "honest"],
bg: "#D6D3CD", surface: "#E8E6E1", ink: "#1A1A1A", muted: "#5C5A55", accent: "#1A1A1A", accent2: "#B30000",
display: "Times New Roman, Times, serif",
body: "Arial, Helvetica, sans-serif",
radius: "0px — concrete does not round",
border: "Heavy raw dividers: 2–4px solid ink; exposed table grids; unstyled form boxes",
shadow: "None. Mass and weight come from solid blocks, not elevation",
spacing: "Tight and structural: 16px base rhythm; full-bleed bands; content slammed to edges with 16–24px margins",
aesthetic: "Web brutalism as béton brut: default system fonts, raw gray grounds, visible tables and borders, blue links, and layouts that refuse to flatter. Links are blue and underlined. Buttons are gray and beveled by the browser. Honesty is the whole program — the page shows its skeleton proudly.",
principles: ["Expose the structure: grids, tables, and rules stay visible", "Default browser aesthetics are a feature, not a failure", "Content over chrome — styling budgets go to legibility"],
layout: "Full-bleed stacked bands with hard edges; left-aligned everything; max-widths are generous (1400px+) or absent. Sidebars are plain bordered columns.",
buttons: "Native gray beveled buttons or flat black rectangles with white Arial labels. Hover: invert or underline. No transitions longer than 100ms.",
cards: "No cards — bordered sections and definition rows. If containment is needed, a 2px solid box with square corners.",
nav: "A bordered bar with wordmark left and blue underlined links. Breadcrumbs as raw paths (Home / Section / Page). No sticky blur, no pills.",
imagery: "Unretouched, often low-res, shown at native aspect with hard borders. Alt text treated as first-class content.",
icons: "None, or raw Unicode glyphs (▪ ► ●). No icon sets, no SVGs with brand polish.",
texture: "Raw concrete gray flats; optional visible scanline or noise at low opacity for age. Never gradients.",
motion: "Effectively static. Instant hover states; marquee and blink are period-accurate if used sparingly.",
avoid: ["Rounded corners, shadows, or gradients of any kind", "Custom webfonts for body text", "Hero sections with centered marketing copy", "Smooth-scroll theatrics or parallax", "Hiding the URL structure — show paths and indexes"],
},
{
slug: "neo-brutalism",
name: "Neo-Brutalism",
description: "Bold borders, hard shadows, saturated colors and deliberately raw interfaces.",
category: "Brutalist",
tags: ["bold", "high-contrast", "playful"],
bg: "#FFF6E5", surface: "#FFFFFF", ink: "#111111", muted: "#6B6257", accent: "#FF5C00", accent2: "#2B4EFF",
display: "Archivo Black, Arial Black, sans-serif",
body: "Inter, Helvetica Neue, Arial, sans-serif",
radius: "0–6px; cards often sharp, stickers and tags fully pill",
border: "2–3px solid #111111 on every card, button, input, and tag — borders are the design",
shadow: "Hard offset shadows: 4px 4px 0 #111111 (cards), 6px 6px 0 on heroes; zero blur, always",
spacing: "8px base; chunky 20–28px card padding; sections 72–104px; sticker labels with 8–12px padding",
aesthetic: "Neo-brutalism is brutalism with a spray can: the raw structure stays, but surfaces explode with saturated color — orange, blue, lime, pink — inside thick black frames. Sticker-like badges, rotated labels, starbursts, and hard shadows make every element feel printed, cut out, and slapped on. Loud, confident, and engineered to be memorable.",
principles: ["Everything gets a border and a hard shadow — no floating elements", "Saturated color fields clash on purpose; black holds them together", "Type is big, black, and uppercase; hierarchy through scale and weight"],
layout: "Blocky asymmetric grid with overlapping stickers and starbursts; alternating saturated section grounds (cream → yellow → blue). Marquee tickers divide chapters. Max-width 1200px with full-bleed color bands.",
buttons: "3px-bordered rectangles with hard 4px shadows and uppercase bold labels; primary in accent, secondary white. Hover translates (-2px,-2px) and grows shadow to 6px; active presses flat (0 shadow).",
cards: "White or pastel cards, 3px black border, 4–6px hard shadow, sharp or slightly rounded corners. Header strip in accent with black title; footer row with sticker tags.",
nav: "Cream bar with 3px black bottom border; logo in a black box; links uppercase bold with highlighter hover; CTA is an accent button with hard shadow.",
imagery: "Bold flat illustration, halftone textures, cut-out stickers, thick-outlined doodles. Photos get 3px borders + hard shadows and slight rotation.",
icons: "Thick 2.5px-stroke icons in black circles/squares, or filled sticker icons with white borders. Chunky and few.",
texture: "Halftone dots, diagonal stripes, checkerboards, and grain at 8–15% — print-shop energy on section grounds.",
motion: "Snappy 150ms steps; hover lifts with shadow growth; marquee tickers scroll; sticker wiggles on hover. No soft fades — moves are mechanical and proud.",
avoid: ["Blurred soft shadows or glassmorphism", "Thin 1px borders or hairline anything", "Muted corporate palettes", "Rounded-3xl blob shapes", "Timid small type — go big or go home"],
},
{
slug: "playful-brutalism",
name: "Playful Brutalism",
description: "Chunky friendly shapes, candy colors and wobbling stickers with structural bite.",
category: "Brutalist",
tags: ["playful", "bold", "friendly"],
bg: "#FFF9F0", surface: "#FFFFFF", ink: "#222222", muted: "#7A736A", accent: "#FF4FA3", accent2: "#00B3FF",
display: "Baloo 2, Fredoka, Arial Rounded MT Bold, sans-serif",
body: "Nunito, Quicksand, Helvetica Neue, sans-serif",
radius: "14–20px squishy rounding on cards; pills for stickers",
border: "2.5–3px solid #222222 outlines around everything cute — plush with a frame",
shadow: "Hard but sweet: 5px 5px 0 #222222; hover squishes to 2px with a boing",
spacing: "Bouncy rhythm: 24px card padding, 64–88px sections, stickers overlapping edges by 8–16px",
aesthetic: "A toy box with rules: rounded candy forms outlined in thick ink, pastel-meets-neon color, googly stickers, squiggles, and starbursts. Underneath the cuteness the grid is strict — every wobble is aligned. Appeals to Gen-Z brands, kids' products, and anyone allergic to corporate gray.",
principles: ["Cute but constructed: wobbles align to the grid", "Candy color with ink outlines — sweetness needs structure", "Motion is physical: squish, wobble, boing"],
layout: "Centered bouncy stacks with scattered sticker constellations; wavy and zigzag section dividers; alternating pastel grounds. Max-width 1120px, lots of overlap.",
buttons: "Pill buttons, 3px ink border, candy fill, bold rounded labels; hard 4px shadow. Hover wobbles (rotate ±2deg); press squishes flat with a 150ms spring.",
cards: "Squishy rounded cards with ink borders and hard shadows; icon medallions, squiggle underlines, and sticker badges breaking the frame.",
nav: "Cream bar, 3px bottom border, rounded logo sticker, pill links with candy hover fills; CTA is a pink pill with shadow.",
imagery: "Flat vector mascots, blob shapes, candy patterns, thick-outlined doodles. Photos masked in arches and blobs with ink borders.",
icons: "Rounded filled icons with 2px ink outlines; emoji-scale expressiveness; consistent chunky set.",
texture: "Confetti dots, squiggles, checkerboard trims, scalloped edges, subtle paper grain under candy fills.",
motion: "Springy: 200–350ms cubic-bezier(0.34,1.56,0.64,1) pops; sticker wiggle on hover; floating idle bob on mascots. Joyful but snappy.",
avoid: ["Thin lines or hairline anything", "Muted desaturated palettes", "Sharp corporate rectangles", "Slow fades and gentle ease-outs", "Cynical or cold copy tone"],
},
{
slug: "corporate-brutalism",
name: "Corporate Brutalism",
description: "Boardroom concrete: heavy rules, tabular data and imposing institutional grids.",
category: "Brutalist",
tags: ["institutional", "grid", "authoritative"],
bg: "#EFEFEA", surface: "#FFFFFF", ink: "#141414", muted: "#62625C", accent: "#0033AA", accent2: "#141414",
display: "Helvetica Neue, Arial, sans-serif",
body: "Helvetica Neue, Arial, sans-serif",
radius: "0px — institutions do not round corners",
border: "2px solid #141414 structural rules; data tables fully gridded with 1px lines",
shadow: "None. Authority comes from mass and order, not lift",
spacing: "Rigid 8px system; dense data zones (12–16px), formal 64–96px section breaks; tabular numerals everywhere",
aesthetic: "The annual-report wing of brutalism: imposing black rules, dense tables, small-caps labels, institutional blue links, and layouts that feel audited. Everything aligns; nothing decorates. Trust is built through visible order — the design equivalent of a headquarters facade.",
principles: ["Order signals trust: align everything, grid everything", "Data density is a virtue — tables over cards", "One institutional blue; everything else is ink and paper"],
layout: "Strict multi-column institutional grid; header band with rule stack; content in bordered ledger panels; footers with dense fine print. Max-width 1280px.",
buttons: "Square authoritative buttons: black primary, blue links, red only for destructive ledger actions. Labels uppercase 12px tracked. Instant hover states.",
cards: "Ledger panels: white, 2px black header rule, gridded rows, tabular figures, status stamps. No elevation, no radius.",
nav: "Heavy institutional masthead: wordmark, division links, search, and a black rule sandwich (thick-thin-thick). Section tabs with counts.",
imagery: "Architecture, infrastructure, team grid portraits in grayscale; charts are the primary visual. Photos framed with 2px rules and captions.",
icons: "Minimal geometric marks; 1.5px strokes; data glyphs (arrows, carets) over pictograms. Numbers preferred.",
texture: "Flat ledger paper; faint blueprint grid in data zones at 5%; security-pattern microprint in footers for flavor.",
motion: "None beyond instant state changes and row highlights. Motion would undermine the gravity.",
avoid: ["Playful color, illustration, or rounded anything", "Marketing heroes and lifestyle photography", "Animations, parallax, or scroll theatrics", "Hiding numbers behind vague copy", "Trendy typefaces — Helvetica or equivalent only"],
},
{
slug: "editorial-brutalism",
name: "Editorial Brutalism",
description: "Poster-scale headlines, raw rules and ink-heavy layouts with newsroom urgency.",
category: "Brutalist",
tags: ["editorial", "bold", "poster"],
bg: "#F2EFE9", surface: "#FFFFFF", ink: "#111111", muted: "#6F6A60", accent: "#D92300", accent2: "#111111",
display: "Arial Black, Archivo Black, Helvetica Neue, sans-serif",
body: "Helvetica Neue, Arial, sans-serif",
radius: "0px sharp; images may bleed full-bleed",
border: "Thick black rules (3–6px) between stories; red kickers; bordered pull-quote blocks",
shadow: "None — ink on paper, no elevation",
spacing: "Newsroom density: tight 16–24px story rhythm, giant 80–160px display headlines, full-bleed image breaks",
aesthetic: "A protest poster crossed with a front page: enormous condensed headlines, red urgency accents, black rules everywhere, and layouts that shout. Stories stack like bills on a wall. Made for publications, campaigns, and launches that need to feel like news, not content.",
principles: ["Headlines are the design — set them enormous and tight", "Red means now: reserve the accent for urgency", "Stack, don't nest — flat sequences of strong blocks"],
layout: "Front-page stack: masthead, giant headline, full-bleed image, rule, story grid, ticker. Multi-column story wells with drop caps. Max-width 1400px, edges bleed.",
buttons: "Black bars with white uppercase condensed labels, full-bleed on mobile. Hover floods red. No radius, no shadow, all caps.",
cards: "Story blocks: kicker, huge headline, dek, byline, rule — no containing card. Image-led features bleed edge to edge.",
nav: "Masthead bar: date/edition mono, giant wordmark, section links in condensed caps; breaking-news ticker below in red-on-black.",
imagery: "High-contrast reportage photography, full-bleed, hard crops, red duotone options. Captions small with credit lines.",
icons: "None decorative — use typographic devices: ★, →, №, rules, and boxed section numbers.",
texture: "Newsprint grain and halftone at 6–10%; misregistration offsets (red/black split) on display type for print fury.",
motion: "Typewriter tickers, clip-path headline reveals, hard cuts. 200ms steps; urgency over smoothness.",
avoid: ["Soft shadows, rounded cards, or pastel palettes", "Polite 48px headlines — double them", "Generic stock photography", "Centered delicate layouts", "More than one red and one black"],
},
{
slug: "minimal-brutalism",
name: "Minimal Brutalism",
description: "One black frame, one idea: gallery-spare layouts with brutalist conviction.",
category: "Brutalist",
tags: ["minimal", "structural", "gallery"],
bg: "#FAFAF8", surface: "#FFFFFF", ink: "#101010", muted: "#7C7C78", accent: "#101010", accent2: "#4D4DFF",
display: "Helvetica Neue, Inter, Arial, sans-serif",
body: "Helvetica Neue, Inter, Arial, sans-serif",
radius: "0px throughout",
border: "A single confident weight: 2px solid ink for frames and dividers, hairlines nowhere",
shadow: "None at all — presence comes from scale and isolation",
spacing: "Gallery rhythm: one work per viewport, 120px+ pauses, 24px frame insets, tiny mono captions",
aesthetic: "A white cube with a backbone: vast empty rooms, single black-framed statements, enormous quiet type. Where neo-brutalism shouts in color, minimal brutalism whispers in structure — one rule, one idea, total conviction. Built for portfolios, architects, and galleries.",
principles: ["One idea per viewport, framed in black", "Two weights of one grotesk do all typographic work", "Isolation creates value — space is the pedestal"],
layout: "Single-column exhibition sequence; each section a framed room (2px border, 24px inset). Index page as numbered list with hairline... no — 2px rules. Max-width 1000px.",
buttons: "Text-scale actions: 2px-bordered rectangles, uppercase 12px tracked labels, generous padding. Hover fills black with white text instantly.",
cards: "Framed plates: 2px border, image or statement inside, mono caption below the frame. No shadows, no fills.",
nav: "Hairline... 2px top and bottom rules, wordmark left, index right in mono. Fixed, white, severe.",
imagery: "One image at a time, large, bordered, captioned like an exhibit plate. Grayscale or muted; no collages.",
icons: "Effectively none — numerals and arrows (→) in mono serve as wayfinding.",
texture: "Flat gallery white; faint concrete or paper grain at 3% maximum.",
motion: "Stillness with intent: instant hovers, slow 500ms fade-ins on scroll, image scales 1.0→1.03 over seconds.",
avoid: ["Color fills or accent hues beyond one blue", "Multiple ideas competing in one viewport", "Shadows, radius, or decoration", "Small timid type", "Carousels — sequence vertically instead"],
},
{
slug: "colorful-brutalism",
name: "Colorful Brutalism",
description: "Rainbow concrete: clashing primaries inside heavy black structure.",
category: "Brutalist",
tags: ["colorful", "bold", "high-energy"],
bg: "#7C5CFF", surface: "#FFFFFF", ink: "#111111", muted: "#55504A", accent: "#FFD802", accent2: "#FF4FA3",
display: "Archivo Black, Arial Black, sans-serif",
body: "Inter, Helvetica Neue, Arial, sans-serif",
radius: "10–16px chunky rounding colliding with sharp black frames",
border: "3px solid #111111 everywhere; sections divided by black bands, not whitespace",
shadow: "Hard 6px 6px 0 #111111; stacked double shadows (white + black) on heroes",
spacing: "Dense festival rhythm: 20px card padding, 56–80px color-block sections, rotated stickers overlapping",
aesthetic: "Every section a different saturated ground — violet, yellow, pink, cyan — stitched with black bands and white sticker cards. Maximal color, brutalist bones. It feels like a music festival poster that became a website: joyful, loud, and impossible to ignore.",
principles: ["Change the ground color every section — rhythm through hue", "Black bands and borders stitch clashing colors together", "White sticker cards float the content above the noise"],
layout: "Full-bleed color chapters separated by 4px black bands; white bordered cards carry text; marquee tickers and starbursts punctuate. Max-width 1200px inside bands.",
buttons: "Black or white 3px-bordered buttons with hard shadows on color grounds; labels uppercase black or white. Hover swaps fill color with a 150ms pop.",
cards: "White sticker cards with 3px borders and 6px hard shadows on saturated grounds; colored header strips; rotating badge stickers.",
nav: "Black bar with white links and a yellow CTA with black text; or cream bar with 3px bottom border. Always high-contrast against the hero ground.",
imagery: "Cut-out stickers, flat vector scenes, halftone portraits in clashing duotones. Photos bordered thick and tilted ±2deg.",
icons: "Sticker icons: filled candy shapes with 2.5px black outlines and white inner detail.",
texture: "Checkerboards, stripes, polka dots, and halftones in black/white over color grounds at 10–20%.",
motion: "Festival energy: marquees, spinning starbursts (slow 12s), hover pops with 150ms springs. Color-block wipe transitions between sections.",
avoid: ["White or gray section grounds — commit to color", "Thin borders or soft shadows", "Muted or pastel-only palettes", "Long gray paragraphs on color (use white cards)", "Timid single-accent restraint"],
},
{
slug: "anti-design",
name: "Anti-Design",
description: "Deliberate wrongness: clashing type, broken grids and hostile charm.",
category: "Brutalist",
tags: ["experimental", "raw", "provocative"],
bg: "#E8E8E8", surface: "#F2F2F2", ink: "#000000", muted: "#555555", accent: "#0000EE", accent2: "#FF0000",
display: "Times New Roman, serif",
body: "Arial, Helvetica, sans-serif",
radius: "0px — decoration is the enemy, even pretty corners",
border: "Inconsistent on purpose: some beveled, some doubled, some missing; default fieldset looks welcome",
shadow: "Browser-default or none; deliberate flatness except accidental bevels",
spacing: "Broken rhythm: random-feeling margins, overlapping blocks, text running edge to edge then suddenly indented",
aesthetic: "Anti-design weaponizes ugliness: Times body copy, misaligned blocks, clashing link blue on gray, autoplay-era chaos — deployed with total control. It signals insider credibility to designers and developers by refusing every trend. The wrongness must look intentional, never accidental.",
principles: ["Break rules visibly and confidently — timid weirdness reads as a bug", "Default browser styling is a legitimate material", "Friction is branding: make visitors feel something"],
layout: "Colliding columns, overlapping absolutely-positioned blocks, horizontal scroll traps, footers in the middle. Tables for layout are period-correct.",
buttons: "Default gray beveled buttons, or blue underlined text links. Hover states may do nothing — or something alarming.",
cards: "Fieldsets with legends, beveled wells, bordered divs with clashing background tints. No system, on purpose.",
nav: "A list of blue underlined links, possibly with visited purple, possibly in a sidebar table cell. Hit counters welcome.",
imagery: "Low-res GIFs, clip art, dithered photos, broken-image icons as decor. Compression artifacts are patina.",
icons: "Unicode and emoji as icons (☞ ✖ ☠). No crafted icon set — that would be selling out.",
texture: "Tiled starfield backgrounds, gray bevel gradients, visible dither. Nostalgia through hostility.",
motion: "Marquees, blinking text, cursor trails, alert() energy — but keep it performant and escapable. Parody, not malware.",
avoid: ["Looking accidentally broken — commit fully or not at all", "Whitespace, alignment, or visual hierarchy (the forbidden trio)", "Modern SaaS patterns sneaking in", "Accessibility as an afterthought — even hostile design needs alt text and keyboard paths", "Hurting readability so much the message dies"],
},
{
slug: "post-brutalism",
name: "Post-Brutalism",
description: "Brutalism grown up: raw grids softened with refined type and restrained color.",
category: "Brutalist",
tags: ["refined", "structural", "editorial"],
bg: "#F5F3EF", surface: "#FFFFFF", ink: "#1B1B1B", muted: "#75716A", accent: "#2B4EFF", accent2: "#FF5C00",
display: "Neue Haas Grotesk, Inter Tight, Helvetica Neue, sans-serif",
body: "Inter, Helvetica Neue, Arial, sans-serif",
radius: "4px functional rounding; sharp for editorial moments",
border: "1.5–2px ink structure lines; confident but not chunky",
shadow: "Small hard offsets (3px 3px 0 ink) used sparingly on key actions only",
spacing: "Disciplined 8px system; 80–110px sections; data-dense zones allowed inside strict frames",
aesthetic: "What brutalism becomes after design school: the grid and honesty remain, but typography is refined, color is rationed (one electric blue), and whitespace is back on the team. Raw enough for credibility, polished enough for clients. The agency-portfolio sweet spot.",
principles: ["Keep the skeleton, tailor the suit — structure raw, details refined", "One electric accent against disciplined neutrals", "Typography carries the attitude, not decoration"],
layout: "Strong grid with confident asymmetry; bordered work-index rows; case studies alternate raw-specimen and polished-outcome views. Max-width 1280px.",
buttons: "2px-bordered rectangles with 3px hard shadows in blue or black; labels medium 14px. Hover lifts 2px. Restrained but physical.",
cards: "Bordered index rows and 2px frames with generous padding; mono meta labels; hover reveals accent edge or image.",
nav: "Ruled bar with wordmark, index links, and availability badge; mono section numbers; blue underline hovers.",
imagery: "Mix of raw process shots and polished finals; duotone treatments unify; images framed with 2px borders and mono captions.",
icons: "Precise 1.75px geometric icons; arrows and numerals do heavy lifting; blue used sparingly.",
texture: "Faint grid paper and spec ticks in margins; 4% grain. Studio-draft energy, controlled.",
motion: "Confident 180–250ms ease-outs; image reveals with clip wipes; hover states physical but quick.",
avoid: ["Full chaos color or sticker overload (that's neo-brutalism)", "Hairline-only timidity — commit to visible structure", "Generic SaaS softness", "More than one saturated accent", "Centering everything — asymmetry is the heritage"],
},
{
slug: "industrial-brutalism",
name: "Industrial Brutalism",
description: "Factory-floor functionalism: safety yellow, stencil type and hazard-striped order.",
category: "Brutalist",
tags: ["industrial", "utilitarian", "stencil"],
bg: "#2B2B2B", surface: "#3A3A3A", ink: "#F2F0EA", muted: "#A8A49A", accent: "#FFD802", accent2: "#FF5A1F",
display: "Anton, Oswald, Arial Narrow, sans-serif",
body: "Inter, Helvetica Neue, Arial, sans-serif",
radius: "0px — machined edges only",
border: "2–3px solid in light-on-dark; hazard stripes (yellow/black 45°) as dividers and warnings",
shadow: "None; mass conveyed through dark tonal stacking (#222 → #333 → #444)",
spacing: "Tight workmanlike: 16–24px panel padding, 48–72px sections, spec-plate labels on everything",
aesthetic: "A control room crossed with a shipping crate: dark steel grounds, safety-yellow accents, condensed stencil headlines, riveted panels, and spec plates on every module. Built for hardware, logistics, devtools, and energy brands that want to feel heavy and reliable.",
principles: ["Dark steel grounds; yellow means action or warning, nothing else", "Label everything like equipment: plates, serials, ratings", "Condensed uppercase type shouts efficiently"],
layout: "Modular equipment racks: bordered dark panels in strict rows, status LEDs, spec plates; dashboards read like control consoles. Max-width 1440px fluid.",
buttons: "Yellow plates with black stencil labels and 2px light borders; secondary dark metal with yellow edge. Press states clunk (translate 2px, 100ms).",
cards: "Steel panels: #3A3A3A fill, 2px #555 border, rivet dots in corners, spec-plate header with mono serial. Status LED dot.",
nav: "Dark gantry bar with yellow wordmark plate, stencil links, and a live status readout in mono (SYS ● NOMINAL).",
imagery: "Machinery, warehouses, night infrastructure, macro metal. High contrast, warm sodium highlights, slight desaturation.",
icons: "Stencil-cut pictograms, 2px strokes, yellow or bone on dark. Warning triangles and ISO-style glyphs welcome.",
texture: "Brushed metal gradients (subtle vertical), diamond plate at low opacity, rivets, hazard stripes, stencil overspray.",
motion: "Mechanical: 100–150ms linear clunks, LED blinks, gauge sweeps. Servo sounds are a joke — do not add audio.",
avoid: ["Light airy layouts or pastel color", "Rounded friendly anything", "Thin delicate typography", "Decorative animation or bounce easing", "Using yellow for passive decoration — it must mean something"],
},
];
