export const stylesF = [
{
slug: "art-deco",
name: "Art Deco",
description: "Geometric luxury ornament: gold fans, sunbursts and Gatsby-era glamour.",
category: "Heritage Luxury",
tags: ["art-deco", "luxury", "geometric"],
bg: "#0E0E12", surface: "#16161C", ink: "#EFE6D0", muted: "#8E8574", accent: "#D4AF37", accent2: "#0E7C7B",
display: "Cinzel, Marcellus, serif",
body: "Jost, Futura, sans-serif",
radius: "Arches, fans, chevrons; 0px on framed certificates",
border: "Deco frames: double gold rules, fan/sunburst SVG corners, chevron dividers, stepped borders",
shadow: "Ballroom glow: 0 20px 60px black/60, gold inner light on frames",
spacing: "Ceremonial geometry: centered symmetric axis, 120–160px movements, 32px framed padding",
aesthetic: "1925 Paris in pixels: black lacquer, gold fan ornament, stepped ziggurat layouts, teal accents, dynastic symmetry. Glamour through geometry. For hotels, cocktails, jazz, weddings, and luxury.",
principles: ["Symmetry is sacred — center everything ceremonially", "Gold ornament + black lacquer + one jewel accent", "Fans, sunbursts, chevrons: the motif trio"],
layout: "Ballroom axis: fan-crested hero, stepped gallery tiers, certificate chapters, marquee footer. Max-width 1200px centered.",
buttons: "Gold cartouches with tracked caps; hover fills gold/black-text. Champagne CTA for bookings.",
cards: "Deco plaques: black lacquer, gold fan corners, cameo imagery, stepped edges.",
nav: "Marquee bar: centered monogram in fan crest, tracked links, gold rules above/below.",
imagery: "Jazz-age photography, champagne macro, skyline geometry, feather/silk textures. Gold-graded.",
icons: "Fans, sunbursts, chevrons, cocktail glyphs — gold thin-line Deco set.",
texture: "Gold leaf, lacquer, velvet, marble at 8–12%; fan-pattern wallpapers subtle.",
motion: "Ballroom slow: 600ms fan-opens, shimmer sweeps, curtain reveals. Charleston restraint.",
avoid: ["Asymmetry (heresy here)", "Sans-serif display type", "Bright modern color", "Rounded SaaS geometry", "Fast playful motion"],
},
{
slug: "art-nouveau",
name: "Art Nouveau",
description: "Flowing botanical ornament: whiplash curves, stained glass and Mucha grace.",
category: "Heritage Luxury",
tags: ["art-nouveau", "botanical", "ornamental"],
bg: "#F5EFE2", surface: "#FFFDF6", ink: "#3B3128", muted: "#756B5F", accent: "#687144", accent2: "#B3541E",
display: "Cormorant Garamond, Playfair Display, serif",
body: "EB Garamond, Georgia, serif",
radius: "Whiplash arches and oval cameos; vine-framed panels",
border: "Botanical frames: vine SVG borders, stained-glass leading lines, arch windows",
shadow: "Glasshouse soft: 0 12px 32px warm/12; stained-glass glow accents",
spacing: "Flowing: arched compositions, 110–140px garden movements, 32px framed padding",
aesthetic: "Mucha posters and Métro entrances: whiplash vines, haloed maidens (illustrated, tasteful), stained-glass color, arch windows. Romantic organic ornament. For perfume, wine, hospitality, and craft.",
principles: ["Curves, never corners — whiplash lines lead the eye", "Stained-glass palette: olive, amber, teal, rust on cream", "Arches frame everything precious"],
layout: "Garden gallery: arched hero cameo, vine-chapter rows, stained-glass interludes, ornate footer. Max-width 1200px.",
buttons: "Cameo buttons: arched/oval, olive fills, cream serif labels; hover glows amber.",
cards: "Arch-window panels: vine frames, cameo imagery, ornamental captions.",
nav: "Arched bar: vine monogram, serif links, amber CTA. Ornamental rules.",
imagery: "Botanical illustration, stained glass, portrait cameos, vineyard light. Romantic grade.",
icons: "Vines, dragonflies, lilies, arches — Nouveau glyph set in olive/amber.",
texture: "Stained glass, vine patterns, paper grain, mosaic at 8–12%.",
motion: "Growing vines (SVG draw on scroll), petal drifts, glow pulses. Languorous 500ms+.",
avoid: ["Sharp geometric modernism", "Neon or synthetic color", "Sans-serif display", "Symmetric Deco rigidity (flow, don't step)", "Fast motion"],
},
{
slug: "mid-century-modern",
name: "Mid-Century Modern",
description: "Eames-era optimism: starbursts, tapered lines and warm atomic geometry.",
category: "Heritage Luxury",
tags: ["mid-century", "atomic", "retro"],
bg: "#F5F1E8", surface: "#FFFFFF", ink: "#2B2B2B", muted: "#716E66", accent: "#C5401A", accent2: "#287696",
display: "Futura, Century Gothic, sans-serif",
body: "Helvetica Neue, Inter, sans-serif",
radius: "Boomerang curves and tapered forms; 8–16px friendly panels",
border: "Atomic keylines: 1–2px warm-gray frames; starburst dividers; tapered rules",
shadow: "Showroom soft: 0 10px 30px warm/10; long soft furniture-catalog shadows",
spacing: "Showroom rhythm: low horizontal bands, 88–110px sections, 28px card padding",
aesthetic: "A 1958 Herman Miller showroom: teak and mustard, starburst clocks (CSS!), tapered legs on everything, barkcloth patterns. Optimistic, warm, well-made. For furniture, interiors, coffee, and lifestyle.",
principles: ["Taper everything: legs, rules, type details", "Mustard + teal + rust on warm cream", "Starbursts and boomerangs: the atomic motif pair"],
layout: "Showroom scroll: hero room-set, collection rows with tapered cards, maker story, catalog footer. Max-width 1280px.",
buttons: "Tapered buttons: rust/teal fills, cream labels, 10px radius. Hover warms + lifts.",
cards: "Catalog cards: product on cream, tapered image masks, spec rows in mono, starburst sale badges.",
nav: "Showroom bar: script+geometric wordmark, collection links, cart. Warm and low.",
imagery: "Styled room-sets, product on seamless, atomic patterns, vintage ads as flavor.",
icons: "Starbursts, boomerangs, tapered arrows — atomic glyph set.",
texture: "Teak grain, barkcloth, tweed, starburst fields at 8–12%.",
motion: "Showroom smooth: 300ms warm fades, starburst slow-spins, drawer-like panel slides.",
avoid: ["Cold grays or neon", "Sharp brutalist geometry", "Dense packed grids", "Sans-mono tech chrome", "Fast bouncy motion"],
},
{
slug: "70s-retro",
name: "70s Retro",
description: "Warm analog groove: burnt orange, harvest gold and curvy mushroom type.",
category: "Decades",
tags: ["70s", "groovy", "warm"],
bg: "#F3E9D2", surface: "#FFF8EA", ink: "#3B2E23", muted: "#746756", accent: "#A4501D", accent2: "#7A8450",
display: "Cooper Black, Shrikhand, serif",
body: "Karla, Inter, sans-serif",
radius: "Mushroom curves: 20px+ blobs, rainbow-arch dividers, flower-power rounds",
border: "Groovy frames: thick rounded outlines in brown/orange; rainbow-stripe dividers",
shadow: "Shag warmth: 0 12px 32px brown/15; sunset-glow accents",
spacing: "Lounge rhythm: groovy 88–110px sections, flower-scattered margins, 28px panel padding",
aesthetic: "A fondue night in pixels: burnt orange + harvest gold + avocado, Cooper Black headlines, rainbow arches, flower power, wood paneling warmth. Cozy and groovy. For food, music, cannabis, and lifestyle nostalgia.",
principles: ["Earth-tone triad: orange + gold + avocado on cream", "Curvy display type (Cooper!) with tight spacing", "Rainbows, mushrooms, flowers: the motif trio"],
layout: "Lounge scroll: rainbow-arch hero, groovy feature rows, flower-break interludes, fondue-pot CTA. Max-width 1200px.",
buttons: "Groovy pills: orange fills, cream Cooper labels; hover melts (scale + warm).",
cards: "Lounge panels: cream, brown frames, flower-corner stickers, sunset header strips.",
nav: "Lounge bar: flower mark, groovy links, orange CTA. Rainbow trim top.",
imagery: "Analog photography: vans, vinyl, fondue, shag. Warm faded grade, grain.",
icons: "Mushrooms, flowers, vans, rainbows — groovy glyph set in earth tones.",
texture: "Shag, wood paneling, flower fields, sunset stripes at 10–15%.",
motion: "Groovy drift: lava-lamp blobs (12s), flower spins (slow), 300ms warm pops.",
avoid: ["Cool blues or neon", "Sharp minimal geometry", "Sans-serif display type", "Fast techy motion", "Cynical copy (good vibes only)"],
},
{
slug: "80s-retro",
name: "80s Retro",
description: "Neon-grid nostalgia: chrome sunsets, outrun lines and VHS warmth.",
category: "Decades",
tags: ["80s", "outrun", "neon"],
bg: "#0D0221", surface: "#1A0B2E", ink: "#F5EDFF", muted: "#9A86C7", accent: "#FF2E88", accent2: "#00E5FF",
display: "Monoton, Orbitron, Impact, sans-serif",
body: "Outfit, Inter, sans-serif",
radius: "Chrome rounds: pills, grid-sun circles, VHS-card 8px",
border: "Neon keylines: 1–2px pink/cyan; grid-floor horizons; scanline overlays",
shadow: "Outrun glow: 0 0 30px pink + 0 0 80px violet; chrome speculars",
spacing: "Arcade pacing: sunset hero, 72–96px neon chapters, 24px panel padding",
aesthetic: "Miami midnight, 1986: chrome script logos, grid-suns setting over wireframe, VHS tracking lines, palm silhouettes. Nostalgia with horsepower. For music, games, drinks, and nightlife.",
principles: ["Sunset palette: pink → violet → deep blue, cyan accents", "Grid floors + chrome suns + VHS lines = instant 80s", "Script display + mono details"],
layout: "Outrun scroll: sunset hero with grid floor, neon chapter bands, arcade-grid features, midnight CTA. Max-width 1280px.",
buttons: "Chrome/neon pills with glow; hover flares. High-score CTA styling for conversion.",
cards: "VHS-case panels: dark, neon keylines, tracking-line headers, sunset thumbs.",
nav: "Midnight bar: chrome script mark, neon links, glowing CTA. Grid trim.",
imagery: "Grid suns, chrome cars, palms, cassettes. Pink-cyan grade, VHS grain.",
icons: "Cassettes, grids, lightning, palms — neon-glow set.",
texture: "Grid floors, VHS noise, scanlines, chrome gradients.",
motion: "Retro-future: grid scroll (slow), neon flicker (gentle), sun-set parallax. VHS tracking warp on transitions (subtle).",
avoid: ["Daylight or earthy palettes", "Minimal restraint", "Sans-only typography", "Static gradients (animate glow)", "Modern flat illustration"],
},
{
slug: "90s-retro",
name: "90s Retro",
description: "Saved-by-the-bell color: squiggles, shapes and bold geometric fun.",
category: "Decades",
tags: ["90s", "geometric", "bold"],
bg: "#FFF6E5", surface: "#FFFFFF", ink: "#222222", muted: "#767067", accent: "#704DFF", accent2: "#007B7B",
display: "Archivo Black, Shrikhand, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "Bold geo: triangles, zigzags, circles; 12–20px cards",
border: "Confetti frames: 2–3px ink outlines; zigzag and squiggle dividers",
shadow: "Fresh-Prince offsets: 5px 5px 0 ink; pastel color-block shadows",
spacing: "Saturday-morning density: shape-scattered 72–96px sections, 24px cards",
aesthetic: "1993 in the best way: teal + purple + lime confetti, squiggle underlines, triangle patterns, boombox energy. Loud, fun, geometric. For snacks, games, kids, and throwback drops.",
principles: ["Confetti geometry everywhere — with grid discipline", "Teal + purple + lime + coral; black outlines", "Squiggles underline what matters"],
layout: "Throwback stack: confetti hero, shape-feature rows, pattern interludes, boombox CTA. Max-width 1240px.",
buttons: "Geo blocks: purple/teal fills, white bold labels, hard shadows; hover pops.",
cards: "Confetti cards: white, ink borders, shape badges, squiggle titles.",
nav: "Fresh bar: geometric mark, bold links, lime CTA. Zigzag trim.",
imagery: "Boomboxes, sneakers, cartoons, geometric patterns. Saturated and fun.",
icons: "Squiggles, triangles, lightning, gamepads — chunky 90s set.",
texture: "Confetti, zigzags, dots, checkerboards at 12–20%.",
motion: "Saturday bounce: 200ms pops, shape floats, squiggle draws. Playful springs.",
avoid: ["Muted minimal palettes", "Hairlines or subtlety", "Serif display type", "Slow fades", "Taking itself seriously"],
},
{
slug: "vaporwave",
name: "Vaporwave",
description: "Retro-futuristic gradients with nostalgic melancholy and Roman statues.",
category: "Decades",
tags: ["vaporwave", "aesthetic", "nostalgic"],
bg: "#17102E", surface: "#241545", ink: "#F5EDFF", muted: "#B3A1D6", accent: "#FF71CE", accent2: "#7DF9FF",
display: "Times New Roman, serif",
body: "Helvetica Neue, Arial, sans-serif",
radius: "0–8px; statues sharp, windows 90s-square",
border: "Chrome keylines; grid-floor horizons; VHS frame edges",
shadow: "Mall-glow: 0 0 40px pink/30; statue moonlight rims",
spacing: "Mall-at-midnight pacing: vast sunset vistas, 100px+ pauses, floating windows",
aesthetic: "Dead-mall melancholy: gradient suns over grid oceans, marble busts, palm silhouettes, Japanese microtype, VHS grain. Nostalgia as critique as comfort. For music, fashion, art, and internet-native brands.",
principles: ["Sunset gradient + grid + statue = the holy trinity", "Japanese microtype and shopping-mall signage as texture", "Melancholy pacing: slow, vast, empty on purpose"],
layout: "Vista scroll: sunset hero with statue, floating 90s windows with content, grid-ocean interludes, midnight CTA.",
buttons: "Mall-kiosk pills: chrome gradients, serif labels; hover glows pink.",
cards: "Floating windows: 90s chrome frames over vistas; statue cameos; VHS timestamps.",
nav: "Minimal over vista: ＡＥＳＴＨＥＴＩＣ tracked mark, window links, glowing CTA.",
imagery: "Statues, grid suns, palms, malls, VHS stills. Pink-cyan grade, heavy grain.",
icons: "Palms, suns, columns, floppy disks — mall-directory glyphs.",
texture: "VHS noise, grid floors, marble, chrome at 10–15%.",
motion: "Slow drift: sun shimmer, grid crawl (20s), VHS tracking wobble (rare). Numb slowness is correct.",
avoid: ["Bright daylight energy", "Corporate clarity", "Fast motion", "Explaining the joke", "Clean vector sterility"],
},
{
slug: "synthwave",
name: "Synthwave",
description: "Night-drive neon: outrun grids, chrome suns and analog-synth glow.",
category: "Decades",
tags: ["synthwave", "outrun", "night"],
bg: "#0A0118", surface: "#150826", ink: "#F5EDFF", muted: "#9A86C7", accent: "#FF2E88", accent2: "#FFD319",
display: "Orbitron, Monoton, sans-serif",
body: "Outfit, Inter, sans-serif",
radius: "Pills and sun-circles; sharp HUD panels",
border: "Laser keylines: 1–2px pink/amber; perspective grid floors; chrome trims",
shadow: "Night-drive glow: 0 0 30px pink/40 + amber underglow; sun halos",
spacing: "Night-drive pacing: sun hero, 80–100px highway chapters, 24px panels",
aesthetic: "Midnight on the interstate, 1985: chrome sun sinking into a perspective grid, laser-pink skies, muscle-car silhouettes, analog VU glow. Driving music made visual. For music, automotive, games, and drinks.",
principles: ["Sun + grid + night = instant synthwave", "Amber underglow grounds the pink skies", "Chrome display + mono telemetry details"],
layout: "Highway scroll: sun hero, grid chapters with content mile-markers, tunnel CTA finale. Max-width 1280px.",
buttons: "Laser pills with glow; amber solid for go-moments; hover flares headlights-bright.",
cards: "Dashboard panels: dark with laser keylines, VU details, sun-thumb headers.",
nav: "Night bar: chrome mark, laser links, glowing CTA; mile-marker progress.",
imagery: "Grid suns, highways, muscle cars, skylines. Pink-amber grade.",
icons: "Suns, grids, cassettes, steering glyphs — laser-line set.",
texture: "Grid floors, VHS grain, lens streaks, asphalt at 8–12%.",
motion: "Drive loops: grid scroll toward viewer (12s), sun pulse, headlight sweeps. Hypnotic highway constancy.",
avoid: ["Daylight palettes", "Earthy minimalism", "Static suns (pulse them)", "Serif typography", "Slow sleepy pacing — this drives"],
},
{
slug: "pixel-8bit",
name: "Pixel / 8-Bit",
description: "Crisp chunky pixels: sprite logic, limited palettes and arcade honesty.",
category: "Neon & Play",
tags: ["pixel", "8-bit", "arcade"],
bg: "#0F0F1B", surface: "#1B1B2E", ink: "#F2F0FF", muted: "#8E8AB0", accent: "#7DF9FF", accent2: "#FFD802",
display: "Press Start 2P, VT323, monospace",
body: "VT323, IBM Plex Mono, monospace",
radius: "0px — pixels are square (stepped corners via box-shadow trick allowed)",
border: "Pixel frames: 4px stepped borders (box-shadow pixel-corners); 2px sprite outlines",
shadow: "Hard pixel offsets: 4px 4px 0 black; no blur (blur is the enemy)",
spacing: "Sprite-grid: 8px pixel unit, 16/24/32px steps, 64–88px quest chapters",
aesthetic: "A cartridge come to life: chunky pixel type at display sizes, sprite icons, 4-color ramps, scanline overlays, HP bars and dialogue boxes as UI. Honest constraints, endless charm. For games, devtools with humor, education, and portfolios.",
principles: ["Pixels stay crisp: image-rendering pixelated, no smoothing", "Limited ramps (4–8 colors per scene); dither for gradients", "Game UI is the UI: HP bars, dialogue boxes, quest logs"],
layout: "Quest scroll: title-screen hero (PRESS START), world-map chapters, dialogue-box content, game-over CTA. Max-width 1100px.",
buttons: "Arcade buttons: stepped pixel frames, chunky fills, PRESS-style labels; hover flashes; press clunks.",
cards: "Dialogue boxes: bordered panels with portrait sprite + typed text + ▼ advance cue.",
nav: "HUD bar: hearts/coins counters, world tabs, mute toggle. Quest-log menu on mobile.",
imagery: "Pixel art scenes, sprites, tilesets. Consistent pixel scale (e.g. 4x) throughout.",
icons: "Sprite icons: hearts, coins, swords, potions — pixel-drawn, limited palette.",
texture: "Scanlines, CRT vignette, dither patterns. Pixel-perfect, never blurry.",
motion: "Frame-step motion (steps() easing!): sprite walks, blink cursors, typed dialogue. 8fps charm; reduced-motion = static frames.",
avoid: ["Blur or anti-aliasing on pixel assets", "Proportional fonts in HUD zones", "Photorealistic imagery", "Smooth eased motion on sprites (use steps!)", "Unlimited rainbow palettes"],
},
{
slug: "gaming-ui",
name: "Gaming UI",
description: "HUD-first interfaces: health bars, quest logs and reward-loop feedback.",
category: "Neon & Play",
tags: ["gaming", "hud", "rewards"],
bg: "#0B0E14", surface: "#12161F", ink: "#EDEFF5", muted: "#7C8698", accent: "#00E5FF", accent2: "#FFD802",
display: "Rajdhani, Chakra Petch, sans-serif",
body: "Inter, Rajdhani, sans-serif",
radius: "4–8px HUD panels; chamfered corners via clip-path",
border: "HUD frames: 1–2px cyan/25 keylines + corner brackets; rarity-color edges (common→legendary)",
shadow: "Combat glow: 0 0 20px accent/25; damage-red vignettes on errors; loot-gold glows",
spacing: "Command-center density: 12–16px panel padding, persistent HUD rails, 64–80px campaign chapters",
aesthetic: "A AAA HUD wrapped around your product: XP bars, quest-tracked onboarding, rarity-tiered cards, kill-feed activity, loot-box reveals for rewards. Play is the engagement model. For fitness, education, fintech, and community products.",
principles: ["Every action pays out: XP, bars, sounds-off flashes", "Rarity colors mean fixed tiers — document the loot table", "HUD persists: progress is always visible"],
layout: "Command center: HUD header (level, XP, currency), quest rail left, main arena center, feed right. Campaign chapters for marketing.",
buttons: "Ability buttons: chamfered, keyed (Q/E/R hints), cooldown sweeps; primary glows. Big and thumb-ready.",
cards: "Loot cards with rarity frames + tilt-reveal; quest cards with progress bars and reward rows.",
nav: "HUD header: avatar + level ring, nav tabs as zones, currency counters, settings cog.",
imagery: "Splash-art heroes, 3D loot renders, map vistas, character portraits. Cinematic grade.",
icons: "Ability glyphs, rank badges, currency coins — game-icon clarity at 16–48px.",
texture: "Hex grids, carbon, scanlines, particle embers at 6–10%.",
motion: "Juice: XP bar tweens, damage shakes (subtle), loot reveals (500ms), level-up fanfares. Reduced-motion = instant results + toasts.",
avoid: ["Gamification without rewards (bars that never fill)", "Pay-to-win optics", "Obscuring real function behind game chrome", "Endless grinding with no rest states", "Motion that hides outcomes"],
},
{
slug: "comic-pop-art",
name: "Comic / Pop Art",
description: "Halftone heroics: bold inks, burst captions and four-color excitement.",
category: "Neon & Play",
tags: ["comic", "pop-art", "halftone"],
bg: "#F5F0E6", surface: "#FFFFFF", ink: "#141414", muted: "#6E675C", accent: "#E30613", accent2: "#FFD802",
display: "Bangers, Archivo Black, sans-serif",
body: "Comic Neue, Inter, sans-serif",
radius: "0–10px; panels sharp, bursts star-shaped",
border: "Ink-heavy: 3px panel frames, burst badges, caption boxes (yellow, bordered)",
shadow: "POW offsets: 6px 6px 0 ink; action-line speed streaks",
spacing: "Splash-page pacing: full-bleed splashes, 3–4 panel grids, burst interjections, 72–96px issues",
aesthetic: "Silver-age comics as UX: panel grids with gutters, caption boxes narrating the journey, burst badges for offers, halftone shading. Reading order = user flow. For snacks, sports, kids, events, and challengers.",
principles: ["Panels sequence the story — gutters pace the scroll", "Captions narrate; bursts exclaim; ration both", "Four colors + ink; dots do the rendering"],
layout: "Issue architecture: splash hero, panel-grid features, caption transitions, letters-page testimonials, next-issue CTA.",
buttons: "Burst buttons (star-shaped clip-path!) and ink bars; hover POW-scales.",
cards: "Comic panels: ink frames, caption box header, art middle, burst badge corner.",
nav: "Masthead bar: issue number, logo burst, section panels links.",
imagery: "Comic art, halftone photos, action lines, onomatopoeia. Bold and flat.",
icons: "Bursts, stars, arrows, pow-glyphs — Kirby energy, thick and few.",
texture: "Halftones, newsprint, action lines, ink splatter (rare).",
motion: "Panel slams, burst pops, caption typewriter. Comic timing: fast beats, held poses.",
avoid: ["Muted palettes", "Thin lines", "Photorealistic seriousness", "Wall-of-text issues (show, don't tell)", "Burst inflation (save POWs)"],
},
{
slug: "graffiti-streetwear",
name: "Graffiti / Streetwear",
description: "Concrete-culture edge: tags, drips and drop-model urgency.",
category: "Neon & Play",
tags: ["graffiti", "streetwear", "urban"],
bg: "#111111", surface: "#1A1A1A", ink: "#F5F2EA", muted: "#8A877E", accent: "#D6FF3F", accent2: "#FF4D00",
display: "Permanent Marker, Archivo Black, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–8px; tags freeform, product sharp",
border: "Spray edges: rough SVG masks, drip dividers, sticker frames with white keylines",
shadow: "Alley depth: 0 16px 48px black/60; spray-glow tags in lime/orange",
spacing: "Drop rhythm: countdown hero, wall-of-fame grids, 72–96px chapters, sold-out stamps",
aesthetic: "A fresh wall at 2am: wildstyle tags, wheat-paste layers, sticker slaps, drop countdowns, sold-out stamps. Hype with concrete credibility. For streetwear, sneakers, music, energy drinks, and youth culture.",
principles: ["Tags are signatures — commission real lettering", "Drops drive design: countdowns, stock bars, stamps", "Concrete textures ground the hype"],
layout: "Drop sequence: countdown hero, lookbook wall, product grid with stock bars, wall-of-fame UGC, restock footer.",
buttons: "Slap stickers and spray blocks; hover drips; sold-out stamps replace buttons honestly.",
cards: "Product slabs: dark, sticker-framed, stock-bar footers, size-row selects.",
nav: "Alley bar: tag logo, drop links, cart with count, countdown pill.",
imagery: "Wall photography, lookbook flash shots, product on concrete, sticker macros. High contrast flash grade.",
icons: "Crowns, drips, arrows, stars — tag-adjacent glyphs, rough strokes.",
texture: "Concrete, wheat-paste, spray grain, sticker vinyl at 10–18%.",
motion: "Spray-ins (masked reveals), drip loops (subtle), countdown urgency, sticker slaps on add-to-cart.",
avoid: ["Clean minimal luxury cues", "Fake urgency without real stock logic", "Thin delicate type", "Stock lifestyle photography", "Cultural tourism without credibility"],
},
{
slug: "quiet-luxury",
name: "Quiet Luxury",
description: "Restrained serif typography and whitespace for understated wealth.",
category: "Heritage Luxury",
tags: ["quiet-luxury", "refined", "understated"],
bg: "#F7F5F0", surface: "#FFFFFF", ink: "#2B2926", muted: "#6F695F", accent: "#2B2926", accent2: "#8C6E3F",
display: "Cormorant Garamond, EB Garamond, serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–4px; restraint in geometry",
border: "Whisper rules: 1px #E5E0D5 hairlines; no boxes around content",
shadow: "None — wealth doesn't elevate, it settles",
spacing: "Old-money pacing: 140px+ sections, 720px measure, single objects per view",
aesthetic: "Stealth wealth rendered digital: perfect neutrals, exquisite serif headlines, cashmere-beige grounds, tiny tracked labels, no logos shouting. Quality legible only to those who know. For private banks, tailoring, skincare, and advisory.",
principles: ["No logos-as-decoration; wordmarks whisper", "Beige, stone, ink — color is a rumor", "One perfect thing per view"],
layout: "Gallery-quiet: single-column statements, look-book imagery, private-client closers. Max-width 1100px.",
buttons: "Understated ink bars with tracked 12px labels; hover deepens slowly. Appointments over checkouts.",
cards: "No cards — framed plates with captions. Services as quiet index rows.",
nav: "Whisper bar: small wordmark, three links, contact. Fades to hairline.",
imagery: "Cashmere macro, stone interiors, tailored details, foggy landscapes. Desaturated warm grade.",
icons: "Hairline glyphs, barely there. Monograms over pictograms.",
texture: "Cashmere, stone, paper at 3–5%. Restraint in opacity too.",
motion: "Glacial: 600ms fades, slow image settles. Silence between moves.",
avoid: ["Logos patterns or monogram wallpaper", "Gold or jewel tones (that's luxury-maximalism)", "Urgency or discounts", "Rounded playful geometry", "Explaining wealth (show, don't tell)"],
},
{
slug: "surrealism",
name: "Surrealism",
description: "Dream-logic interfaces: floating objects, impossible scale and poetic dissonance.",
category: "Experimental",
tags: ["surreal", "dream", "art"],
bg: "#EDE6D8", surface: "#F7F2E7", ink: "#2B2620", muted: "#6C675C", accent: "#0F4C81", accent2: "#C81E1E",
display: "Cormorant Garamond, Georgia, serif",
body: "EB Garamond, Georgia, serif",
radius: "Oval cameos, arch portals, cloud-soft blobs",
border: "Horizon lines, oval frames, shadow-casting rules (objects float above grounds)",
shadow: "Impossible light: long dramatic shadows (0 30px 60px warm/25) under floating objects",
spacing: "Gallery-dream pacing: vast skies (140px+), single floating subjects, poem captions",
aesthetic: "Dalí's waiting room: melting clocks optional (one, earned), floating staircases, giant eggs, tiny figures in vast skies. Poetic dissonance with museum manners. For galleries, perfume, film, and brands selling mystery.",
principles: ["One impossibility per view — dreams are sparse", "Vast skies make small objects profound", "Captions are poetry, not UX copy"],
layout: "Dream sequence: sky hero with floating subject, horizon chapters, cabinet-of-curiosities grid, waking CTA.",
buttons: "Portal buttons: oval/arch outlines, serif labels; hover levitates. Few and ceremonial.",
cards: "Curiosity plates: floating object + shadow + poem caption. No grids of many.",
nav: "Whisper bar over skies: small mark, three dream links. Dissolves on scroll.",
imagery: "Impossible photography and illustration: floating objects, vast skies, ladders to nowhere. Warm desaturated grade.",
icons: "Keys, eyes, eggs, ladders — dream glyphs, thin and few.",
texture: "Cloud grain, canvas weave, desert sand at 6–10%.",
motion: "Levitating idles (8s float), slow parallax skies, melting transitions (rare, earned). Hypnotic slowness.",
avoid: ["Multiple impossibilities competing", "Explaining the dream (no lore dumps)", "Bright candy color", "Fast motion", "Cluttered curiosity cabinets"],
},
{
slug: "dreamcore",
name: "Dreamcore",
description: "Liminal nostalgia: familiar places, hazy memory and VHS softness.",
category: "Experimental",
tags: ["dreamcore", "liminal", "nostalgic"],
bg: "#E8E4D8", surface: "#F2EEE2", ink: "#3B3830", muted: "#6A655A", accent: "#5B8DD9", accent2: "#E8A0BF",
display: "Georgia, Times New Roman, serif",
body: "Verdana, Georgia, serif",
radius: "Soft memory: 12px rounded photos, hazy vignettes",
border: "Memory frames: white polaroid-ish mats, soft vignettes, timestamp captions",
shadow: "Hazy: 0 8px 30px warm-gray/20 + vignette darkening on imagery",
spacing: "Wandering pace: meandering image rivers, 100px+ pauses, caption fragments",
aesthetic: "A half-remembered afternoon: empty playgrounds, mall corridors, birthday-party photos with timestamps, VHS haze. Comfort and unease in equal measure. For music, art, fashion, and memory brands.",
principles: ["Familiar + slightly wrong = the feeling", "Timestamps and captions anchor the haze", "Wander, don't funnel — exploration over conversion"],
layout: "Memory walk: hazy hero image, wandering photo rivers with fragments, rest-stop chapters, guestbook closer.",
buttons: "Keepsake buttons: soft fills, timestamp labels; hover sharpens (memory focuses).",
cards: "Memory cards: hazy photo + timestamp + fragment caption. No CTAs inside memories.",
nav: "Faint bar: small mark, wander links, date readout. Barely there, like memory.",
imagery: "Liminal photography: empty public spaces, party candids, VHS stills. Hazy warm grade, timestamps.",
icons: "Stars, eyes, doors, sun-faded glyphs — memory-symbols, soft.",
texture: "VHS grain 10%, light leaks, dust, vignette. Haze is structural.",
motion: "Drifting: slow Ken Burns, haze shifts, timestamp flickers (rare). Sleepy 800ms+ timings.",
avoid: ["Sharp corporate clarity", "Bright saturated energy", "Funnels and urgency", "Explaining the feeling", "Fast motion (dreams don't hurry)"],
},
{
slug: "liminal-weirdcore",
name: "Liminal / Weirdcore",
description: "Threshold-space unease: empty corridors, low-fi text and strange comfort.",
category: "Experimental",
tags: ["liminal", "weirdcore", "strange"],
bg: "#D8D5CC", surface: "#E4E1D8", ink: "#2B2B2B", muted: "#605C55", accent: "#C81E1E", accent2: "#0F4C81",
display: "Arial, Helvetica, sans-serif",
body: "Arial, Verdana, sans-serif",
radius: "0–4px; fluorescent-lit sharpness",
border: "Institutional edges: tile grids, ceiling-grid dividers, exit-sign red accents",
shadow: "Fluorescent flat: even shadowless light + vignette unease on imagery",
spacing: "Threshold pacing: long empty corridors (160px+ voids), sparse text islands, echoing footers",
aesthetic: "Backrooms-adjacent: empty offices, pools at night, playgrounds fogged, low-fi overlaid text (YOU ARE HERE). Strange comfort through emptiness. For horror, alt-music, art, and games.",
principles: ["Emptiness is the content — protect the voids", "Low-fi text overlays (IDs, arrows, HELP) as wayfinding", "Fluorescent palette: beige, tile-white, exit red"],
layout: "Threshold walk: corridor hero, empty room chapters with text islands, pool-night interlude, exit-sign closer.",
buttons: "Institutional plates: beige fills, black labels, exit-red for the one true CTA.",
cards: "Room cards: empty-space photo + overlay text fragment. Sparse and strange.",
nav: "Directory-plate bar: floor numbers, YOU-ARE-HERE dot, minimal links.",
imagery: "Liminal photography: empty malls, corridors, pools, playgrounds. Flat fluorescent grade.",
icons: "Exit signs, arrows, IDs, smileys (one, unsettling) — institutional glyphs.",
texture: "Carpet tile, ceiling grid, pool ripple, VHS grain at 8–12%.",
motion: "Uncanny stillness: fluorescent hum-flicker (very subtle, safe), slow zooms into emptiness. Mostly still.",
avoid: ["Filling the voids (the cardinal sin)", "Bright cheerful energy", "Explaining the lore", "Horror gore (unease > shock)", "Photosensitive flicker — keep hum barely-there"],
},
{
slug: "generative-algorithmic",
name: "Generative / Algorithmic",
description: "Systems-made visuals: code-drawn patterns, live parameters and data beauty.",
category: "Experimental",
tags: ["generative", "code-art", "data"],
bg: "#0A0A0B", surface: "#131316", ink: "#F2F0EA", muted: "#8A877E", accent: "#D6FF3F", accent2: "#7C5CFF",
display: "Space Grotesk, IBM Plex Mono, sans-serif",
body: "Inter, IBM Plex Mono, monospace",
radius: "2–8px; system-sharp with soft panels",
border: "System frames: 1px white/12, parameter-readout chips, seed displays (SEED #4821)",
shadow: "Data glow: 0 0 30px accent/15; canvas bloom on dark",
spacing: "Lab rhythm: live canvas hero, parameter decks, gallery of seeds, 88–110px sections",
aesthetic: "The algorithm is the artist: canvas-drawn flows, parametric grids, seed-based editions, sliders that re-grow the visuals. Transparent systems, beautiful outputs. For AI products, data tools, festivals, and studios.",
principles: ["Show the system: seeds, parameters, and code are content", "Every visual reproducible from a seed — display it", "Interactivity grows understanding: sliders > paragraphs"],
layout: "Lab scroll: live hero canvas + parameter deck, gallery of seeds (regenerate!), methodology band, API CTA.",
buttons: "Lab controls: regenerate (dice), slider decks, seed chips, export PNG. Primary in lime.",
cards: "Seed cards: canvas thumb + seed number + parameter readout + remix button.",
nav: "System bar: mark, gallery/method/API links, live seed readout, export CTA.",
imagery: "Canvas-generated: flows, grids, topographies. No stock — the system draws everything.",
icons: "Dice, sliders, seeds, export glyphs — lab-instrument style, mono labels.",
texture: "Canvas grain, plotter lines, halftone-from-code. Generated, never pasted.",
motion: "Living canvases (rAF, paused offscreen + reduced-motion stills); parameter morphs 400ms; seed transitions.",
avoid: ["Static fake-generative gradients", "Hiding seeds/parameters (kills trust)", "Heavy canvases without perf budgets", "Unexplained randomness", "Motion without pause controls"],
},
];
