export const stylesE = [
{
slug: "kinetic-typography",
name: "Kinetic Typography",
description: "Type in motion: words that slide, scramble and perform the message.",
category: "Immersive & Motion",
tags: ["kinetic", "motion-type", "expressive"],
bg: "#0E0E0E", surface: "#161616", ink: "#F4F1EA", muted: "#8F8B82", accent: "#D6FF3F", accent2: "#FF5C00",
display: "Archivo Black, Anton, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–8px; type moments sharp, UI quietly rounded",
border: "Baseline rules and ticker frames; captions in bordered chips",
shadow: "Type echoes: layered offset duplicates on key words; UI stays flat",
spacing: "Performance pacing: full-viewport statements, 40px caption rails, 100px act breaks",
aesthetic: "Music-video typography as interface: lines that scramble in, words that highlight like karaoke, marquees that argue with headlines. The message performs itself. For launches, manifestos, music, and studios.",
principles: ["Motion carries meaning: scramble = decode, highlight = emphasize", "One kinetic moment per viewport", "Always ship a static final state (SEO + reduced-motion)"],
layout: "Set list: full-viewport type acts, caption rails, encore CTA. Persistent progress dots.",
buttons: "Lyric-links: giant underlined phrases as CTAs; bordered replay buttons; solid lime for conversion.",
cards: "Set cards: act number + kinetic line + caption; no boxes around performing type.",
nav: "Minimal overlay + act menu; mute-motion toggle always visible.",
imagery: "Type-first; cutaway imagery in letterform masks or breakout bands; tour-grade photography secondary.",
icons: "Play, replay, sound, motion-toggle glyphs — functional, quiet.",
texture: "Dark flat with grain; lyric-highlight washes; scanline shimmer on performing lines.",
motion: "Core: char-split reveals, scramble decodes, karaoke highlights, marquee arguments. 60fps transforms; reduced-motion = final frames + stepper.",
avoid: ["Kinetic body copy (headlines only)", "Multiple simultaneous animations", "Motion without a mute toggle", "SEO-empty animated canvases (mirror text in DOM)", "Seasickness speeds"],
},
{
slug: "typography-first",
name: "Typography-First",
description: "Reading-led design: exquisite measure, scale and hierarchy over decoration.",
category: "Type-Led",
tags: ["typography", "reading", "hierarchy"],
bg: "#FDFCF9", surface: "#FFFFFF", ink: "#1B1A17", muted: "#74706A", accent: "#1B1A17", accent2: "#2B4EFF",
display: "Newsreader, Georgia, serif",
body: "Newsreader, Source Serif 4, Georgia, serif",
radius: "0–4px; print-sharp",
border: "Typographic rules only: kickers with rules, footnote dividers, chapter numerals",
shadow: "None — paper has no elevation",
spacing: "Reading science: 60–70ch measure, 1.6–1.8 line-height, 32px paragraph rhythm, 96px chapters",
aesthetic: "A book that happens to be a website: perfect measure, considered scale steps (1.25 ratio), footnotes, sidenotes, and pull quotes. Links are the only blue. For publishers, docs, essays, and tools where reading IS the job.",
principles: ["Measure, leading, and scale — in that order of importance", "Hierarchy through type alone: size, weight, italic, caps", "Footnotes and sidenotes are first-class citizens"],
layout: "Reading column (680px) + sidenote rail (220px, desktop); chapter openers; TOC sidebar for long works. Quiet progress hairline.",
buttons: "Text-scale actions: small-caps links, footnote-style buttons, one ink subscribe bar. Hover underlines deepen.",
cards: "No cards — pull quotes, asides, and footnote blocks with rules. Index rows for archives.",
nav: "Chapter nav: TOC with current-section highlight; prev/next chapter footer; print/reading-mode toggles.",
imagery: "Figures with captions and numbers; diagrams in ink; author portraits small. Images serve the text.",
icons: "Section marks (§), pilcrows (¶), footnote daggers (†) — typographic furniture, not pictograms.",
texture: "Paper white flat; deckle edge on covers only; ink-friendly 3% grain.",
motion: "Reading-calm: smooth anchor scroll, footnote popovers 150ms, highlight-on-cite. Nothing else moves.",
avoid: ["Cards, shadows, or SaaS chrome", "Sans-serif body text", "Wide measures over 75ch", "Popups interrupting reading", "Decorative animation"],
},
{
slug: "variable-fonts",
name: "Variable Fonts",
description: "Living letterforms: weight, width and optical size reacting to context.",
category: "Type-Led",
tags: ["variable", "interactive-type", "fluid"],
bg: "#F4F2ED", surface: "#FFFFFF", ink: "#141414", muted: "#6E6A61", accent: "#E30613", accent2: "#1D4ED8",
display: "Inter Variable, Fraunces Variable, sans-serif",
body: "Inter Variable, system-ui, sans-serif",
radius: "0–8px; type playgrounds sharp, UI softly rounded",
border: "Specimen frames: 1–2px ink rules, axis sliders styled as lab controls, waterfall dividers",
shadow: "Lab-calm: 0 4px 20px rgba(0,0,0,0.06) on playground panels; type stays flat",
spacing: "Specimen rhythm: giant interactive lines (10vw), axis control decks, 72–96px lab sections",
aesthetic: "A type lab you can play: headlines whose weight follows scroll or cursor, width that breathes with viewport, optical sizes that snap at breakpoints. Interactive specimens teach the system. For foundries, design tools, and brands with a voice that modulates.",
principles: ["Map axes to meaning: weight = emphasis, width = space, italic = aside", "Show the controls: sliders and readouts invite play", "Performant play: font-variation-settings with will-change discipline"],
layout: "Lab sequence: playable hero line + axis deck, waterfall specimens, pairing playground, buy/get section. Max-width 1280px.",
buttons: "Lab controls: axis sliders, preset chips (Caption → Display), Get-the-font CTA in ink. Readouts in mono.",
cards: "Specimen panels: bordered playgrounds with axis labels, waterfall rows, pairing cards.",
nav: "Foundry bar: wordmark, family index, weights dropdown, trial CTA. Axis readout in mono.",
imagery: "Type specimens as imagery; process sketches; variable animations exported as loops.",
icons: "Axis glyphs (wght/wdth/opsz), play/reset, download — lab-instrument style.",
texture: "Paper flat; slider-track grooves; faint waterfall gridlines.",
motion: "The product: scroll/cursor-mapped variation (rAF-throttled), preset morphs 400ms. Reduced-motion = preset stepper.",
avoid: ["Animating axes on body copy (display only)", "Janky unthrottled variation updates", "Hiding axis values (show the numbers!)", "Too many families at once", "Faux bold/italic on variable files"],
},
{
slug: "oversized-typography",
name: "Oversized Typography",
description: "Scale as spectacle: viewport-filling headlines that carry whole pages.",
category: "Type-Led",
tags: ["oversized", "display", "bold"],
bg: "#111111", surface: "#1A1A1A", ink: "#F5F2EA", muted: "#8A877E", accent: "#FF4D00", accent2: "#F5F2EA",
display: "Anton, Archivo Black, Impact, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–6px; scale needs no softening",
border: "Typographic architecture: rules between giant lines, outlined echo rows, index ticks",
shadow: "Scale shadows: hard offset echoes (6px 6px 0 accent) on one line max; UI flat",
spacing: "Monumental: 14–22vw lines, -0.04em tracking, 0.9 leading, 100px+ pauses between statements",
aesthetic: "Brutalist scale with editorial control: three giant lines per page do the work of ten sections. Words become rooms you walk through. For festivals, studios, athletes, and launches with one huge thing to say.",
principles: ["3–7 words per giant line; edit until it fits", "One family, three treatments (fill/outline/italic) max", "Small mono meta frames the monuments"],
layout: "Monument stack: full-bleed giant statements alternating with quiet meta bands and one image break. Footer as final monument.",
buttons: "Monument-links: giant underlined phrases; bordered index buttons; one solid accent conversion block.",
cards: "No cards — statement blocks with rules and numerals. Lineup/schedule as giant index rows.",
nav: "Overlay minimal: mark + menu + ticket CTA; full-screen giant-link menu.",
imagery: "Scale contrast: tiny images inside giant type (masks), or single full-bleed breaks. Duotone to match ink.",
icons: "Arrows and numerals at display scale (→ ↗ 01). Nothing small and fussy.",
texture: "Dark grain, misregistration on one line, concrete flat alternative on light variant.",
motion: "Scroll-scrubbed line reveals (clip-path), char stagger on entry, marquee echoes. Damped and heavy — monuments move slowly.",
avoid: ["Paragraphs at display scale", "Multiple competing giant messages", "Thin weights at huge sizes (go black)", "Centering everything (flush-left monuments hit harder)", "Small timid CTAs"],
},
{
slug: "collage",
name: "Collage",
description: "Cut-and-paste energy: torn edges, tape and layered fragments with intent.",
category: "Cut & Paste",
tags: ["collage", "cut-paste", "layered"],
bg: "#EFE9DC", surface: "#FFFFFF", ink: "#1C1B1A", muted: "#6E675C", accent: "#C81E1E", accent2: "#0F4C81",
display: "Archivo Black, Georgia, serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0px + torn clip-paths; tape strips translucent",
border: "Torn edges (clip-path polygons), tape strips, deckled frames, marker outlines",
shadow: "Paste depth: 4px 6px 0 rgba(28,27,26,0.9) under lifted fragments; tape translucency",
spacing: "Composed clutter: 12–32px overlaps, rotations ±4deg, 72–96px chapters with breathing room",
aesthetic: "A studio wall mid-project, art-directed: torn magazine fragments, taped type, circled details, sticker interventions — layered over warm paper with one alignment axis keeping it shippable. For agencies, music, fashion, and culture brands.",
principles: ["Layer with hierarchy: hero fragment, support cluster, tape accents", "Torn + taped + circled = the material trio", "One axis of alignment survives the beautiful mess"],
layout: "Wall composition: hero fragment cluster, support strips, chapter breaks as taped labels. Max-width 1280px.",
buttons: "Taped stickers and circled links; hover peels (rotate 0 + lift). Big and few.",
cards: "Fragment clusters: bordered scraps with tape, captions handwritten-style, sticker badges.",
nav: "Taped bar: logo cut-out, marker links, CTA sticker. Slight tilt (-0.5deg) on the strip.",
imagery: "Torn photos, magazine cuts, ticket stubs, stamped textures. Mixed eras unified by paper grade.",
icons: "Hand-circled arrows, tape flags, star stickers — annotation graphics.",
texture: "Paper grain 6%, tape gloss, marker strokes, stamp ink, deckle edges.",
motion: "Peel physics: hover straightens with spring; entrances drop with thud; tape shimmer subtle. 300ms springs.",
avoid: ["Randomness without composition", "Digital-perfect edges on torn elements", "Unreadable overlaps", "Chaos in transactional flows", "Forgetting mobile stacking order"],
},
{
slug: "scrapbook",
name: "Scrapbook",
description: "Memory-keeping warmth: photos, tickets and handwritten notes in keepsake grids.",
category: "Cut & Paste",
tags: ["scrapbook", "memory", "handmade"],
bg: "#F3EDE2", surface: "#FFFDF6", ink: "#3B362E", muted: "#6F675E", accent: "#B3541E", accent2: "#5B7E6B",
display: "Caveat, Georgia, serif",
body: "Karla, Inter, sans-serif",
radius: "2–6px photos with white polaroid borders; tape corners",
border: "Keepsake frames: white polaroid mats, stitched dashes, washi-tape strips",
shadow: "Keepsake lift: 0 6px 18px rgba(59,54,46,0.15) under photos; tape translucency",
spacing: "Keepsake rhythm: overlapping mementos, 24px journal padding, 72–96px chapters",
aesthetic: "A family album as interface: polaroids with captions, ticket stubs, pressed flowers (CSS), washi tape, and one handwritten font used sparingly. Warm, personal, nostalgic. For weddings, travel, family brands, and community stories.",
principles: ["White polaroid mats unify any photo mix", "One handwritten accent font; everything else highly legible", "Dates and captions ARE the content — write them well"],
layout: "Album spread: hero memory wall, timeline chapters with date tabs, guest-note margins. Max-width 1100px.",
buttons: "Sticker and stamp buttons: rounded, warm fills, handwritten labels sparingly. RSVP/contribute CTAs prominent.",
cards: "Memory cards: polaroid photo + caption + date stamp; ticket-stub dividers with perforation dashes.",
nav: "Keepsake bar: family/brand mark, chapter tabs (dates), contribute CTA. Doily-trim optional (one!).",
imagery: "Personal photos in polaroid mats, scanned ephemera, pressed-flower CSS motifs, kraft envelopes.",
icons: "Hearts, stars, stamps, scissors — keepsake glyphs, warm and few.",
texture: "Kraft paper, linen, washi patterns, photo grain at 6–10%.",
motion: "Gentle: photo lift on hover, page-turn chapter transitions (400ms), falling-petal accent (once, subtle).",
avoid: ["Slick stock photography", "Multiple script fonts", "Dark moody grading on memories", "Clutter that buries the captions", "Forgetting print/export (albums want printing)"],
},
{
slug: "zine-punk",
name: "Zine / Punk",
description: "Xeroxed rebellion: cut letters, harsh contrast and photocopied fury.",
category: "Cut & Paste",
tags: ["zine", "punk", "xerox"],
bg: "#F2F0EB", surface: "#FFFFFF", ink: "#111111", muted: "#5C5A55", accent: "#D92300", accent2: "#FFEB00",
display: "Impact, Arial Black, sans-serif",
body: "Courier New, monospace",
radius: "0px + photocopy-rough clip edges",
border: "Cut-paper edges, taped rips, marker blackouts, stamp frames",
shadow: "Xerox depth: hard 5px offsets + photocopy noise; redaction bars as dividers",
spacing: "Ransom-note rhythm: colliding sizes, 16px dense columns, full-bleed scream sections",
aesthetic: "A Kinko's at midnight: cut-out headlines, ransom-note type mixing, high-contrast xerox portraits, safety-pin motifs, redaction bars. Loud, cheap, and honest. For bands, venues, activist causes, indie games, and streetwear.",
principles: ["Contrast is king: black on white, red for alarm", "Mix 3+ type treatments like ransom notes — with conviction", "Photocopy texture unifies everything rebellious"],
layout: "Manifesto stack: scream hero, lineup index, manifesto columns, show-date tables, distro footer. Max-width 1200px.",
buttons: "Cut-out stickers and stamp buttons; hover slams (scale 1.05, 100ms). Ticket blocks with stub edges.",
cards: "Flyer panels: xerox image + cut headline + date stamp + tape. No polish, all conviction.",
nav: "Flyer header: logo cut-out, date marquee, section stamps. Sticky with xerox edge.",
imagery: "High-contrast xerox portraits, cut-and-paste collage, safety pins, barcodes, stamps.",
icons: "Anarchy-adjacent glyphs: pins, bolts, skulls (one), arrows — cut-out style.",
texture: "Photocopy grain 12–18%, halftones, marker strokes, tape, staple dots.",
motion: "Slam cuts: hard entrances 150ms, marquee lineups, hover slams. No easing softness.",
avoid: ["Polished corporate anything", "Polite single-typeface restraint", "Soft shadows or gradients", "Stock photography", "Preachy without show dates (earn the anger)"],
},
{
slug: "risograph",
name: "Risograph",
description: "Soy-ink print charm: misregistered layers, grain and limited spot palettes.",
category: "Handmade & Texture",
tags: ["riso", "print", "grain"],
bg: "#F4F1EA", surface: "#FFFFFF", ink: "#232323", muted: "#7A766E", accent: "#FF6655", accent2: "#0078BF",
display: "Archivo Black, Space Grotesk, sans-serif",
body: "Space Grotesk, Inter, sans-serif",
radius: "0–10px; print-sharp with soft paper warmth",
border: "Ink keylines in spot colors; registration-mark motifs; deckled dividers",
shadow: "Print depth: multiply-layer offsets (red/blue split 3px) instead of shadows",
spacing: "Print rhythm: 2–3 spot colors max, 72–100px gallery sections, 24px print padding",
aesthetic: "Ariso print run, interactive: fluorescent pink + teal + black layers, visible misregistration, heavy soy-grain, paper tooth. Each scroll feels pulled from the drum. For illustrators, publishers, studios, and merch brands.",
principles: ["2–3 spot inks only — limitation is the look", "Misregister on purpose: 2–4px layer offsets", "Grain everywhere: 10–15% soy noise unifies"],
layout: "Print gallery: hero duotone poster, process bands (layers separating on scroll!), edition grid, shop footer. Max-width 1240px.",
buttons: "Spot-ink blocks with misregistered echo on hover; edition-style numbered CTAs.",
cards: "Print plates: duotone image + ink frame + edition numeral + price stamp.",
nav: "Studio bar: mark, ink-dot palette switcher (fun!), editions link, cart CTA.",
imagery: "Duotone illustrations, grainy photos in spot inks, process separations as content.",
icons: "Print-shop glyphs: drums, registration marks, ink drops — spot-colored.",
texture: "Soy grain 10–15%, paper tooth, misregistration, roller marks in margins.",
motion: "Print process: layers slide into registration on scroll (scrubbed, delightful); hover misregisters. Reduced-motion = registered stills.",
avoid: ["Full CMYK photorealism", "Clean vector sterility", "More than 3 inks", "Shadows instead of layer offsets", "White sterile grounds (warm paper!)"],
},
{
slug: "halftone",
name: "Halftone",
description: "Print-dot drama: comic dots, duotone pops and Ben-Day patterned depth.",
category: "Handmade & Texture",
tags: ["halftone", "dots", "pop"],
display: "Archivo Black, Anton, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–12px; pop panels sharp, stickers round",
border: "Ink frames 2–3px; Ben-Day dot dividers; burst badges",
shadow: "Pop depth: hard 5px ink offsets; dot-gradient fades instead of blurs",
spacing: "Pop rhythm: dot-field grounds, 24px panel padding, 72–96px chapters",
aesthetic: "Lichtenstein meets the landing page: Ben-Day dot fields, duotone photo-pops, burst badges (POW pricing!), and ink-heavy frames. Dots do the shading. For comics, snacks, sports, and challenger brands with punch.",
bg: "#F5F0E6", surface: "#FFFFFF", ink: "#141414", muted: "#6E675C", accent: "#E30613", accent2: "#0B3D91",
principles: ["Dots are shading: scale dot size with tone, never use gradients", "Duotone + dots + ink = complete image system", "Bursts and bangs punctuate — ration to conversion moments"],
layout: "Pop sequence: dot-field hero with burst, feature rows with duotone thumbs, burst CTA finale. Max-width 1240px.",
buttons: "Burst and bar buttons: ink-bordered red/yellow blocks, POW hover scale (1.04, 120ms).",
cards: "Pop panels: duotone image top, dot-fade edge, ink frame, burst price badges.",
nav: "Strip bar: logo burst, condensed links, red CTA block. Dot trim top.",
imagery: "Duotone photography with dot overlays, comic illustrations, burst badges, onomatopoeia accents.",
icons: "Burst stars, bangs, arrows — comic furniture, thick and few.",
texture: "Ben-Day dots 8–20%, newsprint grain, misregistration on display lines.",
motion: "Pop physics: slam entrances, burst spins (slow), hover POWs. Snappy 120–200ms.",
avoid: ["Smooth gradients (dots only!)", "Muted corporate palettes", "Thin delicate anything", "Photorealistic un-dotoned heroes", "Burst overuse (save POWs for money moments)"],
},
{
slug: "grain-noise",
name: "Grain / Noise",
description: "Analog warmth over digital: film grain, texture overlays and tactile depth.",
category: "Handmade & Texture",
tags: ["grain", "film", "analog"],
bg: "#131311", surface: "#1C1C1A", ink: "#EDEAE2", muted: "#8A867C", accent: "#E8FF47", accent2: "#FF6B4A",
display: "Inter Tight, Helvetica Neue, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "10–16px soft modern; grain over everything",
border: "Hairlines white/12; grain unifies panels and photos into one stock",
shadow: "Analog depth: soft dark drops + grain overlay (SVG turbulence, 6–10%) on all surfaces",
spacing: "Cinematic-modern: 96–128px sections, 28px panel padding, generous image chapters",
aesthetic: "Shot-on-film digital: clean modern layouts with a permanent grain overlay, warm blacks, muted highlights, tactile photography. The grain says human; the grid says professional. For photographers, studios, fashion, and premium content brands.",
principles: ["One grain recipe (SVG turbulence + opacity) across the whole site", "Warm the blacks, mute the whites — filmic tone curve", "Grain over everything equally: UI, photos, gradients"],
layout: "Modern editorial with film finish: hero image chapter, feature grid, full-bleed photo breaks, journal footer. Max-width 1280px.",
buttons: "Clean pills/bars with filmic hover (grain intensifies + lift). Lime accent for conversion.",
cards: "Modern cards with grain finish: image tops graded filmic, 16px radius, soft shadows + noise.",
nav: "Clean bar with grain finish; mono exposure-readouts as playful meta (ISO 400 · f/2.8).",
imagery: "Filmic photography: warm shadows, soft highlights, visible grain. Consistent preset across all images.",
icons: "Clean line icons; aperture/film glyphs as brand motifs.",
texture: "Film grain 6–10% (animated option at 8fps, subtle), paper tooth on light variant, halation on highlights.",
motion: "Subtle: grain shimmer (optional, off by default), slow Ken Burns, 300ms lifts. Calm and confident.",
avoid: ["Clean sterile digital without grain (misses the point)", "Heavy HDR or oversaturated looks", "Grain so heavy text suffers", "Mixing film stocks per section", "Forgetting reduced-motion for animated grain"],
},
{
slug: "hand-drawn",
name: "Hand-Drawn",
description: "Wobbly human lines: marker strokes, doodles and imperfect warmth.",
category: "Handmade & Texture",
tags: ["hand-drawn", "doodle", "human"],
bg: "#FFFDF5", surface: "#FFFFFF", ink: "#2E2A26", muted: "#8A8178", accent: "#E4572E", accent2: "#2E86AB",
display: "Caveat, Kalam, Comic Sans MS, sans-serif",
body: "Karla, Nunito, sans-serif",
radius: "Wobbly: border-radius with uneven values (e.g. 12px 14px 11px 15px); circled highlights",
border: "Marker strokes: 2–3px uneven SVG underlines, circled emphasis, arrow doodles as dividers",
shadow: "Paper lift: soft 0 6px 18px warm-gray/15; marker highlights behind key words",
spacing: "Notebook rhythm: doodle margins, 24px card padding, 72–96px chapters, annotations everywhere",
aesthetic: "A whiteboard that shipped: wobbly dividers, hand-circled prices, arrow doodles pointing at features, one handwritten font for emphasis over a legible body face. Human, funny, and clear. For education, nonprofits, kids, and friendly SaaS.",
principles: ["Wobble everything once: dividers, frames, highlights — never twice the same", "One hand font for emphasis; legible face for paragraphs", "Arrows and circles are wayfinding, not decoration"],
layout: "Notebook flow: hero with circled promise, doodle-annotated features, testimonial margin-notes, FAQ in hand frames. Max-width 1100px.",
buttons: "Hand-framed buttons: wobbly borders, marker-fill hovers, arrow doodle into primary. Big and friendly.",
cards: "Sticky-note and index-card panels: slight rotations (±1.5deg), tape corners, marker titles.",
nav: "Notebook bar: doodle logo, hand-underlined links, circled CTA.",
imagery: "Doodles, diagrams, stick-figure explainers, annotated screenshots with marker circles.",
icons: "Doodle icons: wobbly stroke, round caps, inconsistent (charmingly) — one artist's set.",
texture: "Paper grain 5%, marker bleed on highlights, tape, coffee ring (one, classic).",
motion: "Draw-on: SVG stroke animations on scroll, doodle wiggles on hover, note rotations settle with spring.",
avoid: ["Multiple hand fonts competing", "Perfect geometric shapes (wobble them)", "Handwritten body copy (legibility!)", "Corporate stock photography", "Over-doodling until content drowns"],
},
{
slug: "illustration-led",
name: "Illustration-Led",
description: "Drawn worlds first: spot illustrations, scenes and characters carrying pages.",
category: "Handmade & Texture",
tags: ["illustration", "characters", "storybook"],
bg: "#FFF9F0", surface: "#FFFFFF", ink: "#2B2620", muted: "#8A8178", accent: "#E4572E", accent2: "#2E86AB",
display: "Fraunces, Georgia, serif",
body: "Karla, Inter, sans-serif",
radius: "16–24px storybook panels; blob masks for scenes",
border: "Soft ink outlines on illustrated panels (1.5–2px); chapter-rule ornaments",
shadow: "Storybook lift: 0 12px 32px warm/12; illustrated drop shadows inside scenes",
spacing: "Storybook pacing: scene chapters 96–120px, spot illustrations in margins, 28px panel padding",
aesthetic: "A picture book for grown-up products: hero scenes, spot illustrations per feature, recurring characters, chapter ornaments. One consistent illustration style throughout — mixed styles kill the magic. For education, fintech, health, and onboarding.",
principles: ["One illustration style, one palette — consistency is the magic", "Scenes for heroes, spots for features, ornaments for rhythm", "Characters recur: mascots build attachment across pages"],
layout: "Storybook scroll: illustrated hero scene, alternating scene/feature chapters, character glossary, happy-ending CTA. Max-width 1200px.",
buttons: "Storybook buttons: warm fills, rounded 12px, friendly 16px labels; hover bounces gently.",
cards: "Scene panels: illustrated headers, warm borders, 20px radius; empty states are mini-illustrations.",
nav: "Friendly bar with illustrated mark, rounded links, sunny CTA.",
imagery: "Custom illustration system (the whole investment): scenes, spots, characters, ornaments. No stock, ever.",
icons: "Illustrated icon set matching the scenes: same stroke, same palette, same humor.",
texture: "Paper grain 4%, watercolor washes in scenes, pencil-line details.",
motion: "Living pictures: gentle idle loops (blink, bob, 4–6s), scroll-triggered scene builds, character reactions on CTA hover.",
avoid: ["Stock photography beside custom illustration", "Mixed illustration styles", "Tiny illustrations that read as icons", "Generic corporate Memphis (see corporate-memphis for that)", "Illustration without function — every scene should explain"],
},
{
slug: "corporate-memphis",
name: "Corporate Memphis",
description: "Flat friendly vector people: big tech's geometric humanism, polished.",
category: "Handmade & Texture",
tags: ["flat", "big-tech", "friendly"],
bg: "#FFFFFF", surface: "#F4F6FB", ink: "#1E2A3B", muted: "#64748B", accent: "#4D7CFE", accent2: "#FF6B9D",
display: "Inter, Plus Jakarta Sans, sans-serif",
body: "Inter, system-ui, sans-serif",
radius: "16px cards, pill buttons, blob image masks",
border: "None or hairline slate-200; color-block shapes instead of lines",
shadow: "Friendly-soft: 0 8px 28px rgba(30,42,59,0.08); blob grounds with no shadow",
spacing: "SaaS-friendly: 88–110px sections, alternating white/tint grounds, 28px card padding",
aesthetic: "Big-tech humanism, executed with taste: flat geometric people with elongated limbs, purple-blue-coral palette, blob grounds, airy grids. Ubiquitous because it tests well — differentiate through copy and motion. For SaaS, fintech, HR, and health products.",
principles: ["People in every hero: joy, teamwork, thumbs-up energy", "Purple-blue-coral palette; skin tones diverse and flat", "Blobs and dots organize; grids convert"],
layout: "Friendly funnel: hero (copy + people scene), logos, feature grid with spots, metric band, testimonial, CTA with waving group. Max-width 1200px.",
buttons: "Blue pills, white 15px semibold; hover lifts; secondary white-bordered. Rounded and reassuring.",
cards: "White 16px cards with spot illustrations, icon chips, 2-line bodies; soft shadows.",
nav: "Clean white bar, friendly links, blue CTA pill. Announcement bar in tint.",
imagery: "Flat vector people scenes (consistent library!), blob-masked photos of real customers for proof.",
icons: "Rounded duotone chips with white glyphs; consistent geometric set.",
texture: "Flat tints, dot grids, blob shapes — minimal texture, maximum friendliness.",
motion: "Gentle floats (5s), wave loops on characters, 250ms lifts. Approachable springs.",
avoid: ["Mixing illustration libraries", "Dark moody sections (this style lives in daylight)", "Cynical copy (commit to earnest)", "Photorealistic heroes", "Over-differentiation that breaks tested patterns"],
},
{
slug: "organic-biophilic",
name: "Organic / Biophilic",
description: "Nature-shaped interfaces: leaf curves, earth tones and breathing whitespace.",
category: "Organic & Calm",
tags: ["organic", "nature", "biophilic"],
bg: "#F6F4EC", surface: "#FFFFFF", ink: "#2E3A2F", muted: "#5F7261", accent: "#3E7C4F", accent2: "#C2703D",
display: "Fraunces, Georgia, serif",
body: "Inter, Karla, sans-serif",
radius: "Leaf shapes: asymmetric (4px 28px), arches, full blobs for imagery",
border: "Growing lines: 1–2px moss keylines; vine dividers (SVG); deckled leaf edges",
shadow: "Forest-floor soft: 0 12px 32px green-black/10; sun-dapple highlights",
spacing: "Grove rhythm: breathing 96–130px sections, arched image rooms, 28px panel padding",
aesthetic: "A greenhouse you can click: arched imagery, moss and clay palette, leaf-curve dividers, serif headlines about growth, dappled light. Calm and alive. For wellness, food, travel, sustainability, and hospitality.",
principles: ["Arches and leaf curves beat rectangles", "Earth palette: moss, clay, bark, cream — sky blue sparingly", "Light dapples: gradients feel like sun through leaves"],
layout: "Garden walk: arched hero image, grove feature rows, sunlit testimonial glade, rooted footer. Max-width 1240px.",
buttons: "Seed buttons: moss fills with cream labels, arched 16px radius; hover grows (scale 1.03) like time-lapse.",
cards: "Terrarium panels: arched image tops, cream bodies, moss keylines, growth-stat rows.",
nav: "Vine bar: leaf mark, earthy links, moss CTA pill. Sun-warm on scroll.",
imagery: "Botanical photography, arched portraits, macro leaves, morning light. Green-graded warmth.",
icons: "Leaf, sprout, sun, drop glyphs — organic strokes, round caps.",
texture: "Leaf veins, bark, linen, dappled-light gradients at 8–15%.",
motion: "Growing: sprout-up reveals, leaf-sway idles (6s), sun-drift gradients. Photosynthesis pacing — slow.",
avoid: ["Sharp corporate rectangles", "Neon or synthetic hues", "Dense packed layouts (let it breathe)", "Fast snappy motion", "Plastic or chrome textures"],
},
{
slug: "eco-sustainable",
name: "Eco / Sustainable",
description: "Planet-first design: recycled textures, impact counters and honest green.",
category: "Organic & Calm",
tags: ["eco", "sustainability", "impact"],
bg: "#F4F5EF", surface: "#FFFFFF", ink: "#22301F", muted: "#556B53", accent: "#2E7D32", accent2: "#F2B705",
display: "Fraunces, Inter Tight, sans-serif",
body: "Inter, Karla, sans-serif",
radius: "12–16px honest rounding; stamp badges round",
border: "Recycled edges: 1–2px kraft keylines; stamp frames; dashed impact-ticket dividers",
shadow: "Honest-soft: 0 8px 24px green-black/08; stamp ink offsets on badges",
spacing: "Impact rhythm: counter bands, 88–110px sections, 24px card padding, receipt-style footprints",
aesthetic: "Patagonia-grade honesty: kraft and cream grounds, forest-green ink, impact counters (trees planted, CO₂ saved), certification stamps, recycled-paper texture. Claims backed by receipts. For sustainable brands, food, fashion resale, and energy.",
principles: ["Show receipts: counters, certificates, supply-chain maps", "Kraft + forest + sun-yellow; green must be earned, not washed", "Stamps and tickets make virtue tangible"],
layout: "Impact funnel: mission hero with counter, proof bands (certs), product with footprint labels, journal, pledge CTA. Max-width 1200px.",
buttons: "Forest fills with cream labels; sun-yellow for joy moments; stamped hover (ink edge appears).",
cards: "Footprint cards: product + CO₂/origin tickets with dashed tear edges; cert stamp rows.",
nav: "Mission bar: leaf mark, impact counter pill, shop/learn links, pledge CTA.",
imagery: "Hands in soil, forests, factories with daylight, package-unboxing in kraft. Honest, unretouched warmth.",
icons: "Leaf, recycle, sun, drop, footprint glyphs — honest line style.",
texture: "Recycled kraft grain 8–12%, seed-paper flecks, stamp ink, twine dividers.",
motion: "Counting-up impact numbers, growing progress rings, gentle leaf drift. Earnest 300ms ease-outs.",
avoid: ["Greenwashing gradients without proof", "Slick luxury finishes", "Hiding supply-chain info", "Vague eco-claims (quantify!)", "Plastic-gloss textures"],
},
{
slug: "japandi",
name: "Japandi",
description: "Japanese-Scandi fusion: warm minimalism, low lines and crafted calm.",
category: "Organic & Calm",
tags: ["japandi", "calm", "crafted"],
bg: "#F5F1E9", surface: "#FFFDF8", ink: "#33302A", muted: "#6B655A", accent: "#8C5A2B", accent2: "#4A5D4E",
display: "Cormorant Garamond, Inter Tight, serif",
body: "Inter, Hiragino Sans, sans-serif",
radius: "6–12px soft crafted rounding; low plinth-like panels",
border: "Joinery lines: 1px warm-gray frames; shoji-grid dividers; low black plinth bars",
shadow: "Tea-room soft: 0 10px 30px warm/10; low-grounded weight, never floating",
spacing: "Grounded calm: low horizontal compositions, 100–130px breathing sections, 28px panel padding",
aesthetic: "Kyoto meets Copenhagen: low oak forms, bouclé and clay, shoji-grid rhythms, single stems in vases. Minimalism with warmth and craft. For furniture, interiors, ceramics, and slow-living brands.",
principles: ["Low and horizontal: compositions hug the ground", "Oak, clay, stone, bouclé — materials lead, color follows", "One stem, one stone: styling restraint as luxury"],
layout: "Gallery-calm: low hero compositions, material chapters, maker stories, room-set closers. Max-width 1240px.",
buttons: "Clay fills with cream labels; quiet bordered secondaries; 12px radius, 48px targets. Hover warms color.",
cards: "Material cards: oak/clay grounds, product centered low, generous air above. Soft shadows.",
nav: "Calm bar: wordmark, room/maker links, cart with count. Warm blur on scroll.",
imagery: "Low styled interiors, ceramic macro, daylight shadows, single-stem florals. Warm desaturated grade.",
icons: "Thin crafted glyphs: joinery marks, material swatches as navigation aids.",
texture: "Oak grain, bouclé, clay, linen at 6–12% — touchable matte richness.",
motion: "Slow craft: 400ms warm fades, daylight-drift gradients, product turns unhurried.",
avoid: ["Tall dense layouts", "Cold blue-grays", "Glossy or chrome finishes", "Cluttered styling (one stem!)", "Fast bouncy motion"],
},
{
slug: "wabi-sabi",
name: "Wabi-Sabi",
description: "Perfect imperfection: asymmetry, cracks and weathered beauty, honored.",
category: "Organic & Calm",
tags: ["wabi-sabi", "imperfect", "serene"],
bg: "#EFE9DD", surface: "#F7F3E9", ink: "#3A352C", muted: "#8A8178", accent: "#9C2B2E", accent2: "#4A5D4E",
display: "Cormorant Garamond, Yu Mincho, serif",
body: "EB Garamond, Georgia, serif",
radius: "Irregular: hand-torn edges, 2–6px uneven, kintsugi gold seams as dividers",
border: "Weathered edges: torn deckles, kintsugi gold crack lines, ash-gray hairlines",
shadow: "Faint and warm: 0 4px 16px warm/08; gold seams glow faintly",
spacing: "Contemplative: vast ma pauses (140px+), off-center placements, single-object views",
aesthetic: "Beauty in the broken: cracked bowls mended with gold, weathered wood, uneven edges, moss in the margins. Asymmetric, impermanent, incomplete — and complete because of it. For tea, ceramics, slow travel, and contemplative brands.",
principles: ["Honor the crack: kintsugi seams are features", "Asymmetry and incompleteness feel alive", "Weathered materials over new ones, always"],
layout: "Tea-garden sequence: single-object views, gold-seam dividers, poem-like captions, quiet maker colophon. Max-width 1000px.",
buttons: "Quiet ink rectangles with gold-seam hover; tea-order CTAs ceremonial and few.",
cards: "Object plates: weathered grounds, gold seam accents, wabi captions. No grids of plenty.",
nav: "Whisper bar: mark, two links, cart. Fades to a gold hairline on scroll.",
imagery: "Cracked ceramics, moss gardens, weathered wood, morning mist. Desaturated warmth, soft focus edges.",
icons: "Enso circles, crack lines, stone stacks — minimal Zen glyphs.",
texture: "Clay, ash, moss, gold dust at 6–12%. Imperfection rendered faithfully.",
motion: "Stillness: 600ms breath fades, drifting mist, gold-seam draws. Silence between moves.",
avoid: ["Symmetry and polish", "Bright new-looking materials", "Dense grids", "Fast motion or urgency", "More than one gold seam per view"],
},
];
