export const stylesB = [
{
slug: "maximalism",
name: "Maximalism",
description: "More is more: layered color, pattern and ornament in joyful overload.",
category: "Maximalist",
tags: ["maximalist", "layered", "ornate"],
bg: "#1E1B2E", surface: "#2A2540", ink: "#F5EFE0", muted: "#A89FC0", accent: "#FF4FA3", accent2: "#FFD802",
display: "Playfair Display, Georgia, serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "12–20px lush rounding; arches and scallops welcome",
border: "Ornamental borders: double gold rules, patterned trims, 2px contrasting keylines around layered panels",
shadow: "Rich and deep: 0 20px 60px rgba(0,0,0,0.45), gold glows 0 0 40px rgba(255,216,2,0.25)",
spacing: "Abundant and layered: overlapping bands, 24px panel padding, 72–100px sections, collaged margins",
aesthetic: "Maximalism celebrates abundance: jewel tones, damask and animal prints, gallery walls of mismatched frames, tassels rendered in CSS. Every surface holds something — pattern on pattern, serif on serif. It suits hospitality, beauty, and brands whose promise is richness itself. Restraint would be a broken promise.",
principles: ["Layer relentlessly: pattern over color over texture over type", "Jewel tones and metallics; neutrals only as breathing seams", "Ornament is content — trim, fringe, and frames carry meaning"],
layout: "Collaged abundance: overlapping bands and frames, gallery-wall grids, full-bleed patterned chapters. Max-width 1280px but edges constantly bleed.",
buttons: "Jeweled buttons: gradient or velvet fills, gold 2px borders, serif labels with letterspacing. Hover glows gold; press sinks into pile.",
cards: "Layered panels: patterned grounds, gold keylines, cameo medallions, ribbon corners. Shadows deep and warm.",
nav: "Ornate bar: monogram crest, serif links with gold hover underlines, jeweled CTA. Patterned trim top and bottom.",
imagery: "Opulent photography: velvet, marble, florals, candlelight, peacocks. Gilt frames (CSS borders) on every image, mismatched deliberately.",
icons: "Ornamental glyphs: filigree dividers, crest-like marks, gold thin-stroke icons. Emoji-scale richness in moderation.",
texture: "Damask, velvet noise, marble veining, animal print at 10–25% — texture is a headline act, not a background.",
motion: "Lush 400–600ms ease-in-out; slow Ken Burns on imagery; shimmer sweeps on gold. Everything moves like heavy fabric.",
avoid: ["Whitespace as a feature — fill it with intent", "Flat grays or corporate blue", "Single typeface throughout", "Sharp brutalist geometry", "Fast snappy micro-interactions"],
},
{
slug: "playful-maximalism",
name: "Playful Maximalism",
description: "Confetti interfaces: stickers, squiggles and candy color at full volume.",
category: "Maximalist",
tags: ["playful", "confetti", "gen-z"],
bg: "#FFF3E4", surface: "#FFFFFF", ink: "#232323", muted: "#8A8177", accent: "#FF4FA3", accent2: "#00C2FF",
display: "Fredoka, Baloo 2, Comic Sans MS, sans-serif",
body: "Nunito, Quicksand, sans-serif",
radius: "16–24px blob rounding; stickers fully pill; wavy dividers",
border: "Chunky 2–3px ink outlines on stickers; rainbow keylines; scalloped and zigzag edges",
shadow: "Bouncy hard shadows: 5px 5px 0 ink; pastel glow shadows on candy grounds",
spacing: "Festival packing: stickers overlap by 12–20px, 20px card padding, 56–80px sections, confetti margins",
aesthetic: "A birthday party that never ends: confetti, googly stickers, squiggle underlines, candy gradients, and three mascots minimum. Every scroll reveals a new surprise. Built for Gen-Z brands, games, snacks, and anyone selling joy. The grid exists — it's just wearing a costume.",
principles: ["Surprise per scroll: never let two viewports feel alike", "Candy color + ink outlines = joy with structure", "Motion is slapstick: wobble, boing, confetti burst"],
layout: "Sticker-bomb stacks: centered bouncy columns with scattered overlapping decals; wavy dividers; alternating candy grounds. Max-width 1120px.",
buttons: "Candy pills with ink borders and hard shadows; labels bold rounded. Hover wobbles; click bursts tiny confetti (CSS/canvas).",
cards: "Sticker cards: white, ink-bordered, tilted ±2deg, with washi-tape corners and badge overlaps.",
nav: "Cream bar with sticker logo, pill links in rotating candy fills, and a bouncing CTA.",
imagery: "Mascots, 3D candy renders, emoji-scale illustrations, polaroid-framed photos with doodle captions.",
icons: "Chunky filled sticker icons with white borders and ink outlines; wildly expressive, strictly one set.",
texture: "Confetti, polka dots, squiggles, checkerboards, terrycloth noise — loud at 15–30%.",
motion: "Slapstick springs: 250–400ms cubic-bezier(0.34,1.56,0.64,1); idle float on mascots; confetti on conversion actions.",
avoid: ["Muted palettes or corporate restraint", "Hairlines and subtle anything", "Long gray paragraphs — break into sticker bites", "Slow fades; everything should boing", "More than a glance of whitespace unfilled"],
},
{
slug: "editorial-maximalism",
name: "Editorial Maximalism",
description: "Magazine excess: colliding headlines, pull quotes and image pile-ups.",
category: "Maximalist",
tags: ["editorial", "collage", "print"],
bg: "#F6F1E7", surface: "#FFFFFF", ink: "#141414", muted: "#6E675C", accent: "#C81E1E", accent2: "#0F4C81",
display: "Playfair Display, Didot, Georgia, serif",
body: "Georgia, Source Serif 4, serif",
radius: "0–4px print-sharp; torn edges via clip-path welcome",
border: "Print rules: thick-thin-thick masthead rules, 2px story frames, red kickers with rules",
shadow: "Print-flat: none, except hard offset drop-shadows (8px 8px 0 ink) on pull-quote blocks",
spacing: "Newsstand density: overlapping kickers, 16px story rhythm, giant 72–140px headlines, full-bleed breaks",
aesthetic: "A fashion issue exploded across the screen: colliding serif headlines, oversized pull quotes, image pile-ups, red kickers, and footnotes as decoration. High-low mixing — couture imagery beside raw rules. For publishers and brands with editorial nerve.",
principles: ["Headlines collide: overlap, scale-clash, and interrupt the grid", "Print devices at poster scale: kickers, folios, pull quotes, captions", "Red + ink + paper; photography supplies the rest"],
layout: "Magazine spread logic: full-bleed openers, multi-column wells, breakout pull quotes spanning gutters, folio footers. Max-width 1400px.",
buttons: "Ink bars with white serif caps labels; red hover flood. Bookmark-style ribbons for saves.",
cards: "Story packages: kicker + headline + lede + byline + rule stacks; image-led features break the grid deliberately.",
nav: "Masthead with issue number, giant serif wordmark, section tabs in small caps; red breaking strip optional.",
imagery: "Fashion-grade photography, full-bleed openers, contact-sheet grids, captioned figures. Grayscale-to-color hover reveals.",
icons: "Typographic ornaments and section numerals; star ratings and arrows in serif style.",
texture: "Newsprint grain 5–8%, halftone portraits, registration-mark motifs in margins.",
motion: "Editorial reveals: clip-path headline wipes, image scale-settle 600ms, footnote smooth-scroll. No bounce.",
avoid: ["Uniform card grids and SaaS chrome", "Sans-serif headlines", "Timid 40px headlines", "Stock-photo smiles", "Infinite scroll without issue breaks"],
},
{
slug: "psychedelic-maximalism",
name: "Psychedelic Maximalism",
description: "Liquid swirls, melting type and kaleidoscopic color in full trip.",
category: "Maximalist",
tags: ["psychedelic", "trippy", "fluid"],
bg: "#12041F", surface: "#1E0B33", ink: "#F7ECFF", muted: "#A98FC7", accent: "#FF4FD8", accent2: "#00E5CC",
display: "Shrikhand, Bungee, Impact, sans-serif",
body: "Outfit, Inter, sans-serif",
radius: "Organic blobs and waves; 24px+ or fully fluid border-radius (30% 70% 70% 30%)",
border: "Iridescent keylines: 2px gradient borders via border-image; glow outlines over flat fills",
shadow: "Neon blooms: 0 0 30px magenta, 0 0 60px violet; layered colored glows, zero black shadows",
spacing: "Flowing and overlapping: sections melt into each other with SVG wave dividers; 64–96px movements",
aesthetic: "A 1967 concert poster fed through a GPU: liquid gradients, melting display type, kaleidoscope symmetry, and chrome bubbles floating over deep violet space. Built for music, festivals, cannabis, and nightlife brands. Legibility bends — but never fully breaks.",
principles: ["Color in motion: gradients always animated, never static", "Type melts: warp, outline, and layer display lettering", "Dark cosmic grounds make neon hues hallucinate"],
layout: "Seamless trip: wave-divided chapters on deep violet, mirrored/kaleidoscope hero compositions, floating bubble cards. Max-width 1280px.",
buttons: "Gooey pills with animated gradient fills and glow shadows; swirling hover states. Labels bold, often with glow.",
cards: "Glass-bubble panels over animated gradient fields; iridescent borders; floating with slow idle drift.",
nav: "Transparent over the trip; warped logo lettering; glowing pill links; melting CTA.",
imagery: "Liquid chrome, melting portraits, fractal flora, concert haze. Heavy gradient-map treatments unify everything.",
icons: "Trippy line icons with glow: mushrooms, eyes, waves, peace marks — metaphysical sticker set.",
texture: "Liquid marble, oil-slick gradients, grain + chromatic aberration on type, lens-dirt sparkles.",
motion: "Everything breathes: 6–12s gradient loops, 8s float cycles, melting hover warps. Reduced-motion shows a still poster.",
avoid: ["Corporate restraint or single-accent discipline", "Sharp grid visibility", "Static gradients", "Tiny timid type", "Light-mode-first thinking"],
},
{
slug: "typography-maximalism",
name: "Typography Maximalism",
description: "Type as image: wall-to-wall letterforms, kinetic headlines, zero chrome.",
category: "Maximalist",
tags: ["typography", "kinetic", "expressive"],
bg: "#0F0F0F", surface: "#161616", ink: "#F4F1EA", muted: "#8F8B82", accent: "#FF4D00", accent2: "#F4F1EA",
display: "Anton, Archivo Black, Impact, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–6px; type needs no rounding",
border: "Typographic rules: baseline grids visible, 2px ink rules between type movements, outlined-text strokes",
shadow: "Type shadows only: hard offset duplicates (4px 4px 0 accent), layered echo stacks on heroes",
spacing: "Type-driven: 100–200px display lines, tight -0.03em tracking, sections paced like chapters (96–140px)",
aesthetic: "The website is a poster that scrolls: viewport-filling condensed headlines, outlined echo lines, marquee tickers, and index-style meta in mono. Images are guests; letterforms are hosts. For type foundries, festivals, studios, and brands with something to shout.",
principles: ["Set headlines at 12–20vw and commit", "Mix filled, outlined, and italic treatments of one family", "Meta in mono, headlines in display — nothing in between"],
layout: "Poster stack: full-bleed type chapters, ticker dividers, index tables of contents, footer as colophon. Edges bleed constantly.",
buttons: "Type-buttons: giant underlined links or black bars with condensed caps; hover fills accent with instant swap.",
cards: "No cards — type blocks with rules. Schedules, lineups, and indexes ARE the content design.",
nav: "Minimal overlay: wordmark + menu toggle + ticket CTA; full-screen type menu on open.",
imagery: "Type-first: images masked inside letterforms or confined to breakout bands; duotone to match ink.",
icons: "Arrows, asterisks, and numerals as ornaments (→ ↗ * №). No pictogram sets.",
texture: "Paper grain on dark, misregistration splits, photocopy noise on display type.",
motion: "Kinetic type: scroll-scrubbed headlines, marquee tickers, char-by-char reveals. 60fps transforms only.",
avoid: ["Body-copy layouts and card grids", "Multiple font families competing", "Small polite headlines", "Decorative illustration over type", "Centering long-form text"],
},
{
slug: "color-maximalism",
name: "Color Maximalism",
description: "Unapologetic saturation: full-spectrum fields, clashing grounds, dopamine UX.",
category: "Maximalist",
tags: ["colorful", "saturated", "dopamine"],
bg: "#FFD802", surface: "#FFFFFF", ink: "#161616", muted: "#6B6257", accent: "#FF2E88", accent2: "#2B4EFF",
display: "Archivo Black, Inter Tight, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "14–20px juicy rounding on white content cards",
border: "Thick ink or white keylines (3px) separating color fields; rainbow divider strips",
shadow: "Saturated color shadows: 8px 8px 0 rgba(22,22,22,1) on cards; colored glows matching grounds",
spacing: "High-energy rhythm: full-bleed color chapters every 64–88px, white cards floating with 24px padding",
aesthetic: "Dopamine dressing for interfaces: every section a saturated field — taxi yellow, hot pink, cobalt — with white content cards floating on top. Color carries the information architecture. For food, music, kids, fitness, and festival brands where energy IS the product.",
principles: ["One saturated ground per section; never repeat adjacently", "White cards float content above the noise", "Black keylines keep clashing hues from vibrating apart"],
layout: "Color-chapter scroll: full-bleed saturated bands, white rounded cards inside, rainbow rules between. Max-width 1200px content wells.",
buttons: "Ink-black buttons on color grounds (white text), or white buttons with ink text on dark grounds. Hover inverts with a pop.",
cards: "White juicy cards with 16px radius and hard ink shadows on saturated grounds; colored header chips.",
nav: "Ink bar with rainbow underline, or white bar over the hero ground; CTA in clashing accent.",
imagery: "High-saturation photography with boosted contrast; cut-out stickers; duotone overlays in section hues.",
icons: "Bold duotone icons: ink glyph on candy chip. Thick strokes, high energy.",
texture: "Halftone dots, diagonal candy stripes, confetti at 10–20% over color grounds.",
motion: "Snappy color-wipe transitions between chapters; hover pops 150ms; marquee rainbow tickers.",
avoid: ["White/gray section grounds", "Muted or pastel-only palettes", "Thin borders and soft gray shadows", "Long text directly on saturated grounds (use cards)", "Autumnal or corporate color stories"],
},
{
slug: "digital-maximalism",
name: "Digital Maximalism",
description: " Internet-native excess: gradients, glass, stickers, cursors and widgets everywhere.",
category: "Maximalist",
tags: ["y2k", "stickers", "internet"],
bg: "#0B0B18", surface: "#15152B", ink: "#F2F0FF", muted: "#8E8AB0", accent: "#00E5FF", accent2: "#FF4FD8",
display: "Unbounded, Bungee, Impact, sans-serif",
body: "Outfit, Inter, sans-serif",
radius: "16–24px bubbly; pills for chips and buttons",
border: "Glowing 1–2px gradient borders; sticker white keylines; scanline overlays",
shadow: "Neon stack: 0 0 24px cyan + 0 0 60px magenta at low alpha; hard sticker drop shadows on decals",
spacing: "Widget-dense: overlapping floating panels, 16–20px card padding, 64–88px sections, always something blinking",
aesthetic: "A 2005 desktop, a Discord server, and a rave flyer merged: gradient meshes, glass widgets, sticker decals, custom cursors, marquees, and a live clock somewhere. Built for internet culture brands, creator tools, and games. Irony and sincerity coexist.",
principles: ["Widgets over whitespace: clocks, players, chats, counters", "Gradients + glass + stickers in every viewport", "Nostalgia is a material: starfields, sparkles, pixel fonts as accents"],
layout: "Desktop collage: floating widget panels over gradient-mesh space; sticker constellations; chat-style content blocks. Max-width 1280px.",
buttons: "Glossy gradient pills with glow; hover intensifies glow and scales 1.04. Download-style beveled buttons as accents.",
cards: "Glass widgets with gradient borders and glow; sticker cards with white keylines; mini-player and chat-bubble variants.",
nav: "Floating pill nav with glass blur, sparkle logo, status dots, and a neon CTA.",
imagery: "Sparkle GIFs energy in still form: chrome 3D, pixel art, screencap collages, webcam-style portraits with stickers.",
icons: "Mixed-era set: pixel icons, glossy orbs, emoji-scale glyphs — unified by glow and white keylines.",
texture: "Starfields, grid floors, scanlines, sparkle overlays, gradient mesh — all at once, balanced by dark grounds.",
motion: "Constant gentle life: blinking status, floating stickers, marquee tickers, gradient drift. Respect reduced-motion with a calm snapshot.",
avoid: ["Minimal layouts or large empty areas", "Single typeface systems", "Flat matte surfaces everywhere", "Corporate blue-gray palettes", "Hiding the seams — show the collage"],
},
{
slug: "chaos-design",
name: "Chaos Design",
description: "Controlled demolition: overlapping, rotated, colliding elements that still convert.",
category: "Maximalist",
tags: ["chaotic", "experimental", "bold"],
bg: "#F4EFE6", surface: "#FFFFFF", ink: "#141414", muted: "#6E675C", accent: "#FF3D00", accent2: "#1E40FF",
display: "Archivo Black, Arial Black, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "Mixed deliberately: sharp frames + occasional blob stickers",
border: "Colliding weights: 3px frames, taped edges, torn clip-paths, highlighter strokes",
shadow: "Mixed: hard offsets on frames, washi-tape translucency, marker highlights behind type",
spacing: "Collision choreography: overlaps of 16–40px, rotations ±3deg, sections crashing into each other",
aesthetic: "A beautiful accident, rehearsed: rotated polaroids, taped type, colliding grids, marker highlights — composed with a strict underlying alignment so it converts. For streetwear, agencies, festivals, and launches that need controlled demolition energy.",
principles: ["Collide with a plan: one alignment axis survives the chaos", "Tape, markers, and torn edges are the material palette", "Every collision must survive 360px mobile without breaking"],
layout: "Composed collisions: overlapping framed blocks on paper ground, rotated ±3deg, marker-highlight headlines. Max-width 1280px, edges bleed.",
buttons: "Sticker buttons: rotated, taped corners, hard shadows; hover straightens with a snap.",
cards: "Overlapping framed panels with tape strips, marker annotations, and sticker badges breaking edges.",
nav: "Taped-together bar: logo sticker, marker-highlight links, CTA with hard shadow. Slight rotation on the whole bar (-0.5deg).",
imagery: "Polaroids with tape, torn magazine cuts, marker-annotated screenshots, highlighter-circled details.",
icons: "Hand-circled arrows, stars, tape flags — annotation-graphics as iconography.",
texture: "Paper grain, tape translucency, marker strokes, torn edges, coffee-ring optional (one, tasteful).",
motion: "Snap physics: rotations settle with spring overshoot; hovers straighten; entrances drop in with a thud (300ms spring).",
avoid: ["Actual randomness — chaos must be art-directed", "Breaking tap targets or text contrast", "Chaos in checkout/finance flows", "More than ±3deg rotation on text blocks", "Forgetting the mobile stacking order"],
},
{
slug: "luxury-maximalism",
name: "Luxury Maximalism",
description: "Baroque digital opulence: gold leaf, deep velvet and jewel-box density.",
category: "Maximalist",
tags: ["luxury", "baroque", "ornate"],
bg: "#100C08", surface: "#1C1510", ink: "#EFE3C8", muted: "#9A8B6F", accent: "#D4AF37", accent2: "#7A1E2B",
display: "Cormorant Garamond, Playfair Display, serif",
body: "EB Garamond, Georgia, serif",
radius: "Arches and ovals; cartouches; 0px on framed certificates",
border: "Gold filigree: double rules, corner flourishes, guilloche patterns via SVG; 1–2px gold keylines",
shadow: "Candlelight depth: 0 24px 80px rgba(0,0,0,0.6), gold inner glows on frames",
spacing: "Palatial: 120–180px ceremonial sections, dense jewel-box galleries, 32px framed padding",
aesthetic: "A Venetian palazzo rendered in pixels: black lacquer, gold leaf, oxblood velvet, malachite, and chandeliers of light. Dense with treasure — galleries, monograms, crests — yet composed with museum precision. For haute brands, hotels, spirits, and jewels.",
principles: ["Gold is architecture: frames, rules, and flourishes — never body fills", "Dark lacquer grounds; light appears as candlelight, not daylight", "Density with hierarchy: treasure rooms need a docent (typographic order)"],
layout: "Palatial sequence: grand foyer hero, treasure-room galleries, certificate chapters, crest footer. Centered axis with flanking ornament.",
buttons: "Gold cartouches: 1px gold border, tracked caps serif labels, dark fill; hover fills gold with black text over 500ms.",
cards: "Jewel boxes: dark lacquer panels, gold filigree frames, cameo imagery, ribbon seals.",
nav: "Crest bar: centered monogram, hairline gold rules, tracked serif links, member CTA in cartouche.",
imagery: "Candlelit product, marble halls, velvet macro, gold detail. Deep blacks, warm speculars, slow drift.",
icons: "Engraved thin-line icons in gold; crests, keys, laurel marks; Roman numerals.",
texture: "Gold leaf noise, velvet pile, marble, damask at 8–15% — richness with restraint in opacity.",
motion: "Ceremonial slowness: 700–1000ms reveals, chandelier shimmer, curtain wipes between chapters.",
avoid: ["Bright modern color or neon", "Rounded SaaS geometry", "Sans-serif display type", "Fast bouncy motion", "White backgrounds anywhere"],
},
{
slug: "graphic-maximalism",
name: "Graphic Maximalism",
description: "Poster-wall energy: bold shapes, duotones and oversized graphics edge to edge.",
category: "Maximalist",
tags: ["graphic", "poster", "bold"],
bg: "#F5F2EA", surface: "#FFFFFF", ink: "#101010", muted: "#6E675C", accent: "#E30613", accent2: "#0B3D91",
display: "Archivo Black, Anton, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–10px; sharp frames, rounded stickers as accents",
border: "Poster frames: 3px ink borders, color-block keylines, starburst badges",
shadow: "Poster-shop: hard 6px offsets on feature blocks; print misregistration on display type",
spacing: "Wall rhythm: full-bleed graphic chapters 72–100px, overlapping headline/image collisions, ticker seams",
aesthetic: "A gallery wall of gig posters that you scroll through: huge vector graphics, duotone photos, starbursts, and condensed headlines colliding edge to edge. Vector-first, ink-heavy, screen-printed. For sports, music, events, and challenger brands.",
principles: ["Graphics lead, text follows — every section needs a visual punch", "Duotone + ink + one spot color unifies any imagery", "Bleed everything: posters have no margins"],
layout: "Poster wall: full-bleed graphic chapters alternating with ink-black set pieces; overlapping type/image collisions. Max-width 1400px.",
buttons: "Poster bars: full-width ink or red blocks with condensed caps; hover misregisters (offset echo).",
cards: "Gig-poster panels: duotone image, huge condensed title, date strip, starburst badge. Hard borders, hard shadows.",
nav: "Showbill bar: black with condensed links, red date/CTA block, ticker below for tour dates.",
imagery: "Vector illustrations, duotone photography, halftone textures, screen-print grain. High contrast always.",
icons: "Poster devices: stars, lightning bolts, ticket stubs, arrows — thick and few.",
texture: "Screen-print grain 8–12%, halftones, misregistration offsets, paper tooth on light grounds.",
motion: "Gig energy: marquee tickers, poster-slam entrances (scale 1.04→1, 250ms), hover misregistration shifts.",
avoid: ["Delicate hairlines or soft shadows", "Muted corporate palettes", "Polite centered layouts", "Photography without duotone treatment", "More than two spot colors plus ink"],
},
{
slug: "editorial-magazine",
name: "Editorial / Magazine",
description: "Magazine-inspired layouts driven by expressive typography and imagery.",
category: "Editorial & Print",
tags: ["editorial", "magazine", "typography"],
bg: "#FFFFFF", surface: "#F7F4EE", ink: "#191817", muted: "#77716A", accent: "#B3001B", accent2: "#191817",
display: "Playfair Display, Georgia, serif",
body: "Source Serif 4, Georgia, serif",
radius: "0–3px print sharp",
border: "Magazine rules: masthead double rules, column hairlines, captioned figure frames",
shadow: "None — ink on paper",
spacing: "Spread rhythm: 72–110px features, 24px baseline grid, 65ch measure, pull quotes breaking columns",
aesthetic: "A glossy monthly rendered interactive: cover-style openers, department grids, pull quotes, folios, and captioned figures. Serif display with italic accents, red kickers, generous photography. Authority through editing — every page feels art-directed.",
principles: ["Art-direct every scroll: alternate openers, wells, and breakouts", "Pull quotes and captions are design elements, not afterthoughts", "Departments (recurring grids) create ritual and return visits"],
layout: "Issue architecture: cover opener, TOC index, feature wells, department grids, back-page sign-off. Max-width 1240px with full-bleed openers.",
buttons: "Subscribe bars (ink fill, white serif caps), text-link reads, bookmark ribbons. Hover floods red.",
cards: "Story packages with kicker/headline/dek/byline; cover tiles with issue-style typography; no floating shadows.",
nav: "Masthead: date + issue, centered serif wordmark, double rule, department links in small caps.",
imagery: "Commissioned-feel photography: portraits, reportage, still life. Full-bleed openers, captioned figures, credit lines.",
icons: "Minimal: section numerals, arrows, save ribbons. Ornaments (❦) as dividers.",
texture: "Coated-paper flat with 3% grain; cover gloss via subtle top-light gradient on openers only.",
motion: "Page-turn calm: 250ms fades, cover Ken Burns (slow), smooth anchor scroll. Nothing bouncy.",
avoid: ["Card-shadow SaaS patterns", "Sans-serif display headlines", "Autoplay video openers", "Infinite scroll without issue structure", "Popups interrupting reading"],
},
{
slug: "newspaper",
name: "Newspaper",
description: "Broadsheet density: columns, headlines and datelines with ink urgency.",
category: "Editorial & Print",
tags: ["news", "broadsheet", "dense"],
bg: "#F7F4EC", surface: "#FFFFFF", ink: "#1A1A1A", muted: "#6E6A61", accent: "#A6192E", accent2: "#1A1A1A",
display: "Times New Roman, Times, serif",
body: "Georgia, Times New Roman, serif",
radius: "0px — newsprint has no rounding",
border: "Column rules (1px), section bars (3px black), dateline hairlines, boxed briefs",
shadow: "None — flat ink",
spacing: "Dense and disciplined: 3–5 columns at 1240px, 16–20px story rhythm, 56px headlines, folio headers",
aesthetic: "The front page as interface: nameplate, dateline, multi-column story wells, jump lines, weather-box widgets, and market tickers. Blackletter or Old Style nameplate, Times headlines, justified narrow columns. Trust through density and ritual.",
principles: ["Density signals authority — pack the front with signal", "Nameplate, dateline, folio: the ritual frame matters", "Justified columns, ragged nothing, rules everywhere"],
layout: "Broadsheet grid: nameplate band, lede story spanning 3 columns, secondary wells, sidebar briefs, agate-type data strips. Max-width 1280px.",
buttons: "Section bars and boxed links; subscribe as ink bar; e-edition toggle. Hover underlines, no fills jumping.",
cards: "Story boxes with 1px rules and 3px section bars; briefs in agate 12px; no shadows, no radius.",
nav: "Nameplate block: edition + date + weather; nav as section index in small caps with rules above/below.",
imagery: "Wire-service photography: hard crops, grayscale-leaning, cutlines with credits. Charts in ink with red accents.",
icons: "Weather glyphs, market arrows (▲▼), section numerals. Functional only.",
texture: "Newsprint grain 6–10%, slight show-through tint, halftone on photos.",
motion: "Telegraph minimal: ticker updates, edition timestamp, instant hovers. News doesn't dance.",
avoid: ["Rounded cards or soft shadows", "Sans-serif headlines", "Hero lifestyle photography", "Infinite scroll without sections", "Breaking-news theatrics on evergreen content"],
},
{
slug: "fashion-editorial",
name: "Fashion Editorial",
description: "Runway restraint: towering imagery, whisper typography and gallery pacing.",
category: "Editorial & Print",
tags: ["fashion", "luxury", "imagery"],
bg: "#F4F1EC", surface: "#FFFFFF", ink: "#1C1B1A", muted: "#8A847B", accent: "#1C1B1A", accent2: "#8C2F1B",
display: "Didot, Bodoni Moda, Cormorant Garamond, serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0px — fashion is sharp",
border: "Hairlines only: 1px ink rules, captioned figure lines, look-number ticks",
shadow: "None — imagery floats on space, not elevation",
spacing: "Runway pacing: full-viewport looks, 140px+ pauses, tiny tracked captions, 720px text measure",
aesthetic: "A runway show you scroll: towering full-bleed looks, whisper-quiet captions (Look 12 — wool, silk), enormous serif statements between movements. Negative space is the stylist. For fashion, beauty, jewelry, and anyone selling desire through imagery.",
principles: ["Imagery is 90% of the design — type whispers, photos shout", "One look per viewport; never collage the collection", "Captions are couture: tiny, tracked, precise"],
layout: "Runway sequence: full-viewport look chapters, serif intertitles, credit-block footers. Max-width none — bleed everything.",
buttons: "Ghost rectangles with 1px ink borders and tracked 11px labels; book-appointment fills black. Hover fills over 400ms.",
cards: "No cards — look plates: image, look number, caption, credit. E-commerce PDPs keep gallery purity with quiet buy rows.",
nav: "Floating minimal: monogram left, collection links center in tiny caps, bag/search right. Transparent over looks.",
imagery: "Full-bleed campaign photography, portrait orientation favored, muted grade, film grain. Backstage candids as secondary.",
icons: "Hairline bag/search/account glyphs, 1.5px stroke. Nothing filled, nothing colorful.",
texture: "Film grain 5–8%, paper flat on text chapters, silk gradients barely-there.",
motion: "Runway slow: 800ms crossfades between looks, gentle parallax (±4%), caption fade-ups. Never bouncy.",
avoid: ["Grids of small product tiles as the hero", "Loud color or sticker graphics", "Sans-serif display headlines", "Popups and urgency badges", "Fast carousels — pace like a show"],
},
{
slug: "poster-inspired",
name: "Poster-Inspired",
description: "Single-message impact: huge type, flat color and compositions that shout.",
category: "Editorial & Print",
tags: ["poster", "bold", "graphic"],
bg: "#E30613", surface: "#FFFFFF", ink: "#111111", muted: "#5C5A55", accent: "#111111", accent2: "#FFD802",
display: "Anton, Archivo Black, Impact, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–8px; posters are mostly sharp",
border: "Poster keylines: thick ink frames, color-block seams, starburst badges",
shadow: "Print-flat; hard offsets only on pasted sticker elements",
spacing: "Poster hierarchy: one dominant message at 15vw+, supporting lines small, generous margin frame (24–40px)",
aesthetic: "Every page a one-sheet: a single enormous message, flat spot colors, and a strict margin frame. Sub-pages are supporting posters, not dashboards. For events, campaigns, drops, and causes where one idea must travel.",
principles: ["One message per page at poster scale", "Flat spot color + ink; gradients are cowardice here", "A margin frame turns a webpage into a poster"],
layout: "One-sheet stacks: giant statement, flat color field, detail strip, footer colophon. Full-bleed with 24–40px safe frame.",
buttons: "Ticket-block buttons: ink bars with condensed caps; hover floods accent. Big, full-width on mobile.",
cards: "Showbill panels: date block + headline + venue + stub edge (perforation dashes). No soft shadows.",
nav: "Billhead: wordmark, date block, single CTA. Thin frame around the whole page optional but encouraged.",
imagery: "Silkscreen-style illustration, duotone photos, oversized numerals. Flat and graphic, never photorealistic heroes.",
icons: "Ticket, star, arrow, date-block devices — poster furniture, thick and few.",
texture: "Screen-print grain, halftone, paper tooth at 6–10%.",
motion: "Paste-up energy: slam-in entrances, marquee date tickers, hover misregistration. Fast and flat.",
avoid: ["Dashboards, tables, or dense UI on poster pages", "Photorealistic glossy heroes", "More than two spot colors", "Small polite headlines", "Rounded SaaS chrome"],
},
{
slug: "swiss-poster",
name: "Swiss Poster",
description: "Müller-Brockmann on screen: objective grids, red/black discipline, huge numerals.",
category: "Editorial & Print",
tags: ["swiss", "poster", "grid"],
bg: "#F2EFE9", surface: "#FFFFFF", ink: "#111111", muted: "#6E6A61", accent: "#E30613", accent2: "#0B3D91",
display: "Helvetica Neue, Helvetica, Arial, sans-serif",
body: "Helvetica Neue, Helvetica, Arial, sans-serif",
radius: "0px — always",
border: "Constructivist rules: 4px black bars, red blocks, hairline grid seams shown deliberately",
shadow: "None — ever",
spacing: "Mathematical: 8pt grid, 24px gutters, giant numerals (30vw), flush-left everything, vast active negative space",
aesthetic: "A 1957 Zurich concert poster, interactive: giant Akzidenz numerals, red circles and bars, black diagonal energy, all flush-left on warm paper. Cultural-program gravity for festivals, museums, and civic brands. Objectivity as beauty.",
principles: ["Numerals and geometry ARE the imagery", "Red + black + paper; blue only for historic tri-color moments", "Flush left, ragged right — the law"],
layout: "Poster-grid: giant numeral hero, program index rows with rules, diagonal red/black footer bands. Max-width 1400px, bleed encouraged.",
buttons: "Black bars with white Helvetica caps; red hover flood. Date-block variants for programs.",
cards: "Program rows: date numeral + title + venue + rule; no containing cards. Exhibition blocks with red header bars.",
nav: "Institutional header: crest, program links in caps, red season badge. Rules above and below.",
imagery: "Geometric abstraction preferred; photography (architecture, crowds) cropped hard to grid, often grayscale with red overlay.",
icons: "Circles, bars, arrows, numerals — constructivist primitives, not pictograms.",
texture: "Paper flat; letterpress impression on numerals; faint grid overlay in program sections.",
motion: "Precise: rule-draws on scroll, numeral count-ups, diagonal wipes. 200ms linear. No easing theatrics.",
avoid: ["Centered layouts", "Serif or script type", "Shadows, gradients, rounding", "Photography as the hero (geometry leads)", "More than three hues"],
},
{
slug: "bauhaus",
name: "Bauhaus",
description: "Geometric forms and primary colors composed with modernist rigor.",
category: "Editorial & Print",
tags: ["bauhaus", "geometric", "primary"],
bg: "#F2EDE3", surface: "#FFFFFF", ink: "#1A1A1A", muted: "#6E675C", accent: "#E30613", accent2: "#0B3D91",
display: "ITC Bauhaus, Poppins, Futura, sans-serif",
body: "Futura, Century Gothic, Inter, sans-serif",
radius: "Full circles and semicircles as shapes; 0px on text containers",
border: "Primary-color bars and rules; black 2–3px structural lines; no decorative borders on text",
shadow: "None — flat modernist planes",
spacing: "Compositional: asymmetric balance of circle/triangle/square masses; 64–96px movements; geometric margins",
aesthetic: "Dessau 1925 as a design system: red/yellow/blue primaries plus black, circle-triangle-square compositions, Futura-like geometric type, and diagonal energy balanced by grids. Playful but rigorous — every shape earns its place. For education, architecture, kids' brands with brains, and cultural institutions.",
principles: ["Circle, triangle, square: the only decoration allowed", "Primaries + black on warm paper; never pastels", "Asymmetric balance — weight, not symmetry"],
layout: "Compositional grids: geometric hero masses, diagonal dividers, program rows with shape bullets. Max-width 1280px.",
buttons: "Primary-color blocks (red/blue/yellow) with black or white geometric labels; black hover frames. Shapes: rectangles and pills from circle geometry.",
cards: "Shape-led panels: semicircle headers, primary mass blocks, black rules. Playful geometry, strict alignment.",
nav: "Bar with geometric mark (three shapes), Futura links, primary-color active states. Yellow highlight hovers.",
imagery: "Architecture, shadows, geometric still life, masks and theater. High contrast, primary overlays.",
icons: "Pure geometry: circle/triangle/square constructions, uniform 2px strokes. The set designs itself.",
texture: "Paper flat; letterpress grain 4%; blueprint grid in spec zones.",
motion: "Mechanical ballet: shapes rotate/slide on scroll (slow, linear), type reveals in steps. Mondrian-calm pacing.",
avoid: ["Pastels, gradients, or organic blobs", "Serif typefaces", "Shadows and elevation", "Symmetric corporate layouts", "More hues than the primaries + black"],
},
{
slug: "memphis",
name: "Memphis",
description: "Sottsass playfulness: squiggles, terrazzo and pastel geometry with attitude.",
category: "Editorial & Print",
tags: ["memphis", "playful", "80s"],
bg: "#FFF9F0", surface: "#FFFFFF", ink: "#222222", muted: "#7A736A", accent: "#00B3B3", accent2: "#FF4FA3",
display: "Archivo Black, Poppins, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "Playful mix: circles, squiggles, rounded blobs + sharp triangles",
border: "Graphic outlines: 2–3px ink on shapes; squiggle and dotted keylines as dividers",
shadow: "Flat floating: offset solid pastels (6px 6px 0 #FFD1DC) behind white cards — colorful hard shadows",
spacing: "Gallery-playful: scattered compositions with 24px card padding, 72–96px sections, shapes bleeding off edges",
aesthetic: "Milan 1981, digitized: terrazzo confetti, squiggle lines, pastel cones and toruses (CSS shapes), black-and-white striped bars. Sophisticated silliness for creative tools, fintech challengers, and lifestyle brands with a wink.",
principles: ["Scatter with intent: floating shapes on a strict grid", "Pastel grounds + ink outlines + one neon jolt", "Terrazzo and squiggles are signature — use both"],
layout: "Floating gallery: white content cards over cream with scattered CSS shapes; striped divider bars; dot-grid zones. Max-width 1200px.",
buttons: "Bold geometric buttons in teal/pink/yellow with ink text or white text; pastel hard shadows; hover swaps shape color.",
cards: "White cards with pastel offset shadows and ink borders; squiggle underlines on titles; shape badges.",
nav: "Cream bar with geometric mark, pill links, striped top border (signature), and a candy CTA.",
imagery: "3D pastel renders, terrazzo textures, still-life with squiggles, duotone portraits in Memphis hues.",
icons: "Geometric confetti icons: confetti dots, squiggles, triangles — 2px ink outlines on pastel chips.",
texture: "Terrazzo confetti, dotted grids, striped bars, squiggle fields at 10–20%.",
motion: "Playful physics: floating shapes bob (6s), hover tilts, squiggle draw-on-scroll. Cheerful 250ms springs.",
avoid: ["Corporate blue-gray palettes", "Hairline minimalism", "Photorealistic seriousness", "Gradients (flat pastels only)", "Empty undecorated zones — scatter something"],
},
{
slug: "y2k",
name: "Y2K",
description: "Chrome, glossy surfaces and optimistic early-2000s digital futurism.",
category: "Retro & Internet",
tags: ["y2k", "chrome", "glossy"],
bg: "#0A0A1F", surface: "#141432", ink: "#F2F0FF", muted: "#8E8AB0", accent: "#00E5FF", accent2: "#FF7AD9",
display: "Orbitron, Michroma, Impact, sans-serif",
body: "Outfit, Inter, sans-serif",
radius: "Pills and bubbles: 999px chips, 20px cards, circular orbs",
border: "Chrome keylines: 1–2px silver gradients via border-image; glowing cyan outlines on dark",
shadow: "Glow stack: 0 0 20px cyan + 0 0 60px blue; glossy top-light insets on buttons (inset 0 1px 0 white/40)",
spacing: "Bubbly density: floating glass pills, 20px card padding, 64–88px sections, orb constellations",
aesthetic: "The future as imagined in 1999: liquid chrome lettering, translucent bubbles, starfields, lens flares, and frosted control pods floating over deep space blue. Optimistic, glossy, and a little alien. For music, beauty-tech, gaming, and Y2K fashion brands.",
principles: ["Chrome everything important: text, buttons, dividers", "Bubbles and orbs float — nothing sits flat", "Glow is the shadow system"],
layout: "Orbital collage: frosted pods floating over starfield gradients; chrome headline; bubble nav. Max-width 1280px.",
buttons: "Chrome pills: silver-gradient fills, inner top-light, cyan glow; hover intensifies shine with a sweep.",
cards: "Frosted pods: translucent white/10 blur over space gradients, chrome keylines, orb decorations, glow.",
nav: "Floating bubble bar: frosted pill with chrome logo text, glowing links, orb CTA.",
imagery: "Liquid chrome 3D, butterfly clips, flip-phone macro, starfield skies, butterfly-tattoo flash. High gloss everything.",
icons: "Glossy orb icons: gradient spheres with star sparkles; pixel-star accents.",
texture: "Starfields, lens flares, bubble clusters, chrome gradients, sparkle overlays.",
motion: "Floaty: 5–8s orb drift, shine sweeps on chrome, twinkling stars. Dreamy ease-in-out loops.",
avoid: ["Matte flat design or paper textures", "Sharp brutalist geometry", "Muted earthy palettes", "Static gradients (animate the shine)", "Serif typography"],
},
{
slug: "retro-internet",
name: "Retro Internet",
description: "Early-web warmth: tiled backgrounds, guestbooks and dial-up sincerity.",
category: "Retro & Internet",
tags: ["retro", "web1", "nostalgic"],
bg: "#FFF8DC", surface: "#FFFFFF", ink: "#222222", muted: "#77705F", accent: "#0000EE", accent2: "#FF0000",
display: "Times New Roman, Georgia, serif",
body: "Verdana, Arial, sans-serif",
radius: "0–4px; beveled wells and outset buttons",
border: "Beveled panels (outset/inset), 1px gray table grids, horizontal rules with character (❦ ★)",
shadow: "Bevel highlights, not shadows: inset white + outset gray classic-raised effect",
spacing: "Cozy density: centered 800px content well, sidebar blogrolls, 16px tiled rhythm, webring footers",
aesthetic: "A loving 1997 homepage: tiled starfield or parchment, visitor counter, guestbook, MIDI-era sincerity, under-construction GIFs — rebuilt with modern performance. For personal sites, indie games, zines, and brands trading on sincerity.",
principles: ["Sincerity over polish: write like a human, sign your updates", "Tables, guestbooks, and blogrolls are features", "One MIDI-era flourish per page — then stop"],
layout: "Classic three-zone: banner header, left nav sidebar, content well, guestbook + webring footer. Centered 900px.",
buttons: "Raised beveled buttons (classic gray outset); hover presses inset. Big shiny download buttons welcome.",
cards: "Inset wells and outset panels; award badges (88×31 style) rows; polaroid guest photos.",
nav: "Sidebar nav with star bullets and visited-purple links; top banner with tagline and last-updated stamp.",
imagery: "Pixel art, clip art, scanned photos with white borders, starfield tiles, divider GIFs (CSS recreations).",
icons: "Pixel icons and emoji: ✉ ★ ☎ ♪. Favicon-grade 16px craft.",
texture: "Tiled backgrounds (subtle!), parchment, starfields, construction stripes in the footer.",
motion: "Marquee welcome, blinking NEW! tags, waving flags (CSS), cursor sparkles optional. Nostalgia, not annoyance.",
avoid: ["Sleek SaaS minimalism", "Hiding personality behind systems", "Autoplay audio (the one unforgivable sin)", "Fake retro without real content", "Breaking keyboard/reader access for jokes"],
},
{
slug: "webcore",
name: "Webcore",
description: "Early-internet aesthetics using browser chrome, hyperlinks and deliberately primitive UI.",
category: "Retro & Internet",
tags: ["webcore", "browser", "primitive"],
bg: "#C0C0C0", surface: "#FFFFFF", ink: "#000000", muted: "#555555", accent: "#0000EE", accent2: "#008080",
display: "Times New Roman, serif",
body: "Arial, Helvetica, sans-serif",
radius: "0px — windows are square",
border: "OS-chrome borders: 2px outset window frames, inset wells, 1px table grids",
shadow: "Window-manager shadows: 4px 4px 0 rgba(0,0,0,0.35) under draggable-feeling windows",
spacing: "Desktop collage: overlapping windows with title bars, 8px chrome padding, taskbar footer 40px",
aesthetic: "The browser AS the aesthetic: fake window chrome, tiling image layouts, blue hyperlinks, directory listings, and view-source pride. Webcore treats HTTP itself as a medium — raw, indexable, and a little feral. For net-art projects, indie tools, and archives.",
principles: ["Browser chrome is decoration: windows, scrollbars, status bars", "Blue links, visited purple — the original design system", "View-source should read like poetry"],
layout: "Window collage: draggable-feeling bordered windows over gray desktop; taskbar nav; start-menu sections. Tiled image rivers.",
buttons: "Raised gray buttons with 2px outset borders; default-button bold outline; hover presses inset.",
cards: "Windows: title bar (gradient blue), menu row, content well, status bar. Each card a tiny application.",
nav: "Taskbar: start button, window tabs, clock. Top nav as a bookmark toolbar of favicon links.",
imagery: "Tiled thumbnails, dithered images, screencaps with window chrome, favicon mosaics.",
icons: "16px favicon-grade pixel icons; folder/file glyphs; hourglass for loads (brief, kind).",
texture: "Desktop teal (#008080) or gray grounds; dither patterns; scanline overlays optional.",
motion: "Window-open pops, marquee tickers, progress bars that actually map to loads. Solitaire-win energy on conversion (restrained).",
avoid: ["Hiding URLs and structure", "Custom cursor chaos that breaks usability", "Trendy gradients over chrome honesty", "Single-page smoothness — embrace the clunk", "Forgetting mobile: stack windows vertically"],
},
];
