export const stylesD = [
{
slug: "bento-grid",
name: "Bento Grid",
description: "Compartmentalized delight: varied-size tiles packing features into one view.",
category: "Product & SaaS",
tags: ["bento", "grid", "modular"],
bg: "#F5F5F4", surface: "#FFFFFF", ink: "#1C1917", muted: "#766F6A", accent: "#2962FE", accent2: "#FF6B9D",
display: "Inter, SF Pro Display, sans-serif",
body: "Inter, SF Pro Text, sans-serif",
radius: "16–20px tile rounding; inner media 12px",
border: "1px solid #E7E5E4 on tiles; media flush-bleed inside tiles",
shadow: "Soft tile lift: 0 2px 12px rgba(28,25,23,0.06); hover 0 12px 32px rgba(28,25,23,0.12)",
spacing: "Tile system: 16px gaps, 24px tile padding, 2–4 column spans; one bento viewport per section",
aesthetic: "The Apple-keynote grid as a layout system: a 4–6 column board of mismatched tiles — big feature + small stats + wide banner — packing a whole story into one viewport. Dense but digestible; every tile one idea. For product launches, portfolios, dashboards, and features pages.",
principles: ["One idea per tile; size encodes importance (2×2 hero, 1×1 stats)", "Vary tile media: product shot, stat, quote, mini-chart, icon", "Gaps are gutters: uniform 12–16px, never mixed"],
layout: "Bento board: 12-col grid, tiles spanning 3/4/6/8 cols; hero tile 2 rows tall; responsive collapse 2-col then 1-col. Max-width 1200px.",
buttons: "Tile CTAs: small pills bottom-left of feature tiles; section CTA below the board. 14px medium labels.",
cards: "Tiles ARE the cards: white, 18px radius, border + soft shadow, 24px padding; hover lifts 4px with deeper shadow.",
nav: "Standard minimal bar above the board; anchor links jump to tile groups. Board order = story order.",
imagery: "Product screenshots cropped to tiles, mini device mockups, gradient tile grounds, logo chips. Bleed media to tile edges.",
icons: "20px accent-tinted glyphs as tile headers; stat tiles pair icon + giant number.",
texture: "Subtle dot grid behind the board; gradient meshes inside feature tiles at low opacity.",
motion: "Staggered tile entrances (50ms cascade, 300ms rise); hover lift 200ms; number count-ups in stat tiles.",
avoid: ["Uniform same-size card grids (that's not bento)", "More than 6–8 tiles per board", "Tiny text inside small tiles", "Mixed gap sizes", "Autoplaying video in every tile"],
},
{
slug: "card-based-ui",
name: "Card-Based UI",
description: "Contained modularity: bordered content units in browsable grids and feeds.",
category: "Product & SaaS",
tags: ["cards", "modular", "feeds"],
bg: "#F1F5F9", surface: "#FFFFFF", ink: "#0F172A", muted: "#617187", accent: "#2563EB", accent2: "#7C3AED",
display: "Inter, system-ui, sans-serif",
body: "Inter, system-ui, sans-serif",
radius: "12px cards, 8px media, pills for tags",
border: "1px solid #E2E8F0; media separated by hairline; selected cards get 2px accent ring",
shadow: "Feed-calm: 0 1px 3px rgba(15,23,42,0.08); hover 0 8px 24px rgba(15,23,42,0.12)",
spacing: "Feed rhythm: 16–20px card gaps, 20px card padding, 16:9 media, 64–88px sections",
aesthetic: "The Pinterest-to-dashboard continuum: self-contained content units with media, title, meta, and actions — browsable, saveable, shareable. Scales from social feeds to analytics. For marketplaces, media, dashboards, and anything browsable.",
principles: ["Cards are self-contained: media + title + meta + action, always scannable", "Uniform internal anatomy across varying content", "Hover reveals actions; rest state stays calm"],
layout: "Masonry or uniform grids (3–4 col desktop); list rows on mobile; filter bar + sort above; infinite or paged below. Max-width 1280px.",
buttons: "Card actions: save/bookmark icon buttons, primary pills for conversion; hover-reveal secondary row.",
cards: "Anatomy: 16:9 media top, 16px padding, title 15px semibold 2-line clamp, meta row (avatar + time + tag), action footer.",
nav: "Feed chrome: search + filter chips + view toggle; sticky with blur; saved/count indicators.",
imagery: "Cover media per card (photos, thumbs, charts); avatar stacks; empty-state illustrations for zero results.",
icons: "Bookmark, share, more (···), view-mode glyphs — 18px, gray-500, accent on active.",
texture: "Flat slate-50 ground; skeleton shimmer tiles while loading.",
motion: "200ms hover lifts; layout animations on filter (FLIP); skeleton shimmer; pull-refresh on mobile.",
avoid: ["Varying card anatomy per item", "Cramming full articles into cards (tease, link out)", "More than 2 actions visible at rest", "Autoplay media in cards", "Tiny tap targets on mobile cards"],
},
{
slug: "corporate-saas",
name: "Corporate SaaS",
description: "Trust-first software marketing: gradient heroes, logos walls and ROI proof.",
category: "Product & SaaS",
tags: ["saas", "b2b", "trust"],
bg: "#FFFFFF", surface: "#F8FAFC", ink: "#0F172A", muted: "#64748B", accent: "#2563EB", accent2: "#7C3AED",
display: "Inter, Plus Jakarta Sans, sans-serif",
body: "Inter, system-ui, sans-serif",
radius: "12px cards, 8px buttons, pills for badges",
border: "1px slate-200 on cards; gradient hairlines on hero panels",
shadow: "Polished B2B: hero dashboard 0 24px 80px rgba(37,99,235,0.18); cards 0 2px 12px slate/8",
spacing: "Funnel rhythm: 96–128px sections, logo wall 48px, 3-col feature grids, ROI band, FAQ, final CTA",
aesthetic: "The trusted B2B playbook executed well: gradient hero with dashboard screenshot, customer logo wall, metric proof band, feature grid, testimonial carousel, pricing, FAQ, big CTA. Familiar because it converts. For B2B tools selling to teams with budgets.",
principles: ["Proof before claims: logos, metrics, quotes above the fold-fold", "One funnel, one CTA repeated with escalating commitment", "Screenshots beat illustrations for trust"],
layout: "Funnel stack: nav → hero (copy left, dashboard right) → logos → metrics → features → testimonial → pricing → FAQ → CTA → footer. Max-width 1200px.",
buttons: "Blue primary pills/8px, 16px semibold, arrow affordance; secondary demo-link; sticky mobile CTA.",
cards: "Feature cards: icon chip + title + 2-line body; testimonial cards with photo + logo; pricing tiers with highlighted middle.",
nav: "Logo + product/solutions/pricing + sign-in + Get-started CTA; announcement bar optional; sticky blur.",
imagery: "Dashboard screenshots in browser frames with glow; customer photos; abstract gradient covers for OG/social.",
icons: "Duotone blue icon chips (20px); check circles for lists; star ratings gold.",
texture: "Hero gradient mesh (blue→violet) at 60% + grid overlay at 6%; section grounds alternate white/slate-50.",
motion: "Polished 300ms reveals; dashboard parallax tilt on mouse; logo marquee; count-up metrics.",
avoid: ["Hiding pricing (trust killer)", "Generic AI-gradient everything", "Walls of text without proof", "More than one primary CTA", "Dark patterns in trial language"],
},
{
slug: "stripe-inspired",
name: "Stripe-Inspired",
description: "Gradient precision: airy pastels, developer clarity and weight-300 elegance.",
category: "Product & SaaS",
tags: ["stripe", "gradient", "developer"],
bg: "#FFFFFF", surface: "#F6F9FC", ink: "#0A2540", ink2: "#425466", muted: "#62748A", accent: "#635BFF", accent2: "#00D4FF",
display: "Sohne, Inter, Helvetica Neue, sans-serif",
body: "Sohne, Inter, Helvetica Neue, sans-serif",
radius: "8px cards and buttons; pills for version badges",
border: "Hairlines #E6EBF1; gradient top-border on hero; code blocks bordered dark",
shadow: "Stripe-lift: 0 6px 12px -2px rgba(10,37,64,0.08), 0 3px 7px -3px rgba(10,37,64,0.1); colored glows on hero",
gradient: "Signature: diagonal aurora (orange→pink→violet→cyan) clipped in angled hero bands",
spacing: "Airy precision: 128px hero, 96px sections, 24px card padding, 18px body at 1.6",
aesthetic: "Weight-300 elegance over aurora color: pastel gradient bands sliced diagonally across white, navy-ink text (#0A2540), code samples beside prose, and docs that read like product. For payments, APIs, fintech, and developer-first brands.",
principles: ["Aurora bands carry the color; content sits on white", "Navy ink (#0A2540), never pure black", "Code beside prose — developers decide here"],
layout: "Aurora hero (angled gradient bands + headline + code window), logo wall, code-feature splits, globe/metrics band, docs CTA. Max-width 1080px prose.",
buttons: "Blurple (#635BFF) pills, white 15px medium; hover lifts + darkens; secondary as navy text link with arrow.",
cards: "White, hairline borders, Stripe-lift shadows; code cards dark navy (#0A2540) with pastel syntax.",
nav: "Transparent over aurora → white blur on scroll; product links + developers + pricing + sign-in + CTA pill.",
imagery: "Aurora meshes, 3D card renders, globe visualizations, code-window screenshots.",
icons: "Minimal 20px slate glyphs; product icons as gradient tiles.",
texture: "Aurora mesh gradients + faint grid; angled clip dividers between bands.",
motion: "Aurora slow-drift (20s), 300ms card lifts, code typing in hero window, scroll-triggered band reveals.",
avoid: ["Pure black text", "Heavy shadows or dark sections", "Hiding docs behind marketing", "Generic purple-blue SaaS gradient without the diagonal bands", "Small low-contrast gray text"],
},
{
slug: "linear-inspired",
name: "Linear-Inspired",
description: "Ultra-minimal precision: dark restraint, purple glow and keyboard-first craft.",
category: "Product & SaaS",
tags: ["linear", "dark", "craft"],
bg: "#08090A", surface: "#101214", ink: "#F7F8F8", muted: "#8A8F98", accent: "#5E6AD2", accent2: "#8E8AFF",
display: "Inter, SF Pro Display, sans-serif",
body: "Inter, SF Pro Text, sans-serif",
radius: "8px panels, 6px buttons and inputs",
border: "1px rgba(255,255,255,0.08) hairlines; gradient edge-highlights on hero panels",
shadow: "Purple aura: 0 0 80px rgba(94,106,210,0.25) on heroes; panels 0 8px 30px black/50",
spacing: "Tight craft: 13px UI text, 16px panel padding, 96px marketing sections, 4px base grid",
aesthetic: "Dark-room precision: near-black canvas, 13px Inter, hairline white/8 borders, one violet accent with aura glows, and keyboard shortcuts everywhere. Calm, fast, and obsessive. For devtools, AI products, and productivity tools that sell craft.",
principles: ["Dark is the product: design dark-first, light rarely", "Violet glow marks what matters — ration it", "Shortcuts and ⌘K are navigation, not extras"],
layout: "App shell (sidebar + cycles + issue panes) for product; marketing = centered hero with aura + screenshot + feature grid. Max-width 1100px.",
buttons: "Violet primary (6px, 13px medium); ghost secondaries; kbd hints inside buttons where apt. Focus rings violet.",
cards: "Dark panels with white/8 borders; feature cards pair icon + one-liner; keyboard-first empty states.",
nav: "Minimal dark bar: logo + product/changelog/customers + sign-in + CTA; ⌘K button in product chrome.",
imagery: "Dark product screenshots with violet aura; gradient grid backdrops; customer logos in gray monochrome.",
icons: "15px 1.75px-stroke set, gray-400; violet active; kbd chips for shortcuts.",
texture: "Gradient grid + noise on dark; aura meshes behind heroes; vignette to focus center.",
motion: "Fast 100–150ms UI; hero aura breathes (8s); page transitions fade-slide 200ms; skeleton shimmer violet-gray.",
avoid: ["Light-mode-first thinking", "Multiple bright accents", "Heavy marketing gradients", "Hiding shortcuts", "Large display type in the app UI"],
},
{
slug: "notion-inspired",
name: "Notion-Inspired",
description: "Warm minimal workspace: serif warmth, soft blocks and template friendliness.",
category: "Product & SaaS",
tags: ["notion", "workspace", "warm"],
bg: "#FFFFFF", surface: "#F7F7F5", ink: "#37352F", ink2: "#6F6E69", muted: "#73716D", accent: "#2383E2", accent2: "#D9730D",
display: "Georgia, Lyon Text, serif",
body: "Inter, ui-sans-serif, sans-serif",
radius: "6px blocks, 3px inline (code, mentions), 8px covers",
border: "Barely-there: 1px #E9E9E8 on tables/boards; hover-reveal block controls (⋮⋮ +)",
shadow: "Almost none: page shadows off; menus 0 4px 20px rgba(55,53,47,0.12); drag-ghost lift",
spacing: "Document rhythm: 708px page measure, 4px block gaps, 44px page padding, full-width option for boards",
aesthetic: "A warm document that became software: serif page titles with emoji icons, toggle blocks, callouts in tints, and databases that feel like tables you already love. Friendly, unhurried, template-shaped. For docs, wikis, notes, and community knowledge.",
principles: ["Pages over screens: everything is a block in a document", "Warm paper neutrals (#37352F ink on white)", "Templates teach: starter content beats empty states"],
layout: "Page canvas: cover banner, icon + serif title, block stream (text/toggle/callout/database), sidebar page tree. Max measure 708px (boards full-bleed).",
buttons: "Quiet 32px gray-hover buttons; blue text links; database Add buttons full-width dashed. Hover-grays, never loud fills.",
cards: "Blocks: callouts (tinted bg + icon), toggles, synced embeds, gallery cards with covers. Borders appear on hover/drag.",
nav: "Sidebar page tree with emoji icons, favorites, private/shared sections, + New page; top bar breadcrumb + share.",
imagery: "Unsplash-style covers (muted), emoji page icons, template gallery thumbnails. Warm and human.",
icons: "Emoji-first (!), then 16px gray line icons. Duplicate/turn-into affordances on hover.",
texture: "Paper-white flat; cover images carry all texture; subtle dotted background in empty boards.",
motion: "Gentle 150ms block fades; drag-and-drop smoothness; toggle rotations; slash-menu pop (scale .98→1).",
avoid: ["Dark dashboards or neon accents", "Heavy shadows and elevation", "Hiding block controls from newcomers", "Empty states without templates", "Blue-everything SaaS chrome"],
},
{
slug: "gradient-design",
name: "Gradient Design",
description: "Color in transition: mesh washes, aurora fields and glow-led hierarchy.",
category: "Atmosphere & Gradient",
tags: ["gradient", "mesh", "colorful"],
bg: "#0B0620", surface: "#2A1B5E", ink: "#F4F1FF", muted: "#9A90C0", accent: "#7C5CFF", accent2: "#00E5FF",
display: "Outfit, Inter, sans-serif",
body: "Outfit, Inter, sans-serif",
radius: "20–28px fluid panels; pills for chips",
border: "Gradient hairlines (border-image or mask); glass keylines over bright fields",
shadow: "Colored ambient: 0 20px 80px violet/30, cyan/20; text glow on display lines",
spacing: "Flowing: full-bleed gradient chapters 88–120px, floating glass panels 28px padding",
aesthetic: "Mesh-gradient romance: violet→magenta→cyan washes flowing across dark space, glass panels floating, glowing display type. Feeling-forward and premium-night. For AI products, music, fintech, and launches that need wonder.",
principles: ["Gradients always move (slow drift) — static mesh feels dead", "Dark grounds make color luminous; light text floats", "One gradient story per page — variations, not new rainbows"],
layout: "Aurora scroll: gradient hero with glass panel, feature bands alternating mesh/dark, glow CTA finale. Max-width 1200px.",
buttons: "Gradient pills (violet→cyan) with glow; white labels; hover brightens + lifts. Ghost glass secondaries.",
cards: "Glass over mesh: blur 20px, gradient keyline, 24px radius, glow metrics.",
nav: "Floating glass pill; gradient logo text; glowing CTA.",
imagery: "Mesh fields, 3D gradient blobs, glowing product shots, aurora photography.",
icons: "White-on-glass glyphs with glow; gradient icon tiles for features.",
texture: "Mesh gradients, grain 4%, light-leak streaks. Blur orbs behind everything.",
motion: "20s gradient drift, floating panels (8s), glow pulses. Reduced-motion = still aurora poster.",
avoid: ["Static flat gradients", "Light-mode pastel without dark contrast plan", "Text directly on bright mesh without scrim", "Multiple unrelated gradients per page", "Glow that kills contrast below 4.5:1"],
},
{
slug: "aurora-glow",
name: "Aurora / Glow",
description: "Northern-light interfaces: dark skies, luminous ribbons and soft radiance.",
category: "Atmosphere & Gradient",
tags: ["aurora", "glow", "atmospheric"],
bg: "#050914", surface: "#0A1220", ink: "#E8F1FF", muted: "#6E86A3", accent: "#00E5A0", accent2: "#7C5CFF",
display: "Outfit, Sora, sans-serif",
body: "Inter, Outfit, sans-serif",
radius: "16–24px soft panels; pill badges",
border: "Luminous hairlines: 1px rgba(0,229,160,0.35); ribbon dividers via SVG aurora bands",
shadow: "Radiance: 0 0 40px green/25 + 0 0 100px violet/20; card ambient matching ribbon hues",
spacing: "Night-sky pacing: vast dark pauses (120px+), glowing content bands, 28px panel padding",
aesthetic: "Polar night with living light: deep navy-black skies, green-violet aurora ribbons drifting overhead, glass observatory panels, glowing telemetry. Serene and vast. For climate, space, sleep, and premium AI brands.",
principles: ["Darkness is the canvas — protect it; light is precious", "Green→violet ribbons; amber only for human warmth moments", "Glow marks life: active, live, present"],
layout: "Observatory scroll: sky hero with ribbons, dark pauses, glowing data bands, horizon CTA. Max-width 1200px.",
buttons: "Glow pills: green-tinted fills with dark text, or glass with green keyline; hover radiates.",
cards: "Observatory panels: dark glass, luminous keylines, ribbon-top accents, live-dot headers.",
nav: "Minimal dark bar with aurora-dot logo; live status readout; glowing CTA.",
imagery: "Aurora photography, night landscapes, glowing flora, star timelapses. Green-violet grade.",
icons: "Thin luminous glyphs: waves, peaks, orbits, sleep moons — 1.5px with glow.",
texture: "Aurora ribbons (SVG/canvas), starfields, mist, frost grain at 5%.",
motion: "Slow ribbon drift (30s), twinkle stars, breathing glows (6s). Serenity in timing; still poster for reduced-motion.",
avoid: ["Bright daylight sections", "Harsh neon cyberpunk energy", "Multiple competing glow hues", "Fast motion (nothing here hurries)", "Gray corporate chrome"],
},
{
slug: "holographic",
name: "Holographic",
description: "Iridescent foil surfaces: shifting rainbows, light-streak cards and prism play.",
category: "Atmosphere & Gradient",
tags: ["holographic", "iridescent", "foil"],
bg: "#0D0D14", surface: "#15151F", ink: "#F2F0FF", muted: "#8E8AB0", accent: "#7DF9FF", accent2: "#FF7AD9",
display: "Unbounded, Outfit, sans-serif",
body: "Outfit, Inter, sans-serif",
radius: "16–24px foil cards; pills for seals",
border: "Prism keylines: conic-gradient borders (rainbow at low alpha); light-streak dividers",
shadow: "Foil light: rainbow ambient 0 12px 48px holographic/25; white specular streaks on tilt",
spacing: "Showcase pacing: hero foil moment, 88–110px galleries, 24px card padding, dark pauses",
aesthetic: "Trading-card foil as UI: conic-rainbow surfaces that shift with cursor tilt, chrome text, light-streak seals, dark velvet grounds. Collectible energy. For drops, music, gaming, fintech metal cards, and beauty.",
principles: ["Foil responds to light: tilt/hover must shift the rainbow", "Dark velvet grounds make foil read precious", "One foil moment per viewport — ration the rainbow"],
layout: "Showcase: foil hero card with tilt, gallery of holo tiles, dark spec bands, drop CTA. Max-width 1200px.",
buttons: "Foil pills with shifting gradients + dark labels; hover sweeps the spectrum. Secondary dark glass.",
cards: "Holo tiles: conic-gradient surface, specular streak overlay, tilt-on-mouse, dark back with specs.",
nav: "Dark bar with foil logo mark; drop-countdown pill; glowing CTA.",
imagery: "Foil textures, chrome 3D, iridescent product shots, light-streak photography.",
icons: "Prism glyphs with gradient strokes; seal/stamp devices for authenticity.",
texture: "Conic rainbows, light streaks, foil noise, velvet dark grounds.",
motion: "Tilt-reactive foil (pointer-tracked), spectrum sweeps 6s, shimmer on scroll. Static foil fallback for reduced-motion.",
avoid: ["Foil on everything (visual inflation)", "Light grounds behind foil (kills the shift)", "Static rainbow gradients without light response", "Competing foil hues per card", "Tiny foil text (rainbows need area)"],
},
{
slug: "liquid-chrome",
name: "Liquid Chrome",
description: "Molten metal interfaces: flowing silver, mirror reflections and Y2K luxury.",
category: "Atmosphere & Gradient",
tags: ["chrome", "liquid", "metallic"],
bg: "#0A0A0F", surface: "#121218", ink: "#F2F2F5", muted: "#8E8E99", accent: "#C0C0C8", accent2: "#7DF9FF",
display: "Unbounded, Michroma, serif",
body: "Outfit, Inter, sans-serif",
radius: "Organic metal: blob radii (40% 60% 60% 40%), pill capsules, mirror cards 20px",
border: "Mirror keylines: 1–2px silver gradients; reflection dividers (flipped faded duplicates)",
shadow: "Molten ambient: 0 20px 80px silver/20; sharp specular highlights (white streaks)",
spacing: "Gallery-fluid: hero metal mass, 100–130px dark pauses, 28px panel padding",
aesthetic: "Mercury with taste: flowing silver masses, mirror-duplicate reflections, Y2K bubble lettering in chrome, dark voids. Liquid luxury for fashion, fragrance, music, and tech flagships.",
principles: ["Chrome needs darkness to mirror", "Reflections sell liquidity: duplicate + fade + flip", "One molten moment per page; support with matte darks"],
layout: "Molten showcase: chrome hero mass with reflection, matte dark chapters, bubble-type intertitles, mirror CTA. Max-width 1280px.",
buttons: "Chrome pills: silver gradient, dark labels, specular sweep on hover. Matte black secondaries.",
cards: "Mirror panels: dark glass with chrome keylines and reflected headers; blob-masked media.",
nav: "Dark bar, chrome wordmark, minimal links, silver CTA pill.",
imagery: "Liquid metal 3D, mercury macro, chrome fashion, bubble renders. Silver-graded.",
icons: "Liquid glyphs: melting blobs, droplets, orbs — silver gradient fills.",
texture: "Brushed + liquid metal, reflection fades, bubble clusters, star sparkles.",
motion: "Slow mercury morphs (SVG blobs 12s), specular sweeps, floating orbs. Hypnotic, never hurried.",
avoid: ["Matte flat grays without speculars", "Colorful rainbows (silver + one accent max)", "Sharp brutalist frames", "Static chrome (must show light motion)", "Light-mode-first layouts"],
},
{
slug: "3d-web-design",
name: "3D Web Design",
description: "Dimensional product storytelling: depth, lighting and spatial scenes around content.",
category: "Immersive & Motion",
tags: ["3d", "depth", "spatial"],
bg: "#0B0B12", surface: "#14141D", ink: "#F2F0FF", muted: "#8E8AB0", accent: "#8466FF", accent2: "#00E5FF",
display: "Space Grotesk, Sora, sans-serif",
body: "Inter, Space Grotesk, sans-serif",
radius: "18–24px viewport cards; pills for scene labels",
border: "Scene frames: 1px violet/25 keylines; depth cue vignettes; floor-grid overlays",
shadow: "Cinematic: 0 30px 100px black/60 under scenes; colored rim-light glows",
spacing: "Staging: full-viewport 3D chapters alternating with 88px content bands; 28px panel padding",
aesthetic: "Product as cinema: real-time or rendered 3D scenes (product floats, explodes, configures) staged between editorial bands. Lighting does the branding. For hardware, footwear, automotive, and flagship launches. Performance budgets are part of the design.",
principles: ["3D serves story beats: reveal → explore → configure → buy", "Light the brand: consistent key/rim palette across scenes", "Fallbacks are first-class: poster frames + copy carry no-WebGL"],
layout: "Stage + script: sticky 3D viewport chapters with scroll-driven camera, spec bands, configurator section, CTA. Max-width 1280px content.",
buttons: "Cinematic pills with glow; scene controls (rotate/explode) as icon HUD; configurator swatches large.",
cards: "Spec plates floating over scenes; chapter cards with scene labels (01 — Unibody).",
nav: "Minimal overlay: mark + chapter links + configurator CTA; progress rail for scroll chapters.",
imagery: "3D renders, turntables, exploded views, material macros. Consistent studio HDRI.",
icons: "HUD glyphs: orbit, explode, slice, AR — thin with glow.",
texture: "Studio backdrops, floor grids, particulate depth haze, film grain 4%.",
motion: "Scroll-driven camera (scrub, damped); idle turntable 20s; reduced-motion = poster + manual rotate buttons.",
avoid: ["3D without story or fallbacks", "Heavy scenes on mobile without lite mode", "Unreadable text over busy renders (use scrims)", "Autoplay camera that fights the user", "Ignoring load budgets — show progress honestly"],
},
{
slug: "immersive",
name: "Immersive",
description: "Full-bleed worlds: scroll-driven scenes, sound-off cinema and total absorption.",
category: "Immersive & Motion",
tags: ["immersive", "cinematic", "scroll"],
bg: "#060606", surface: "#101010", ink: "#F5F3EC", muted: "#8A877E", accent: "#E8FF47", accent2: "#FF5C00",
display: "Anton, Archivo Black, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0–12px; cinema is sharp, UI floats rounded",
border: "Cinematic mattes: letterbox bars, hairline chapter marks, scrims over imagery",
shadow: "Theater dark: vignettes + scrims; no UI shadows — depth from layering planes",
spacing: "Film pacing: full-viewport acts, 0px between scenes (cuts, not gaps), 96px credit-style closers",
aesthetic: "Cinema you scroll: full-bleed film chapters, letterboxed scenes, giant condensed titles, chapter cards (ACT I), and a world that absorbs the chrome. For destinations, flagships, documentaries, and brand worlds.",
principles: ["Full-bleed or nothing — chrome dissolves into scenes", "Pace like film: establish, develop, cut", "Sound-off cinema: captions and score-lines in type"],
layout: "Acts: 100vh scene chapters with overlay type, intertitle cards, map/data interludes, credit closer. Persistent minimal HUD.",
buttons: "Ghost-on-film buttons with scrims; solid lime for conversion moments. Big, few, subtitled.",
cards: "No cards in scenes — floating HUD plates with scrims; chapters listed as title cards.",
nav: "Dissolving HUD: mark + act links + mute/progress; hides on scroll down, returns on up.",
imagery: "Cinematic full-bleed film/stills; drone sweeps; portrait inserts. Heavy grade, consistent LUT.",
icons: "Playback glyphs, compass, chapter marks — thin white with scrim chips.",
texture: "Film grain 8%, gate weave (subtle), light leaks on cuts, vignette.",
motion: "Scroll-scrubbed dolly/zoom (damped), cross-dissolve cuts, parallax ±8%. Reduced-motion = stills + fade cuts.",
avoid: ["Sidebars and dashboards inside the film", "Small timid media", "Autoplay sound", "Popups over scenes", "Ending without a credit-style closer + CTA"],
},
{
slug: "scrollytelling",
name: "Scrollytelling",
description: "Narrative scroll: pinned graphics, stepped chapters and data that unfolds.",
category: "Immersive & Motion",
tags: ["scrollytelling", "narrative", "data"],
bg: "#FAFAF8", surface: "#FFFFFF", ink: "#1A1A1A", muted: "#6E6A61", accent: "#2B4EFF", accent2: "#FF5C00",
display: "Inter Tight, Helvetica Neue, sans-serif",
body: "Inter, Georgia, sans-serif",
radius: "10–14px graphic panels; pills for step dots",
border: "Hairline frames on pinned graphics; progress rail 2px with accent fill",
shadow: "Editorial-calm: 0 8px 30px rgba(0,0,0,0.08) on pinned media; text stays flat",
spacing: "Chapter rhythm: 100vh steps, pinned graphic left/center, 120px chapter breaks, progress rail",
aesthetic: "The explainer as journey: a sticky graphic evolves as stepped prose scrolls past — maps fill, charts build, diagrams annotate. NYT-graphics discipline. For journalism, research, climate, finance-education, and launches with a real story.",
principles: ["One graphic, many states — continuity teaches", "Steps are short: 2–3 sentences each, one insight per step", "Progress is honest: rail + step dots + back links"],
layout: "Sticky stage + step stream: 50/50 pinned graphic + scrolling steps (desktop); stacked with mini-progress on mobile. Max-width 1280px.",
buttons: "Chapter jumps (prev/next), replay-graphic, share-this-step, methodology toggle. Quiet bordered controls.",
cards: "Step cards: white, bordered, 20px padding, number + insight; active step highlighted with accent edge.",
nav: "Story bar: title + progress rail + chapter menu + share. Reading-time estimate; reduced-motion toggle visible.",
imagery: "Custom charts/maps/diagrams (SVG), annotated photography, timeline graphics. One visual language throughout.",
icons: "Step dots, replay, share, footnote anchors — functional mini-glyphs.",
texture: "Paper flat; faint grid in graphic stage; print-like hairlines.",
motion: "Scroll-scrubbed graphic states (damped, reversible); step fades 250ms; count-ups on entry. Reduced-motion = stepper buttons.",
avoid: ["Decorative scroll-jacking without insight", "Long paragraphs per step", "Graphics that change topic mid-story", "Hiding methodology/sources", "Auto-advance that steals control"],
},
{
slug: "parallax",
name: "Parallax",
description: "Layered depth scrolling: foreground, midground and skies drifting apart.",
category: "Immersive & Motion",
tags: ["parallax", "depth", "layers"],
bg: "#0E1A2B", surface: "#16273D", ink: "#F0F6FF", muted: "#7E96B3", accent: "#FFC24B", accent2: "#4DD8FF",
display: "Sora, Outfit, sans-serif",
body: "Inter, Outfit, sans-serif",
radius: "16px floating panels; pill altitude chips",
border: "Atmospheric: hairline light edges on near layers; mist dividers between depths",
shadow: "Aerial perspective: distant layers hazed, near layers crisp with soft drops",
spacing: "Expedition pacing: 120vh vista chapters, floating content plates, 100px+ sky pauses",
aesthetic: "Diorama scrolling: 4–6 depth layers (sky → peaks → forest → foreground) drifting at different rates over illustrated or photographic vistas. Wonder through depth. For travel, outdoors, gaming, and cinematic launches.",
principles: ["4+ layers minimum or the effect reads flat", "Content rides the near layer — never strand text mid-depth", "Provide a still-vista fallback; depth is enhancement"],
layout: "Vista chapters: full-bleed layered scenes with floating content plates; interlude maps; summit CTA. Max-width 1200px plates.",
buttons: "Expedition pills with glow; altitude/chapter chips; solid amber for book-style conversion.",
cards: "Floating plates: dark glass over vistas with scrims; trail-stat rows; waypoint lists.",
nav: "Altitude HUD: mark + elevation readout + chapter dots; minimal over skies.",
imagery: "Layered vista art (SVG/photo composite), mist PNGs, peak silhouettes, tiny explorers for scale.",
icons: "Peaks, compasses, altitude marks, weather — outdoor glyph set, light on dark.",
texture: "Mist bands, grain, paper-map textures in interludes, star layers at night.",
motion: "Multi-rate scroll layers (0.1×–0.6×), mist drift 20s, bird/particle accents. Reduced-motion = composed stills.",
avoid: ["Parallax on text (readability killer)", "Too-subtle layer rates", "Busy content over busy vistas (scrim!) ", "Motion sickness speeds — keep rates gentle", "No fallback for reduced-motion"],
},
];
