export const stylesC = [
{
slug: "desktop-ui",
name: "Desktop UI",
description: "Windowed nostalgia: draggable-feeling panels, menus and desktop metaphors.",
category: "OS & Terminal",
tags: ["desktop", "windows", "skeuomorph"],
bg: "#008080", surface: "#C0C0C0", ink: "#111111", muted: "#555555", accent: "#000080", accent2: "#008080",
display: "Tahoma, Verdana, sans-serif",
body: "Tahoma, Verdana, sans-serif",
radius: "0px windows; 4px icons labels",
border: "Classic chrome: 2–3px outset frames, inset wells, 1px menu separators",
shadow: "OS shadows: 6px 6px 0 rgba(0,0,0,0.3) under windows; bevel highlights as light source",
spacing: "Desktop logic: 8px chrome padding, 28px title bars, 40px taskbar, icon grid 88px pitch",
aesthetic: "A beloved 1998 desktop, lovingly functional: teal wallpaper, bordered windows with blue gradient title bars, desktop icons with white-outline labels, and a taskbar clock. Every panel feels grabbable. For retro tools, games, portfolios, and playful SaaS easter eggs.",
principles: ["Every panel is a window: title bar, controls, menu, status", "Teal + gray + navy is home — deviate sparingly", "Clicks clunk: outset → inset press states everywhere"],
layout: "Desktop field: wallpaper ground, icon column left, 1–3 overlapping windows center, taskbar pinned bottom. Mobile stacks windows.",
buttons: "Raised outset buttons; bold-outlined default; disabled = gray etched text. Press insets with 100ms clunk.",
cards: "Windows with title bars, menu rows (File Edit View), toolbar strips, content wells, status bars with grip corners.",
nav: "Taskbar: Start button (beveled, bold), task buttons (inset when active), tray with clock. Start menu as dropdown panel.",
imagery: "Pixel icons (32px classic style), wallpaper gradients, dithered photo viewers inside windows.",
icons: "Classic 32/16px pixel icons: folders, documents, trash, computer. White-outline label text.",
texture: "Teal flat or cloudy-sky wallpaper; dithered fills; bevel gradients only on chrome.",
motion: "Window open/close pops (120ms), minimize-to-taskbar illusion, hourglass on fake loads. Snappy and mechanical.",
avoid: ["Web-page layouts without windows", "Modern minimal chrome", "Hiding the taskbar metaphor", "Gradients beyond title bars", "Breaking the metaphor with SaaS modals"],
},
{
slug: "windows-95",
name: "Windows 95",
description: "Gray-beveled perfection: title bars, taskbars and start-menu logic.",
category: "OS & Terminal",
tags: ["windows95", "retro", "gray"],
bg: "#008080", surface: "#C3C7CB", ink: "#000000", muted: "#555555", accent: "#000080", accent2: "#FF0000",
display: "Pixelated MS Sans Serif, Tahoma, sans-serif",
body: "MS Sans Serif, Tahoma, Verdana, sans-serif",
radius: "0px — strictly square, always",
border: "The bevel system: outset (white top-left, dark bottom-right), inset reversed; 1px dotted focus rects",
shadow: "Bevel-implied depth; 4px offset under menus and dragged windows",
spacing: "Pixel discipline: 3px chrome padding, 18px title bars, 28px taskbar, 11px UI text",
aesthetic: "Chicago-era pixel truth: #C3C7CB faces, navy title gradients, dotted focus rectangles, and a Start button with presence. The most imitated UI ever — get the bevels right and everything else follows. For retro games, portfolios, and ironic-then-sincere tools.",
principles: ["Bevels are physics: light top-left, shadow bottom-right, always", "Navy + gray + teal; red only for close/errors", "11px text, dotted focus, chunky targets — period accuracy"],
layout: "Desktop: teal field, window stack, taskbar with Start + tasks + clock. Dialogs centered with title bars and OK/Cancel.",
buttons: "Raised gray buttons with 2px outset; default gets extra black outline; pressed inverts to inset + dotted label shift.",
cards: "Dialog windows: navy gradient title bar with white bold text, □ ✕ glyphs, tab strips, inset wells, button rows.",
nav: "Start menu: two-column (dark sidebar + items), separators, arrows for cascades; taskbar tasks show window titles.",
imagery: "16-color icons, cloudy wallpaper, maze screensaver motifs as section art. Dither proudly.",
icons: "Authentic 16/32px pixel icons with 16-color palette discipline. No anti-aliased modern sets.",
texture: "Flat teal/gray; subtle cloudy wallpaper; bevel gradients strictly on chrome edges.",
motion: "Instant state flips; window drag illusion on headers; hourglass cursor moments. 90s speed: no easing, just clunks.",
avoid: ["Rounded anything", "Modern fonts or sizes", "Blue links inside chrome (that's webcore)", "Soft shadows or blur", "Anachronistic emojis in chrome"],
},
{
slug: "mac-os",
name: "Mac OS",
description: "Classic Mac warmth: pinstripes, platinum and friendly Aqua geometry.",
category: "OS & Terminal",
tags: ["mac", "aqua", "classic"],
bg: "#E8E6DF", surface: "#F2F0EB", ink: "#2B2B2B", muted: "#7A766E", accent: "#0B5FFF", accent2: "#FF9F00",
display: "Charcoal, Chicago, Geneva, sans-serif",
body: "Geneva, Verdana, Helvetica Neue, sans-serif",
radius: "4px platinum windows; full pills on Aqua buttons",
border: "Platinum 1–2px frames; Aqua gel outlines; pinstripe rules in classic zones",
shadow: "Soft Platinum drop (0 4px 16px rgba(0,0,0,0.18)); Aqua glow on default buttons",
spacing: "Friendly density: 12px chrome padding, 22px title bars with stripes, menu bar 24px top",
aesthetic: "Cupertino warmth across eras: pinstripe title bars (or brushed metal, or Aqua gel — pick one era and commit), Chicago display type for headers, Geneva body, smiling folder icons. Friendlier than Windows 95, just as square-rooted in pixels. For creative tools and nostalgic portfolios.",
principles: ["Pick one era (System 7 / Platinum / Aqua) and commit fully", "Friendliness through details: icons smile, buttons gel", "Pinstripes and gels are precious — ration them"],
layout: "Mac desktop: menu bar top (Apple + app menus + clock), window stack with striped titles, trash dock corner. Finder-style column views for content.",
buttons: "Aqua gel pills (glossy highlight, blue fill) for defaults; platinum rounded rects otherwise. Pulsing default glow (gentle).",
cards: "Platinum windows with pinstripe titles, close/zoom boxes left, content wells; Aqua sheets for dialogs.",
nav: "Menu bar navigation (File Edit View Special) + Finder sidebar with icon list; Sherlock-style search field.",
imagery: "Happy Mac motifs, pixel landscapes, brushed-metal textures, Aqua droplets. Wholesome and glossy.",
icons: "Classic Mac icon style: 32px, outlined, expressive, slightly 3D. Trash, folders with faces (tasteful).",
texture: "Pinstripes, brushed metal, Aqua gel highlights, linen (later era). One per project — no mixing eras.",
motion: "Genie-adjacent scale pops, marching-ants selections, smooth Aqua pulses. Playful but smooth (ease-out 200ms).",
avoid: ["Mixing System 7, Platinum, and Aqua in one page", "Windows-style bevels", "Harsh black/navy chrome", "Modern flat minimalism", "Forgetting the menu bar — it's the soul"],
},
{
slug: "terminal",
name: "Terminal",
description: "Monospace truth: prompts, carets and green-on-black developer honesty.",
category: "OS & Terminal",
tags: ["terminal", "cli", "developer"],
bg: "#0C0C0C", surface: "#141414", ink: "#33FF66", muted: "#6A9955", accent: "#33FF66", accent2: "#FFB000",
display: "JetBrains Mono, SF Mono, Menlo, monospace",
body: "JetBrains Mono, SF Mono, Menlo, monospace",
radius: "0–4px; sharp terminal, slightly rounded app chrome",
border: "1px solid #2A2A2A panes; ASCII dividers (─ │ ┌ ┐); blinking block caret",
shadow: "CRT glow: 0 0 24px rgba(51,255,102,0.15); scanline overlay at 6%",
spacing: "Character grid: 8px/16px = 1–2 cells; 80-col measure; line-height 1.6; prompt-prefixed everything",
aesthetic: "The command line as a complete aesthetic: black screen, green phosphor, ASCII borders, man-page typography, and typing animations. Power through text. For devtools, AI products, infra brands, and portfolios that ship. The prompt is the hero section.",
principles: ["Everything is text: prompts, tables (ASCII), progress (bars of █)", "Green/amber phosphor on near-black; one accent for links", "Typing is theater: stagger, caret, and all"],
layout: "Terminal-first: full-viewport shell hero with typed session; docs as man pages; status as top/htop-style bars. 80–100col measure.",
buttons: "Prompt-style actions: [y/N] confirms, $ commands as CTAs, bordered ASCII buttons. Hover inverts green/black.",
cards: "Pane windows with ASCII or thin borders, title bars like tmux tabs; log-stream panels; man-page sections.",
nav: "Prompt nav: ~/docs ~/pricing ~/blog path links; tab-completion hint; Ctrl+K command palette as primary nav.",
imagery: "ASCII art headers, ANSI-color diagrams, sparkline glyphs (▁▃▅), screencast GIFs in bordered panes. No stock photos.",
icons: "Nerd-font glyphs and ASCII marks (● ◆ ► ✓). No emoji, no line-icon sets.",
texture: "Scanlines, phosphor glow, subtle CRT vignette. Optional dot-matrix print texture on light variant.",
motion: "Typing sequences (respect reduced-motion: show final text), caret blink 1s steps, log auto-scroll. Mechanical timing.",
avoid: ["Proportional fonts anywhere in terminal zones", "Marketing gradients or rounded SaaS cards", "Hiding the command line behind GUI-only flows", "Rainbow syntax color in prose areas", "Fake slowness — typing should feel fast, not theatrical-laggy"],
},
{
slug: "hacker-aesthetic",
name: "Hacker Aesthetic",
description: "Matrix-green paranoia: data rain, glitch type and security-theater chrome.",
category: "OS & Terminal",
tags: ["hacker", "matrix", "glitch"],
bg: "#050505", surface: "#0D0F0D", ink: "#00FF41", muted: "#3D6B4F", accent: "#00FF41", accent2: "#FF003C",
display: "Share Tech Mono, JetBrains Mono, monospace",
body: "JetBrains Mono, IBM Plex Mono, monospace",
radius: "0–3px sharp; hex-clip badges for clearance vibes",
border: "1px phosphor-green hairlines; dashed security perimeters; red alert frames",
shadow: "Phosphor bloom: 0 0 12px green at low alpha; red alert glows on warnings",
spacing: "Ops density: log-stream rhythm, 12–13px mono, 16px panel padding, fullscreen dashboards",
aesthetic: "Hollywood terminal meets real opsec: cascading data rain (canvas, subtle), glitch headlines, hex dumps as texture, ACCESS GRANTED stamps. Green-on-black with red reserved for alarms. For security brands, CTFs, and developer tools with fangs.",
principles: ["Green is calm, red is alarm — never mix their jobs", "Data as texture: logs, hex, packets at low opacity", "Glitch is punctuation, not prose — ration it"],
layout: "Ops deck: status header (threat level, uptime), log-stream main, side intel panels, alert ticker. Fullscreen density.",
buttons: "Terminal confirms: [ INITIATE ] bordered, hover floods green with black text; destructive floods red.",
cards: "Intel panels: thin green borders, corner brackets ([ ] corners), header with classification stamp, mono data rows.",
nav: "Clearance bar: logo + threat-level pill + clock + encrypted-link icon; section links as path segments.",
imagery: "Data-rain canvas, circuit traces, satellite night maps, glitch portraits. Green-graded everything.",
icons: "Lock, shield, key, skull (once), signal glyphs — thin mono-line style with glow.",
texture: "Data rain, hex dumps, grid maps, CRT scanlines, digital rain vignettes.",
motion: "Glitch bursts on load (300ms), typing logs, blinking cursors, scan sweeps. Kill all motion under reduced-motion.",
avoid: ["Purple/blue hacker clichés without green discipline", "Unreadable micro-logs as sole content", "Glitch on every headline", "Fake progress that lies about security", "Light mode (this one lives in the dark)"],
},
{
slug: "cyberpunk",
name: "Cyberpunk",
description: "Neon-drenched dystopia: rain, chrome and high-tech low-life interfaces.",
category: "Future & Sci-Fi",
tags: ["cyberpunk", "neon", "dystopian"],
bg: "#0A0A12", surface: "#131320", ink: "#EDEDF5", muted: "#7C7C9C", accent: "#FCEE0A", accent2: "#00F0FF",
display: "Rajdhani, Orbitron, Impact, sans-serif",
body: "Rajdhani, Inter, sans-serif",
radius: "0–4px sharp; clipped corners (cyber-chamfer via clip-path)",
border: "Neon frames: 1–2px cyan/magenta keylines; chamfered corner cuts; hazard chevrons",
shadow: "Neon bleed: 0 0 24px magenta/cyan; rain-streak motion blur on heroes",
spacing: "Dense street-level: overlapping HUD layers, 16px panel padding, 64–88px chapters, ticker seams",
aesthetic: "Night City UI: rain-slicked neon, Japanese vertical signage, chrome implants, megacorp HUDs, yellow warning blocks. High-tech, low-life. For games, music, streetwear, and tech with teeth. Beauty in the overload.",
principles: ["Neon on wet black; yellow is warning, cyan is system, magenta is vice", "Chamfer everything — rounded corners are for corpo suburbs", "Layer HUD over world: scanlines, markers, Japanese microtype"],
layout: "HUD collage: fullscreen rain-city hero with overlay panels, wanted-board grids, vendor-stall sections. Max-width 1400px.",
buttons: "Chamfered neon frames with dark fills and glowing labels; yellow solid for warnings. Hover floods neon with black text.",
cards: "Vendor panels: dark glass, neon keylines, chamfered corners, Japanese vertical accents, price tags in mono.",
nav: "Megacorp bar: logo + district links + wanted-level dots + credit readout in mono. Ticker below.",
imagery: "Rain neon streets, chrome portraits, hover cars, kanji signage. Teal-magenta grade, anamorphic streaks.",
icons: "HUD glyphs: targets, chevrons, chips, katanas-minimal — thin neon strokes with glow.",
texture: "Rain streaks, wet asphalt reflections, scanlines, poster wheat-paste walls, sticker slaps.",
motion: "Rain loops, neon flicker (subtle, accessible), glitch cuts, HUD boot sequences. Flicker must respect vestibular safety.",
avoid: ["Daylight or pastel palettes", "Rounded friendly geometry", "Clean minimal layouts", "Single-accent restraint", "Neon flicker that triggers photosensitivity — keep it slow and optional"],
},
{
slug: "futurism",
name: "Futurism",
description: "Speed-worship modernism: diagonals, motion lines and machine-age optimism.",
category: "Future & Sci-Fi",
tags: ["futurist", "speed", "avant-garde"],
bg: "#F4F1EA", surface: "#FFFFFF", ink: "#141414", muted: "#6E675C", accent: "#E30613", accent2: "#0B3D91",
display: "Futura, ITC Avant Garde, sans-serif",
body: "Inter, Helvetica Neue, sans-serif",
radius: "0px — speed is sharp",
border: "Speed rules: diagonal slashes, 3px motion bars, chevron dividers",
shadow: "Motion-implied: skewed duplicates and speed-line echoes instead of shadows",
spacing: "Forward-leaning: diagonal section cuts, overlapping speed bands, 72–100px movements",
aesthetic: "Marinetti meets the motorway: diagonal compositions, speed lines, chrome numerals, and manifestos set like scripture. Optimistic machine worship — planes, turbines, velocity. For automotive, aerospace, sport, and infrastructure brands.",
principles: ["Diagonals signal motion — horizontals are parking lots", "Manifestos, not paragraphs: short violent lines of copy", "Chrome + red + ink; the palette of velocity"],
layout: "Speedway scroll: diagonal-cut bands, overlapping motion graphics, giant italic numerals. Max-width 1400px, edges sliced.",
buttons: "Chevron-cut buttons (clip-path arrows) in red or ink; italic condensed caps. Hover lunges forward (translate + skew snap).",
cards: "Spec plates with speed-line headers, skewed image masks, mono telemetry rows.",
nav: "Aerodynamic bar: italic wordmark, chevron links, red launch CTA. Slight forward skew on the whole bar.",
imagery: "Motion-blur racing, turbines, runways, chrome macro. Diagonal crops, red duotone options.",
icons: "Arrows, chevrons, gauges, wings — velocity glyphs, 2px italic strokes.",
texture: "Speed lines, carbon weave, brushed aluminum, blueprint grids in spec zones.",
motion: "Velocity: scroll-linked diagonal slides, speed-line draws, number spool-ups. 200ms lunges, ease-in (acceleration!).",
avoid: ["Rounded soft anything", "Pastoral or handmade textures", "Long calm paragraphs", "Static symmetric layouts", "Blue-corporate safety"],
},
{
slug: "sci-fi-ui",
name: "Sci-Fi UI",
description: "Starship consoles: holographic frames, telemetry and systematic wonder.",
category: "Future & Sci-Fi",
tags: ["sci-fi", "hud", "telemetry"],
bg: "#04070D", surface: "#0A1220", ink: "#D7E6FF", muted: "#5B7290", accent: "#4DD8FF", accent2: "#FFB300",
display: "Michroma, Orbitron, sans-serif",
body: "Rajdhani, Inter, sans-serif",
radius: "2–4px; chamfered corners via clip-path on hero panels",
border: "Console frames: 1px cyan hairlines + corner brackets; segmented dividers; arc gauges",
shadow: "Hologram glow: 0 0 20px cyan/20; scanline sweeps; soft blue ambient",
spacing: "Bridge layout: command header, 3-column console grid, 16px panel padding, system-wide 8px grid",
aesthetic: "A believable starship bridge: dark navy void, cyan holographic frames, telemetry that feels alive, amber reserved for cautions. Systematic wonder — every readout labeled, every control plausible. For space, defense-tech, data platforms, and games.",
principles: ["Plausibility over flash: label every readout, units on everything", "Cyan is system, amber is caution, red is emergency — never decorative", "Corners bracketed, never rounded"],
layout: "Bridge grid: header command bar, left nav systems, center viewport (map/scene), right telemetry stack, bottom event log. Responsive collapse to tabs.",
buttons: "Console keys: bordered rectangles with corner ticks, cyan labels; engage actions solid cyan with black text. Two-step arm+confirm for destructive.",
cards: "Holo-panels: hairline frames, bracket corners, header with system name + status dot, telemetry rows in mono.",
nav: "Command bar: ship/product mark, system tabs, alert level pill, stardate clock in mono.",
imagery: "Starfields, nebulae, wireframe planets, blueprint schematics. Cyan-graded, labeled like star charts.",
icons: "Isometric-ish thin icons: orbit, signal, shield, thruster — 1.5px cyan strokes.",
texture: "Starfields, grid spheres, scanlines, holographic noise at 5–8%.",
motion: "Boot sequences, radar sweeps (slow), telemetry tickers, panel power-ons. Calm 300ms system fades; no bounce.",
avoid: ["Fantasy gradients or magic glows without labels", "Rounded playful geometry", "Red/green Christmas semantics", "Fake data that contradicts itself", "Motion that obscures readings"],
},
{
slug: "glassmorphism",
name: "Glassmorphism",
description: "Translucent blurred surfaces floating over vibrant gradient fields.",
category: "Soft & Dimensional",
tags: ["glass", "blur", "translucent"],
bg: "#6C5CE7", surface: "#8B7CF0", ink: "#FFFFFF", muted: "#C9C5E8", accent: "#FFFFFF", accent2: "#00E5FF",
display: "Inter, SF Pro Display, sans-serif",
body: "Inter, SF Pro Text, sans-serif",
radius: "16–24px soft frosted rounding",
border: "Frosted keylines: 1px solid rgba(255,255,255,0.35); inner top-light (inset 0 1px 0 white/30)",
shadow: "Soft depth: 0 8px 32px rgba(0,0,0,0.18); colored ambient from the field behind",
spacing: "Floating rhythm: glass panels overlap gradient blobs, 24–32px padding, 80–110px sections",
aesthetic: "Frosted control-center panels floating over aurora gradients: backdrop-blur 20px, white-at-15% fills, hairline light borders, vivid blurred blobs behind. Airy, premium, and calm-tech. For fintech dashboards, music apps, weather, and productivity tools.",
principles: ["Blur needs a subject: always compose vivid fields behind glass", "White text + 15–25% fills + hairline light borders = the recipe", "One blur value (16–24px) across the whole product"],
layout: "Field + float: full-viewport gradient/blob canvas, frosted nav pill, hero glass panel, widget grid of glass tiles. Max-width 1200px.",
buttons: "Frosted pills: white/20 blur fills with white labels; primary solid white with colored text. Hover brightens fill 10%.",
cards: "Glass tiles: blur 20px, 20px radius, light keyline, 24px padding; metric + sparkline + delta patterns.",
nav: "Floating frosted pill nav centered top; icon links; blur intensifies on scroll.",
imagery: "Gradient blobs, aurora fields, blurred product shots behind glass; avatars with white rings.",
icons: "White duotone glyphs, 1.75px strokes on frosted chips; SF-style clarity.",
texture: "Mesh gradients, blurred orbs, film grain at 3% for premium tooth.",
motion: "Buttery 250–350ms ease-out; panels drift on parallax (±6px); blobs morph slowly (20s).",
avoid: ["Glass over busy photos without scrim (text dies)", "Too-transparent fills (<10% white)", "Dark text on glass without testing every field", "Competing blur values", "Assuming backdrop-filter everywhere — provide solid fallbacks"],
},
{
slug: "neumorphism",
name: "Neumorphism",
description: "Soft extruded plastic: dual shadows sculpting controls from the background.",
category: "Soft & Dimensional",
tags: ["soft-ui", "extruded", "tactile"],
bg: "#E0E5EC", surface: "#E0E5EC", ink: "#4A5568", muted: "#8A94A6", accent: "#4D7CFE", accent2: "#FF6B9D",
display: "Inter, Nunito, sans-serif",
body: "Inter, Nunito, sans-serif",
radius: "12–20px soft sculpted rounding",
border: "None — shadows ARE the borders (light top-left, dark bottom-right)",
shadow: "The signature: 6px 6px 12px #B8BCC4 + -6px -6px 12px #FFFFFF; pressed = inset both",
spacing: "Gallery-spaced: controls need room for shadows to read — 24px+ gaps, 20px padding, 72–96px sections",
aesthetic: "Controls extruded from smart-plastic: the background IS the material, light rakes from top-left, buttons rise or press with inset flips. Monochrome with one pastel accent. Tactile and calm — perfect for music players, calculators, settings, and dashboards.",
principles: ["Background = material: surfaces share the exact bg color", "Light from top-left, always — shadows obey one sun", "Pressed states inset; never mix up/down lighting"],
layout: "Sculpture gallery: widely-spaced extruded panels on the gray ground; dials, sliders, and toggles as hero objects. Max-width 1100px.",
buttons: "Extruded pills/rounds with dual shadows; active/pressed flips to inset. Accent fills allowed on primaries (shadow tints to match).",
cards: "Raised panels (dual shadow) for groups; inset wells for displays/readouts; 16px radius, 24px padding.",
nav: "Extruded tab bar or segmented control; active tab inset; icons + tiny labels, monochrome with accent active.",
imagery: "Minimal: album art in inset wells with rounded frames; soft product renders. Restraint keeps shadows legible.",
icons: "Soft-embossed monochrome glyphs; active states tint accent. 2px rounded strokes.",
texture: "Flat matte plastic; micro-noise at 2% maximum. Cleanliness is structural — dirt kills the illusion.",
motion: "Tactile 150–250ms ease-out; press transitions shadow outset→inset; toggles slide with soft thunk.",
avoid: ["Colorful busy backgrounds (shadows need gray calm)", "Text directly on extruded surfaces below 4.5:1", "Mixing neumorphism with flat cards randomly", "Small dense layouts — shadows need air", "Dark mode neumorphism without re-tuning both shadows"],
},
{
slug: "claymorphism",
name: "Claymorphism",
description: "Puffy 3D clay: inflated pastel forms with chunky inner highlights.",
category: "Soft & Dimensional",
tags: ["clay", "3d", "puffy"],
bg: "#FFE8F0", surface: "#FFF5F8", ink: "#4A3F55", muted: "#9A8FA8", accent: "#FF6B9D", accent2: "#7C5CFF",
display: "Nunito, Quicksand, Baloo 2, sans-serif",
body: "Nunito, Quicksand, sans-serif",
radius: "24–32px puffy; fully round blobs and avatars",
border: "None — form comes from layered shadows, not outlines",
shadow: "Clay stack: inset 2px 2px 4px white/80 + inset -2px -2px 6px color/20 + 8px 8px 16px color/25",
spacing: "Toy-box airy: 28px card padding, 32px+ gaps so puffs don't touch, 80–100px sections",
aesthetic: "Fresh modeling clay: inflated pastel blobs, chunky inner highlights, soft springy everything. Friendly to the point of squishable — dashboards feel like toys, banks feel like candy. For kids, fintech challengers, wellness, and education.",
principles: ["Inflate everything: radius 24px+, shadows stacked 3-deep", "Pastel grounds with deeper-tint shadows (same hue family)", "No outlines — clay holds shape through light alone"],
layout: "Toy shelf: puffy cards floating on pastel with big gaps; blob hero shapes; mascot moments. Max-width 1120px.",
buttons: "Puffy pills with clay shadow stack; hover inflates (scale 1.03); press deflates to inset. Bold rounded labels.",
cards: "Clay tiles: pastel fills, 28px radius, stacked shadows, 28px padding; icon blobs inset on top.",
nav: "Floating clay pill bar with puffy active states; mascot logo mark.",
imagery: "3D clay renders (matching palette!), puffy illustrations, blob-masked photos.",
icons: "Puffy filled icons with inner highlights; strictly rounded, strictly one set.",
texture: "Subtle clay fingerprint noise at 3%; matte finish — no gloss (that's Y2K).",
motion: "Squishy springs: 300–450ms cubic-bezier(0.34,1.8,0.64,1); hover inflate, press deflate; idle bob on mascots.",
avoid: ["Outlines or borders on clay forms", "Dark moody grounds", "Sharp corners anywhere", "Flat minimal layouts (inflate or leave)", "Glossy Y2K highlights — clay is matte"],
},
{
slug: "skeuomorphism",
name: "Skeuomorphism",
description: "Lifelike materials: leather, metal and glass rendered with loving realism.",
category: "Soft & Dimensional",
tags: ["realistic", "materials", "classic-ios"],
bg: "#2B2B2B", surface: "#F5F1E8", ink: "#2B2B2B", muted: "#7A766E", accent: "#0B5FFF", accent2: "#C8A951",
display: "Helvetica Neue, Georgia, serif",
body: "Helvetica Neue, Verdana, sans-serif",
radius: "Real-world: stitched 8px leather panels, round metal dials, glossy buttons",
border: "Material edges: stitched dashes on leather, machined rings on metal, glass reflections",
shadow: "Photographic: layered drop shadows, inner glows, top-light gradients — realism through light",
spacing: "Object-oriented: each control a crafted thing with 16–24px padding; shelves and panels group objects",
aesthetic: "The 2012 camera roll come back as craft: brushed aluminum, stitched leather, green felt, glass shelves, VU meters with needles. Every pixel earns realism. For music gear, cameras, watches, and luxury analog-digital bridges.",
principles: ["Light is physics: one source, consistent reflections and shadows", "Materials must be recognizable in a 48px thumbnail", "Function first: realism serves affordance, not nostalgia alone"],
layout: "Workbench: device-body panels (brushed metal/leather), rack rows of modules, shelf grids. Max-width 1200px.",
buttons: "Machined metal or glossy candy buttons with travel (press sinks 2px + shadow collapses); toggle switches with physics.",
cards: "Material panels: leather with stitching, metal with screws in corners, felt insets for displays.",
nav: "Bookshelf/tab-bar era: wooden shelf tabs, or brushed-metal toolbar with engraved icons.",
imagery: "Photorealistic renders and macro material shots; product on reflective black glass.",
icons: "Photoreal miniatures: tiny cameras, reels, dials. Craft over consistency-with-systems.",
texture: "Leather grain, brushed metal, felt, wood — at full loving fidelity, 15–40%.",
motion: "Physical: needles sweep, reels turn, pages curl, switches thunk (200–400ms ease-in-out). Sound optional, off by default.",
avoid: ["Flat minimalism sneaking in", "Inconsistent light sources between objects", "Unreadable engraved microtext", "Nostalgia without function", "Mixing eras (iOS 6 + leather + glass shelf chaos)"],
},
];
